# **Numpy(Numerical Python) Library :**

### **Copy() & View():**

#### **1.1 Copy():(Deep Copy)**
##### It is numpy method which is used to copy the complete array with different memory location. In copy the data will be independent (different address).
##### Creates a new independent array. Changes in copy DO NOT affect original
##### **Syntax : destination_variable = np.copy(array_variable)**
##### **NOTE : np. Means It will create a new array, .arr means it will modify original array itself**

In [3]:
import numpy as np
original_arr = np.array([1,2,3,4,5,6,7])
copy_arr = np.copy(original_arr)
print(f'Original Array : {original_arr}')
print(f'Copied Array : {copy_arr}')

Original Array : [1 2 3 4 5 6 7]
Copied Array : [1 2 3 4 5 6 7]


##### If I update with respect to copied array means it will not affect the original array

In [10]:
import numpy as np
original_arr = np.array([1,2,3,4,5,6,7])
copy_arr = np.copy(original_arr)

print(f'Original Array : {original_arr}')
print(f'Copied Array : {copy_arr}')

copy_arr[-1]=500
copy_arr[0:2]=100,200

print()
print(f'Original Array : {original_arr}')
print(f'Copied Array : {copy_arr}')

Original Array : [1 2 3 4 5 6 7]
Copied Array : [1 2 3 4 5 6 7]

Original Array : [1 2 3 4 5 6 7]
Copied Array : [100 200   3   4   5   6 500]


In [40]:
import numpy as np
arr1 = np.array([[1,2,3,4],[10,20,30,40]])
arr2 = np.copy(arr1)

print(f'Original Array : {arr1}')
print(f'Copied Array : {arr2}')

arr2[0][1]=120
arr2[1,2]=200

print()
print(f'Original Array : {arr1}')
print(f'Copied Array : {arr2}')

###### Array variable IDs address are different
print()
print(id(arr1))
print(id(arr2))

###### Array Elements address are same
print()
print(id(arr1[0,1]))
print(id(arr2[0,1]))

###### Array Varibale address are different
print()
print(arr1.ctypes.data)
print(arr2.ctypes.data)

Original Array : [[ 1  2  3  4]
 [10 20 30 40]]
Copied Array : [[ 1  2  3  4]
 [10 20 30 40]]

Original Array : [[ 1  2  3  4]
 [10 20 30 40]]
Copied Array : [[  1 120   3   4]
 [ 10  20 200  40]]

1904707647216
1904707649136

1904706523792
1904706523792

1904538974176
1904538974976


In [18]:
import numpy as np
arr1 = np.array([[1,2,3,4],[10,20,30,40]])
arr2 = np.copy(arr1)

print(f'Original Array : {arr1}')
print(f'Copied Array : {arr2}')

arr2[0][1]=120
arr2[1,2]=200

print()
print(f'Original Array : {arr1}')
print(f'Copied Array : {arr2}')

Original Array : [[ 1  2  3  4]
 [10 20 30 40]]
Copied Array : [[ 1  2  3  4]
 [10 20 30 40]]

Original Array : [[ 1  2  3  4]
 [10 20 30 40]]
Copied Array : [[  1 120   3   4]
 [ 10  20 200  40]]


In [33]:
arr1 = np.array([[1,2,3,4],[10,20,30,40]])
arr2 = np.copy(arr1)

print(id(arr1))
print(id(arr2))

print()
print(arr1.ctypes.data)
print(arr2.ctypes.data)

1904706850992
1904707649328

1904538974976
1904538974176


##### The ID is not same even though the array elements are exactle the same. Why Because np. creates a new array memory location. 

In [19]:
arr1=np.array([1,2,3,4])
arr2=np.array([1,2,3,4])
arr3=np.copy(arr1)
print(id(arr1))
print(id(arr2))
print(id(arr3))

1904701963408
1904706850992
1904701032944


##### EVen if we modify it will not affect to original array

In [20]:
arr1=np.array([1,2,3,4])
arr2=np.array([1,2,3,4])
arr3=np.copy(arr1)
print(arr1)
print(arr3)
print()
print(id(arr1))
print(id(arr2))
print(id(arr3))
print()
arr3[0]=1000
print(arr1)
print(arr3)
print()
print(id(arr1))
print(id(arr2))
print(id(arr3))
print()

[1 2 3 4]
[1 2 3 4]

1904707591920
1904701963408
1904706850992

[1 2 3 4]
[1000    2    3    4]

1904707591920
1904701963408
1904706850992



##### To fetch exact address of array we uses array_variable.ctypes.data

In [24]:
print(arr1.ctypes.data)
print(arr2.ctypes.data)
print(arr3.ctypes.data)

1904580585920
1904580586544
1904580583760


#### **1.2 View():(Shallow Copy)**
##### It creates a replica of sarray with same address.
##### For objects address will be different but elements shares a same memory
##### Ot will not Creates a new independent array, It modifies same array with same memory address. Changes in copy it affect original
##### **Syntax : destination_variable = array_variable.view()**
##### **NOTE : np. Means It will create a new array, .arr means it will modify original array itself**

In [26]:
import numpy as np
original_arr = np.array([1,2,3,4,5,6,7])
copy_arr = original_arr.view()
print(f'Original Array : {original_arr}')
print(f'Copied Array : {copy_arr}')

Original Array : [1 2 3 4 5 6 7]
Copied Array : [1 2 3 4 5 6 7]


In [26]:
import numpy as np
original_arr = np.array([1,2,3,4,5,6,7])
copy_arr = original_arr.view()
print(f'Original Array : {original_arr}')
print(f'Copied Array : {copy_arr}')

Original Array : [1 2 3 4 5 6 7]
Copied Array : [1 2 3 4 5 6 7]


##### If we update with respect to original array. It will affect original memory too.

In [27]:
import numpy as np
original_arr = np.array([1,2,3,4,5,6,7])
copy_arr = original_arr.view()

print(f'Original Array : {original_arr}')
print(f'Copied Array : {copy_arr}')

copy_arr[-1]=500
copy_arr[0:2]=100,200

print()
print(f'Original Array : {original_arr}')
print(f'Copied Array : {copy_arr}')

Original Array : [1 2 3 4 5 6 7]
Copied Array : [1 2 3 4 5 6 7]

Original Array : [100 200   3   4   5   6 500]
Copied Array : [100 200   3   4   5   6 500]


In [28]:
import numpy as np
arr1 = np.array([[1,2,3,4],[10,20,30,40]])
arr2 = arr1.view()

print(f'Original Array : {arr1}')
print(f'Copied Array : {arr2}')

arr2[0][1]=120
arr2[1,2]=200

print()
print(f'Original Array : {arr1}')
print(f'Copied Array : {arr2}')

Original Array : [[ 1  2  3  4]
 [10 20 30 40]]
Copied Array : [[ 1  2  3  4]
 [10 20 30 40]]

Original Array : [[  1 120   3   4]
 [ 10  20 200  40]]
Copied Array : [[  1 120   3   4]
 [ 10  20 200  40]]


###### For Array Variable address are different because it is used shared memory but stored in different variable but for array elements address are same

In [29]:
arr1=np.array([1,2,3,4])
arr2=np.array([1,2,3,4])
arr3=arr1.view()
print(id(arr1))
print(id(arr2))
print(id(arr3))

1904701963408
1904707647984
1904701962544


##### Even though ID's are giving differnt address but exact address is same by both address

In [36]:
arr1=np.array([1,2,3,4])
arr3=arr1.view()

print(id(arr1))
print(id(arr3))

print()
print(id(arr1[2]))
print(id(arr3[2]))

print()
print(arr1.ctypes.data)
print(arr3.ctypes.data)

1904706850992
1904701962544

1904706123632
1904706123632

1904580583760
1904580583760


In [32]:
arr1=np.array([1,2,3,4])
arr3=arr1.view()

print(id(arr1))
print(id(arr3))

print()
print(arr1.ctypes.data)
print(arr3.ctypes.data)

1904707648080
1904707647120

1904580584240
1904580584240


In [38]:
import numpy as np
arr1 = np.array([[1,2,3,4],[10,20,30,40]])
arr2 = arr1.view()

print(f'Original Array : {arr1}')
print(f'Copied Array : {arr2}')

arr2[0][1]=120
arr2[1,2]=200

print()
print(f'Original Array : {arr1}')
print(f'Copied Array : {arr2}')

###### Array variable IDs address are different
print()
print(id(arr1))
print(id(arr2))

###### Array Elements address are same
print()
print(id(arr1[0,1]))
print(id(arr2[0,1]))

###### Array Varibale address are same
print()
print(arr1.ctypes.data)
print(arr2.ctypes.data)

Original Array : [[ 1  2  3  4]
 [10 20 30 40]]
Copied Array : [[ 1  2  3  4]
 [10 20 30 40]]

Original Array : [[  1 120   3   4]
 [ 10  20 200  40]]
Copied Array : [[  1 120   3   4]
 [ 10  20 200  40]]

1904707647216
1904707648464

1904706523056
1904706523056

1904538974176
1904538974176
