# **Numpy(Numerical Python) Library :**

#### **1.Array Manipulation Methods :**
##### **1.1 reshape()**
##### **1.2 flatten()**
##### **1.3 ravel()**
##### **1.4 astype()**
##### **1.5 repeat()**
##### **1.6 T (Transpose)**
##### **1.7 flip()**
##### **1.8 delete()**
##### **1.9 Unique()**
##### **1.10 Concatenate()**
##### **1.11 stack()**
##### **1.12 split()**

##### **============================================================** 
#### **1.1 reshape() :** 
##### **============================================================** 
##### It is used to convert 1D array 2D and 1D array to 3D
##### **Syntax : array_variable.reshape()**
##### First We need to create an array by using any one array creation method
##### Then do array reshape from existing array

##### **1-Dimensional to 2-Dimensional Array :** While Converting 1D array to 2D array,the number of array elements in 1D array is equal to the number of rows and columns in the reshape array
##### Menas if our 1D array size is 12 and we need to reshape it for 2D array, so we need to give row and column size in such way that it should be equal to the size of array(1D) when we multiply row and column in 2D array.

In [4]:
import numpy as np
arr = np.array([1,2,3,4,5,6,1,1,1,4,2,3]) # 12
print(arr)
print(arr.reshape(4,3)) # 4*3 = 12

[1 2 3 4 5 6 1 1 1 4 2 3]
[[1 2 3]
 [4 5 6]
 [1 1 1]
 [4 2 3]]


##### **1-Dimensional to 3-Dimensional Array :** While Converting 1D array to 3D array,the number of array elements in 1D array is equal to the number of rows and columns in the reshape array
##### Menas if our 1D array size is 12 and we need to reshape it for 3D array, so we need to give row and column size and total number of elements size in such way that it should be equal to the size of array(1D) when we multiply row ,column and element in 2D array.

In [5]:
import numpy as np
arr = np.array([1,2,3,4,5,6,1,1,1,4,2,3]) # 12
print(arr)
print(arr.reshape(2,3,2)) # 2*3*2 = 12

[1 2 3 4 5 6 1 1 1 4 2 3]
[[[1 2]
  [3 4]
  [5 6]]

 [[1 1]
  [1 4]
  [2 3]]]


In [6]:
import numpy as np
arr = np.array([1,2,3,4,5,6,1,1,1,4,2,3]) # 12
print(arr)
rshape = arr.reshape(2,3,2) # 2*3*2 = 12
print(rshape)
print(rshape.shape)

[1 2 3 4 5 6 1 1 1 4 2 3]
[[[1 2]
  [3 4]
  [5 6]]

 [[1 1]
  [1 4]
  [2 3]]]
(2, 3, 2)


##### **============================================================** 
#### **1.2 flatten() :** 
##### **============================================================** 
##### It returns a copy of the original array converted into 1D.
##### It Creates a new array (copy), where Original array is NOT affected and Uses extra memory
##### **Syntax : array_variable.flatten(order="C")**
##### First We need to create an array by using any one array creation method (create 2D Array,for 1D array it remains unchange)
##### Then check the flatten of an array
##### **Parameters**
##### Here order is optional
##### 'C' → Row-wise (default) : Reads elements row by row
##### 'F' → Column-wise (Fortran style) : Reads elements column by column
##### 'A' → Preserve order based on memory
##### 'K' → Preserve memory layout
##### 
##### What it actually does (Internally) : It Creates a new contiguous array in memory and Copies all elements into a 1D structure and that Breaks the link with original array
##### That means : New memory allocation happens which is Safe to modify.

##### **Note :** For **1-Dimensional Array** the flatten array is remain unchanged, because Flatten() is used to convert multi dimensional array to single dimentional array, where the array elemenets are stored in memory based on specific order

In [7]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
print(f"Original Array : {arr}")
print(f"Flatten Array : {arr.flatten()}")

Original Array : [1 2 3 4 5 6]
Flatten Array : [1 2 3 4 5 6]


##### **Note :** For **2-Dimensional Array** the flatten array is changed, because Flatten() is used to convert multi dimensional array to single dimentional array, where the array elemenets are stored in memory based on specific order
##### Until or unless we pass the order, it will gives flatten() array as it is , It will not change 
##### By default order is row by row, i,e. order='C'

In [8]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(f"Original Array :\n {arr}")
print(f"Flatten Array : {arr.flatten()}")

Original Array :
 [[1 2 3]
 [4 5 6]]
Flatten Array : [1 2 3 4 5 6]


##### **Note :** For **3-Dimensional Array** the flatten array is changed, because Flatten() is used to convert multi dimensional array to single dimentional array, where the array elemenets are stored in memory based on specific order
##### Until or unless we pass the order, it will gives flatten() array as it is , It will not change 
##### By default order is row by row, i,e. order='C'

In [9]:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(f"Original Array :\n {arr}")
print(f"Flatten Array : {arr.flatten()}")

Original Array :
 [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
Flatten Array : [1 2 3 4 5 6 1 2 3 4 5 6]


##### **Order='C'** → Row-wise (default) : Reads elements row by row

##### **For 1D Array with Order='C'** It perform row by row flatten operation. Where First row remain same as first row only because of 1D Array.

In [10]:
## 1D Array
import numpy as np
arr = np.array([1,2,3,4,5,6])
print(f"Original Array :\n {arr}")
print(f"Flatten Array : {arr.flatten(order='C')}")

Original Array :
 [1 2 3 4 5 6]
Flatten Array : [1 2 3 4 5 6]


##### **For 2D Array with Order='C'** It perform row by row flatten operation. Where First row added by 2nd row.

In [11]:
## 2D Array
import numpy as np
arr = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(f"Original Array :\n {arr}")
print(f"Flatten Array : {arr.flatten(order='C')}")

Original Array :
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
Flatten Array : [ 1  2  3  4  5  6  7  8  9 10 11 12]


##### **For 3D Array with Order='C'** It perform row by row flatten operation. Where First row added to next second row then 3rd row

In [12]:
## 3D Array
import numpy as np
arr = np.array([[[1,2,5,6],[7,9,10,12]],[[3,4,5,6],[8,9,11,12]]])
print(f"Original Array :\n {arr}")
print(f"Flatten Array : {arr.flatten(order='C')}")

Original Array :
 [[[ 1  2  5  6]
  [ 7  9 10 12]]

 [[ 3  4  5  6]
  [ 8  9 11 12]]]
Flatten Array : [ 1  2  5  6  7  9 10 12  3  4  5  6  8  9 11 12]


##### **Order=F'** → Column-wise (Fortran style) : Reads elements column by column

##### **For 1D Array with Order='F'** It perform row by row flatten operation. Where First row remain same as first row only because of 1D Array.

In [13]:
## 1D Array
import numpy as np
arr = np.array([1,2,3,4,5,6])
print(f"Original Array :\n {arr}")
print(f"Flatten Array : {arr.flatten(order='F')}")

Original Array :
 [1 2 3 4 5 6]
Flatten Array : [1 2 3 4 5 6]


##### **For 2D Array with Order='F'** It perform column by column flatten operation
##### Original Array :
##### [[1 2 3 4 5 6]
##### [7 8 9 3 4 2]]
##### Flatten Array : [1 7 2 8 3 9 4 3 5 4 6 2

In [14]:
## 2D Array
import numpy as np
arr = np.array([[1,2,3,4,5,6],[7,8,9,3,4,2]])
print(f"Original Array :\n {arr}")
print(f"Flatten Array : {arr.flatten(order='F')}")

Original Array :
 [[1 2 3 4 5 6]
 [7 8 9 3 4 2]]
Flatten Array : [1 7 2 8 3 9 4 3 5 4 6 2]


##### **For 3D Array with Order='F'** It perform column by column flatten operation, Where 1st row ,1st column added with 2nd row 1st column, then  1st row , 2nd column with 2nd row 2nd column added (column by column)
##### Original Array :
##### [[[ 1  2  5  6]
#####  [ 7  9 10 12]]
##### [[ 3  4  5  6]
#####  [ 8  9 11 12]]]
##### Flatten Array : [ 1  3  7  8  2  4  9  9  5  5 10 11  6  6 12 12]

In [15]:
## 3D Array
import numpy as np
arr = np.array([[[1,2,5,6],[7,9,10,12]],[[3,4,5,6],[8,9,11,12]]])
print(f"Original Array :\n {arr}")
print(f"Flatten Array : {arr.flatten(order='F')}")

Original Array :
 [[[ 1  2  5  6]
  [ 7  9 10 12]]

 [[ 3  4  5  6]
  [ 8  9 11 12]]]
Flatten Array : [ 1  3  7  8  2  4  9  9  5  5 10 11  6  6 12 12]


##### **Order='A'** → Preserve order based on memory

##### **For 1D Array with Order='A'** It perform Preserve Order Based memory where oder is already preserved we can't change by flatten operation. Where First row remain same as first row only because of 1D Array.

In [16]:
## 1D Array
import numpy as np
arr = np.array([1,2,3,4,5,6])
print(f"Original Array :\n {arr}")
print(f"Flatten Array : {arr.flatten(order='A')}")

Original Array :
 [1 2 3 4 5 6]
Flatten Array : [1 2 3 4 5 6]


##### **For 2D Array with Order='A'** It perform Preserve Order Based memory where oder is already preserved we can't change by flatten operation. Where First row remain same as first row only because of Array order is preserved.

In [17]:
## 2D Array
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(f"Original Array :\n {arr}")
print(f"Flatten Array : {arr.flatten(order='A')}")

Original Array :
 [[1 2 3]
 [4 5 6]]
Flatten Array : [1 2 3 4 5 6]


##### **For 3D Array with Order='A'** It perform Preserve Order Based memory where oder is already preserved we can't change by flatten operation. Where First row remain same as first row only because of Array order is preserved.

In [18]:
## 3D Array
import numpy as np
arr = np.array([1,2,3,4,5,6])
print(f"Original Array :\n {arr}")
print(f"Flatten Array : {arr.flatten(order='A')}")

Original Array :
 [1 2 3 4 5 6]
Flatten Array : [1 2 3 4 5 6]


##### **Order='K'** → Preserve memory layout

##### **For 1D Array with Order='K'** It perform Preserve memory layout where oder is already preserved we can't change by flatten operation. Where First row remain same as first row only because of Array order is preserved in memory.

In [19]:
## 1D Array
import numpy as np
arr = np.array([1,2,3,4,5,6])
print(f"Original Array :\n {arr}")
print(f"Flatten Array : {arr.flatten(order='K')}")

Original Array :
 [1 2 3 4 5 6]
Flatten Array : [1 2 3 4 5 6]


##### **For 2D Array with Order='K'** It perform Preserve memory layout where oder is already preserved we can't change by flatten operation. Where First row remain same as first row only because of Array order is preserved in memory.

In [20]:
## 2D Array
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(f"Original Array :\n {arr}")
print(f"Flatten Array : {arr.flatten(order='K')}")

Original Array :
 [[1 2 3]
 [4 5 6]]
Flatten Array : [1 2 3 4 5 6]


##### **For 3D Array with Order='K'** It perform Preserve memory layout where oder is already preserved we can't change by flatten operation. Where First row remain same as first row only because of Array order is preserved in memory.

In [21]:
## 3D Array
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[2,4,5],[5,6,3]]])
print(f"Original Array :\n {arr}")
print(f"Flatten Array : {arr.flatten(order='C')}")

Original Array :
 [[[1 2 3]
  [4 5 6]]

 [[2 4 5]
  [5 6 3]]]
Flatten Array : [1 2 3 4 5 6 2 4 5 5 6 3]


##### **============================================================** 
#### **1.3 ravel() :** 
##### **============================================================** 
##### It returns a view of the original array (not a copy).If changes made then it also affects a original array
##### Returns a view (same memory) & Changes affect original array with Faster and memory-efficient
##### **Syntax : array_variable.ravel(order="C")**
##### First We need to create an array by using any one array creation method (create 2D Array,for 1D array it remains unchange)
##### Then check the ravel of an array
##### **Parameters**
##### Here order is optional
##### 'C' → Row-wise (default) : Reads elements row by row
##### 'F' → Column-wise (Fortran style) : Reads elements column by column
##### 'A' → Preserve order based on memory
##### 'K' → Preserve memory layout
##### What it actually does (Internally) : It Returns a view (whenever possible) & Does not copy data and Points to same memory block
##### If memory layout is complex → it may return a copy (rare case)

##### **1-Dimensional Array :** Here if we update one element, It also affects the original array ,It will not create a separate copy, It access same original one and modify it

In [23]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
rav = arr.ravel()
rav[0]=100
print(f"Original Array : {arr}")
print(f"Flatten Array : {rav}")

Original Array : [100   2   3   4   5   6]
Flatten Array : [100   2   3   4   5   6]


##### **2-Dimensional Array :** Here if we update one element, It also affects the original array ,It will not create a separate copy, It access same original one and modify it
##### Here if i am not mentioning the 2nd Index , By default it consider 0 Index Position from column

In [24]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
rav = arr.ravel()
rav[0]=100
print(f"Original Array : {arr}")
print(f"Flatten Array : {rav}")

Original Array : [[100   2   3]
 [  4   5   6]]
Flatten Array : [100   2   3   4   5   6]


##### Here if i am mentioning the 2nd Index then it raises error Because After applying ravel() It becomes single 1D array
##### We can apply row and column index before applying ravel

In [25]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
arr[0][1]=100
rav = arr.ravel()
print(f"Original Array : {arr}")
print(f"Flatten Array : {rav}")

Original Array : [[  1 100   3]
 [  4   5   6]]
Flatten Array : [  1 100   3   4   5   6]


##### Even though we can update the value even after applying ravel, But to change make use of array_variable only to update the element then go through ravel

In [26]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
rav = arr.ravel()
arr[0][1]=100
print(f"Original Array : {arr}")
print(f"Flatten Array : {rav}")

Original Array : [[  1 100   3]
 [  4   5   6]]
Flatten Array : [  1 100   3   4   5   6]


In [27]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
rav = arr.ravel()
rav[0]=100
print(f"Original Array : {arr}")
print(f"Flatten Array : {rav}")

Original Array : [[100   2   3]
 [  4   5   6]]
Flatten Array : [100   2   3   4   5   6]


##### After applying ravel We can't do 2D Indexing Because it becomes 1D array

In [28]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
rav = arr.ravel()
rav[0][1]=100
print(f"Original Array : {arr}")
print(f"Flatten Array : {rav}")

TypeError: 'numpy.int64' object does not support item assignment

##### **Order='C' :** Row by Row ( It reads element row by row) 
##### For 1D array it will not work because it converts the 2D array or 3D array to 1D array of ravel
##### If we done any changes with respect to ravel array then it also change in original array

In [29]:
# 1D Array
import numpy as np
arr = np.array([1,2,3,5,6])
rav = arr.ravel(order='C')
rav[0]=100
print(f"Original Array : {arr}")
print(f"Flatten Array : {rav}")

Original Array : [100   2   3   5   6]
Flatten Array : [100   2   3   5   6]


In [30]:
# 2D Array
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
rav = arr.ravel(order='C')
rav[0]=100
print(f"Original Array : {arr}")
print(f"Flatten Array : {rav}")

Original Array : [[100   2   3]
 [  4   5   6]]
Flatten Array : [100   2   3   4   5   6]


In [31]:
# 3D Array
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[6,2,6],[9,2,4]]])
rav = arr.ravel(order='C')
rav[0]=100
print(f"Original Array : {arr}")
print(f"Flatten Array : {rav}")

Original Array : [[[100   2   3]
  [  4   5   6]]

 [[  6   2   6]
  [  9   2   4]]]
Flatten Array : [100   2   3   4   5   6   6   2   6   9   2   4]


##### **Order='F' :** Column by column ( It reads element column by column) 
##### For 1D array it will not work because it converts the 2D array or 3D array to 1D array of ravel
##### If we done any changes with respect to ravel array then it also change in original array

In [32]:
# 1D Array
import numpy as np
arr = np.array([1,2,3,4,5,6])
rav = arr.ravel(order='F')
rav[0]=100
print(f"Original Array : {arr}")
print(f"Flatten Array : {rav}")

Original Array : [100   2   3   4   5   6]
Flatten Array : [100   2   3   4   5   6]


In [33]:
# 2D Array
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
rav = arr.ravel(order='F')
rav[0]=100
print(f"Original Array : {arr}")
print(f"Flatten Array : {rav}")

Original Array : [[1 2 3]
 [4 5 6]]
Flatten Array : [100   4   2   5   3   6]


In [34]:
# 3D Array
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[6,2,6],[9,2,4]]])
rav = arr.ravel(order='F')
rav[0]=100
print(f"Original Array : {arr}")
print(f"Flatten Array : {rav}")

Original Array : [[[1 2 3]
  [4 5 6]]

 [[6 2 6]
  [9 2 4]]]
Flatten Array : [100   6   4   9   2   2   5   2   3   6   6   4]


##### **Order='A' :** It reads by Preserve Order Based on Memory  
##### For 1D array it will not work because it converts the 2D array or 3D array to 1D array of ravel
##### If we done any changes with respect to ravel array then it also change in original array

In [35]:
# 1D Array
import numpy as np
arr = np.array([1,2,4,5,6])
rav = arr.ravel(order='A')
rav[0]=100
print(f"Original Array : {arr}")
print(f"Flatten Array : {rav}")

Original Array : [100   2   4   5   6]
Flatten Array : [100   2   4   5   6]


In [36]:
# 2D Array
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
rav = arr.ravel(order='A')
rav[0]=100
print(f"Original Array : {arr}")
print(f"Flatten Array : {rav}")

Original Array : [[100   2   3]
 [  4   5   6]]
Flatten Array : [100   2   3   4   5   6]


In [37]:
# 3D Array
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[6,2,6],[9,2,4]]])
rav = arr.ravel(order='A')
rav[0]=100
print(f"Original Array : {arr}")
print(f"Flatten Array : {rav}")

Original Array : [[[100   2   3]
  [  4   5   6]]

 [[  6   2   6]
  [  9   2   4]]]
Flatten Array : [100   2   3   4   5   6   6   2   6   9   2   4]


##### **Order='K' :** It reads by Preserve Memory Layout 
##### For 1D array it will not work because it converts the 2D array or 3D array to 1D array of ravel
##### If we done any changes with respect to ravel array then it also change in original array

In [38]:
# 1D Array
import numpy as np
arr = np.array([1,2,3,5,6])
rav = arr.ravel(order='K')
rav[0]=100
print(f"Original Array : {arr}")
print(f"Flatten Array : {rav}")

Original Array : [100   2   3   5   6]
Flatten Array : [100   2   3   5   6]


In [39]:
# 2D Array
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
rav = arr.ravel(order='K')
rav[0]=100
print(f"Original Array : {arr}")
print(f"Flatten Array : {rav}")

Original Array : [[100   2   3]
 [  4   5   6]]
Flatten Array : [100   2   3   4   5   6]


In [40]:
# 3D Array
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[6,2,6],[9,2,4]]])
rav = arr.ravel(order='K')
rav[0]=100
print(f"Original Array : {arr}")
print(f"Flatten Array : {rav}")

Original Array : [[[100   2   3]
  [  4   5   6]]

 [[  6   2   6]
  [  9   2   4]]]
Flatten Array : [100   2   3   4   5   6   6   2   6   9   2   4]


##### **============================================================** 
#### **1.4 astype() :** 
##### **============================================================** 
##### It is used to convert Data type from one data type to another data type
##### **Syntax: array_variable.astype(dtype, order='K', casting='unsafe', subok=True, copy=True)**
##### First We need to create an array by using any one array creation method
##### Then chnage the original array type to required specific array
##### only dtype is manadatory, rest other arguements are optional
##### **Parameters:**
##### **dtype:** The data type you want to change into.(Required)
##### **order:** Controls the memory layout order of the result. Options are ‘C’, ‘F’, ‘A’, ‘K’.(Default Order is 'K')
##### 'C' → Row-major order
##### 'F' → Column-major order
##### 'A' → Preserve if possible
##### 'K' → Keep original memory order
##### **casting:** Controls the type of data casting. Options are ‘no’, ‘equiv’, ‘safe’, ‘same_kind’, ‘unsafe’.(Default Casting is 'No')
##### 'no' - No conversion allowed unless datatype is exactly same.
##### 'equiv' - Only allow conversions that do NOT change the data representation in memory
##### 'safe' - It allows only safe conversion.Because converting float to int may lose decimal values.
##### 'same_kind' - Allows conversion within similar type family.Int->Float is allowed because both are belongs to numeric category.
##### 'unsafe' - It allows any conversion.Decimal values will be removed.
##### **subok:** If True, then sub-classes will be passed-through, otherwise the returned array will be forced to be a base-class array.(Default subok is True)
##### Determines whether subclasses are preserved. subok=True → keeps matrix type, subok=False → converts to normal ndarray
##### **copy:** By default, astype() returns a newly allocated array. If set to false, the input array is returned instead of a copy.(Default Copy is True)
##### Determines whether a new array should be created. Copy=True, A completely new array is created. Copy=False,Since datatype is already int, NumPy returns the same array instead of creating a copy.
##### **Return:** The method returns a new array with new data type.

##### **dtype:** : The data type you want to change into.

In [48]:
# 1D Array :
arr = np.array([1,2,3,4,5])
arr2 = arr.astype(float)
print(arr.dtype)
print(arr2.dtype)
print(arr)
print(arr2)

int64
float64
[1 2 3 4 5]
[1. 2. 3. 4. 5.]


In [49]:
# 1D Array :
arr = np.array([1,2,3,4,5])
print(f'Original Array : {arr}')
print(f'dtype Array (int) : {arr.astype(int)} => {arr.dtype}')
print(f'dtype Array (float) : {arr.astype(float)} => {arr.dtype}')
print(f'dtype Array (complex) : {arr.astype(complex)} => {arr.dtype}')
print(f'dtype Array (boolean) : {arr.astype(bool)} => {arr.dtype}')
print(f'dtype Array (string) : {arr.astype(str)} => {arr.dtype}')
print(f'dtype Array (list) : {arr.astype(list)} => {arr.dtype}')
print(f'dtype Array (tuple) : {arr.astype(tuple)} => {arr.dtype}')
print(f'dtype Array (set) : {arr.astype(set)} => {arr.dtype}')
print(f'dtype Array (dictionary) : {arr.astype(dict)} => {arr.dtype}')
print(f'dtype Array (frozenset) : {arr.astype(frozenset)} => {arr.dtype}')
print(f'dtype Array (range) : {arr.astype(range)} => {arr.dtype}')

Original Array : [1 2 3 4 5]
dtype Array (int) : [1 2 3 4 5] => int64
dtype Array (float) : [1. 2. 3. 4. 5.] => int64
dtype Array (complex) : [1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j] => int64
dtype Array (boolean) : [ True  True  True  True  True] => int64
dtype Array (string) : ['1' '2' '3' '4' '5'] => int64
dtype Array (list) : [1 2 3 4 5] => int64
dtype Array (tuple) : [1 2 3 4 5] => int64
dtype Array (set) : [1 2 3 4 5] => int64
dtype Array (dictionary) : [1 2 3 4 5] => int64
dtype Array (frozenset) : [1 2 3 4 5] => int64
dtype Array (range) : [1 2 3 4 5] => int64


##### **order:** Controls the memory layout order of the result. Options are ‘C’, ‘F’, ‘A’, ‘K’.
##### 'C' → Row-major order
##### 'F' → Column-major order
##### 'A' → Preserve if possible
##### 'K' → Keep original memory order

In [53]:
# 2D Array :
arr = np.array([[1,2,3,4,5],[7,8,9,10,11]])
arr2 = arr.astype(float,order='C')
print(f'Original Array :{arr}')
print(f'Astype() Array :{arr2}')

Original Array :[[ 1  2  3  4  5]
 [ 7  8  9 10 11]]
Astype() Array :[[ 1.  2.  3.  4.  5.]
 [ 7.  8.  9. 10. 11.]]


In [55]:
# 2D Array :
arr = np.array([[1,2,3,4,5],[7,8,9,10,11]])
arr2 = arr.astype(float,order='F')
print(f'Original Array :{arr}')
print(f'Astype() Array :{arr2}')

Original Array :[[ 1  2  3  4  5]
 [ 7  8  9 10 11]]
Astype() Array :[[ 1.  2.  3.  4.  5.]
 [ 7.  8.  9. 10. 11.]]


In [57]:
# 2D Array :
arr = np.array([[1,2,3,4,5],[7,8,9,10,11]])
arr2 = arr.astype(float,order='K')
print(f'Original Array :{arr}')
print(f'Astype() Array :{arr2}')

Original Array :[[ 1  2  3  4  5]
 [ 7  8  9 10 11]]
Astype() Array :[[ 1.  2.  3.  4.  5.]
 [ 7.  8.  9. 10. 11.]]


In [58]:
# 2D Array :
arr = np.array([[1,2,3,4,5],[7,8,9,10,11]])
arr2 = arr.astype(float,order='A')
print(f'Original Array :{arr}')
print(f'Astype() Array :{arr2}')

Original Array :[[ 1  2  3  4  5]
 [ 7  8  9 10 11]]
Astype() Array :[[ 1.  2.  3.  4.  5.]
 [ 7.  8.  9. 10. 11.]]


In [60]:
# 2D Array :
arr = np.array([[1,2,3,4,5],[7,8,9,10,11]])
arr2 = arr.astype(float,order='A')
arr2

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 7.,  8.,  9., 10., 11.]])

##### **casting :** Controls the type of data casting. Options are ‘no’, ‘equiv’, ‘safe’, ‘same_kind’, ‘unsafe’.(Default Casting is 'No')
##### 'no' - No conversion allowed unless datatype is exactly same.
##### 'equiv' - Only allow conversions that do NOT change the data representation in memory
##### 'safe' - It allows only safe conversion.Because converting float to int may lose decimal values.
##### 'same_kind' - Allows conversion within similar type family.Int->Float is allowed because both are belongs to numeric category.
##### 'unsafe' - It allows any conversion.Decimal values will be removed.

##### While creating an array I have passed integer array element and one float array element. According to the rule of order of priority float have high priority than it , that's why all array elements are converted to float only

In [73]:
# 2D Array :
arr = np.array([[1,2,3.7,4,5],[7,8,9,10,11]])
arr2 = arr.astype(float,casting='no')
print(f'Original Array :{arr}')
print(f'Astype() Array :{arr2}')

Original Array :[[ 1.   2.   3.7  4.   5. ]
 [ 7.   8.   9.  10.  11. ]]
Astype() Array :[[ 1.   2.   3.7  4.   5. ]
 [ 7.   8.   9.  10.  11. ]]


In [72]:
# 2D Array :
arr = np.array([[1,2,3,4,5],[7,8,9,10,11]])
arr2 = arr.astype(int,casting='no')
print(f'Original Array :{arr}')
print(f'Astype() Array :{arr2}')

Original Array :[[ 1  2  3  4  5]
 [ 7  8  9 10 11]]
Astype() Array :[[ 1  2  3  4  5]
 [ 7  8  9 10 11]]


##### In This below Example We got Error Becuase, array data type and astype() method both are different data types , casting='No' means both the data type must be same

In [74]:
# 2D Array :
arr = np.array([[1,2,3,4,5],[7,8,9,10,11]])
arr2 = arr.astype(float,casting='no')
print(f'Original Array :{arr}')
print(f'Astype() Array :{arr2}')

TypeError: Cannot cast array data from dtype('int64') to dtype('float64') according to the rule 'no'

##### **casting='equiv' :** It should not change the memory representation, Hence it won't allow to conversion with different data type.. Same Data type can be allowed

In [77]:
# 2D Array :
arr = np.array([[1,2,3,4,5],[7,8,9,10,11]])
arr2 = arr.astype(int,casting='equiv')
print(f'Original Array :{arr}')
print(f'Astype() Array :{arr2}')

Original Array :[[ 1  2  3  4  5]
 [ 7  8  9 10 11]]
Astype() Array :[[ 1  2  3  4  5]
 [ 7  8  9 10 11]]


In [76]:
# 2D Array :
arr = np.array([[1,2,3,4,5],[7,8,9,10,11]])
arr2 = arr.astype(float,casting='equiv')
print(f'Original Array :{arr}')
print(f'Astype() Array :{arr2}')

TypeError: Cannot cast array data from dtype('int64') to dtype('float64') according to the rule 'equiv'

##### **casting='safe' :** It allows only safe conversion.Because converting float to int may lose decimal values.. Same Data type can be allowed

In [78]:
# 2D Array :
arr = np.array([[1.2,3.9,8.4],[7.9,8.2,9.1]])
arr2 = arr.astype(float,casting='safe')
print(f'Original Array :{arr}')
print(f'Astype() Array :{arr2}')

Original Array :[[1.2 3.9 8.4]
 [7.9 8.2 9.1]]
Astype() Array :[[1.2 3.9 8.4]
 [7.9 8.2 9.1]]


In [67]:
# 2D Array :
arr = np.array([[1.2,3.9,8.4],[7.9,8.2,9.1]])
arr2 = arr.astype(int,casting='safe')
print(f'Original Array :{arr}')
print(f'Astype() Array :{arr2}')

TypeError: Cannot cast array data from dtype('float64') to dtype('int64') according to the rule 'safe'

##### **casting='unsafe' :** It allows any conversion.Decimal values will be removed.

In [79]:
# 2D Array :
arr = np.array([[1.2,3.9,8.4],[7.9,8.2,9.1]])
arr2 = arr.astype(int,casting='unsafe')
print(f'Original Array :{arr}')
print(f'Astype() Array :{arr2}')

Original Array :[[1.2 3.9 8.4]
 [7.9 8.2 9.1]]
Astype() Array :[[1 3 8]
 [7 8 9]]


In [80]:
# 2D Array :
arr = np.array([[1.2,3.9,8.4],[7.9,8.2,9.1]])
arr2 = arr.astype(float,casting='unsafe')
print(f'Original Array :{arr}')
print(f'Astype() Array :{arr2}')

Original Array :[[1.2 3.9 8.4]
 [7.9 8.2 9.1]]
Astype() Array :[[1.2 3.9 8.4]
 [7.9 8.2 9.1]]


##### **casting='same_kind' :** Allows conversion within similar type family.Int->Float is allowed because both are belongs to numeric category

In [83]:
# 2D Array :
arr = np.array([[1,2,4],[4,2,5]])
arr2 = arr.astype(float,casting='same_kind')
print(f'Original Array :{arr}')
print(f'Astype() Array :{arr2}')

Original Array :[[1 2 4]
 [4 2 5]]
Astype() Array :[[1. 2. 4.]
 [4. 2. 5.]]


In [82]:
# 2D Array :
arr = np.array([[1.2,3.9,8.4],[7.9,8.2,9.1]])
arr2 = arr.astype(int,casting='same_kind')
print(f'Original Array :{arr}')
print(f'Astype() Array :{arr2}')

TypeError: Cannot cast array data from dtype('float64') to dtype('int64') according to the rule 'same_kind'

##### **subok:** If True, then sub-classes will be passed-through, otherwise the returned array will be forced to be a base-class array.(Default subok is True)
##### Determines whether subclasses are preserved. 
##### subok=True → keeps matrix type, subok=False → converts to normal ndarray

In [91]:
# 2D Array :
arr = np.matrix([[1,2],[3,4]])
arr2 = arr.astype(float,subok=True)
print(f'Original Array :{arr}')
print(f'Astype() Array :{arr2}')
print(type(arr))
print(type(arr2))

Original Array :[[1 2]
 [3 4]]
Astype() Array :[[1. 2.]
 [3. 4.]]
<class 'numpy.matrix'>
<class 'numpy.matrix'>


In [89]:
# 2D Array :
arr = np.array([[1,2,3],[4,5,6]])
arr2 = arr.astype(float,subok=False)
print(f'Original Array :{arr}')
print(f'Astype() Array :{arr2}')
print(type(arr))
print(type(arr2))

Original Array :[[1 2 3]
 [4 5 6]]
Astype() Array :[[1. 2. 3.]
 [4. 5. 6.]]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


##### **Copy:** By default, astype() returns a newly allocated array. If set to false, the input array is returned instead of a copy.(Default Copy is True)
##### Determines whether a new array should be created. Copy=True, A completely new array is created. Copy=False,Since datatype is already int, NumPy returns the same array instead of creating a copy.¶

##### If copy=True : A completely new array is created.
##### If copy=False : NumPy returns the same array instead of creating a copy.

In [102]:
# 2D Array :
arr = np.array([[1,2,3],[4,5,6]])
arr2 = arr.astype(int,copy=False)
print(f'Original Array :{arr}')
print(f'Astype() Array :{arr2}')
print(arr is arr2)

Original Array :[[1 2 3]
 [4 5 6]]
Astype() Array :[[1 2 3]
 [4 5 6]]
True


In [101]:
# 2D Array :
arr = np.array([[1,2,3],[4,5,6]])
arr2 = arr.astype(float,copy=False)
print(f'Original Array :{arr}')
print(f'Astype() Array :{arr2}')
print(arr is arr2)

Original Array :[[1 2 3]
 [4 5 6]]
Astype() Array :[[1. 2. 3.]
 [4. 5. 6.]]
False


In [100]:
# 2D Array :
arr = np.array([[1,2,3],[4,5,6]])
arr2 = arr.astype(int,copy=True)
print(f'Original Array :{arr}')
print(f'Astype() Array :{arr2}')
print(arr is arr2)

Original Array :[[1 2 3]
 [4 5 6]]
Astype() Array :[[1 2 3]
 [4 5 6]]
False


In [99]:
# 2D Array :
arr = np.array([[1,2,3],[4,5,6]])
arr2 = arr.astype(float,copy=True)
print(f'Original Array :{arr}')
print(f'Astype() Array :{arr2}')
print(arr is arr2)

Original Array :[[1 2 3]
 [4 5 6]]
Astype() Array :[[1. 2. 3.]
 [4. 5. 6.]]
False


##### **============================================================** 
#### **1.5 repeat() :** 
##### **============================================================** 
##### It is used to repeat the elements based on given n value.
##### **Syntax: np.repeat(arr_variable, repetitions, axis = None)**
##### Axis is optional here
##### **Parameter:**
##### **array_variable** - Input array
##### **repetitions** - Number of repetitions of each array elements along the given axis.
##### **axis** - Axis along which we want to repeat values. By default, it returns a flat output array.
##### An array with repetitions of array - arr elements as per repetitions, number of times we want to repeat arr  

In [103]:
arr = np.arange(10)
print(f'Original Array : {arr}')
np.repeat(arr,4)

Original Array : [0 1 2 3 4 5 6 7 8 9]


array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5,
       5, 5, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8, 8, 8, 9, 9, 9, 9])

In [106]:
arr = np.arange(10)
print(f'Original Array : {arr}')
np.repeat(arr,4,axis=0)

Original Array : [0 1 2 3 4 5 6 7 8 9]


array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5,
       5, 5, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8, 8, 8, 9, 9, 9, 9])

##### For axis=1 : Array Dimension must be more than 1D (2D atleast) to see the exactly what will happen

##### axis=1 → horizontal expansion(row wise)
##### axis=0 → vertical expansion(column wise)

In [109]:
arr = np.arange(10).reshape(2,5)
print(f'Original Array : {arr}')
np.repeat(arr,4,axis=1) 

Original Array : [[0 1 2 3 4]
 [5 6 7 8 9]]


array([[0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4],
       [5, 5, 5, 5, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8, 8, 8, 9, 9, 9, 9]])

In [110]:
arr = np.arange(10).reshape(2,5)
print(f'Original Array : {arr}')
np.repeat(arr,4,axis=0) 

Original Array : [[0 1 2 3 4]
 [5 6 7 8 9]]


array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [5, 6, 7, 8, 9],
       [5, 6, 7, 8, 9],
       [5, 6, 7, 8, 9]])

##### **============================================================** 
#### **1.6 Transpose :** 
##### **============================================================** 
##### It is used to perform transpose matrix where it converts rows to columns and columns to rows.
##### **Syntax: arra_variable.T**
##### When it comes to 3D array transpose it will used elements to convert instead of depending on rows and columns

##### **1-Dimensional Array:**

##### Here in 1D Array We cannot see the changes in transpose operation Because there is only onr row 

In [116]:
import numpy as np
arr = np.arange(20)
print(f'Original Array : \n{arr}')
print(f'Transpose Array : \n{arr.T}')

Original Array : 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Transpose Array : 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


##### **2-Dimensional Array:**

In [115]:
import numpy as np
arr = np.arange(20).reshape(4,5)
print(f'Original Array : \n{arr}')
print(f'Transpose Array : \n{arr.T}')

Original Array : 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
Transpose Array : 
[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]


##### **3-Dimensional Array:** When it comes to 3D array transpose it will used elements to convert instead of depending on rows and columns

In [117]:
import numpy as np
arr = np.arange(60).reshape(3,4,5)
print(f'Original Array : \n{arr}')
print(f'Transpose Array : \n{arr.T}')

Original Array : 
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]
Transpose Array : 
[[[ 0 20 40]
  [ 5 25 45]
  [10 30 50]
  [15 35 55]]

 [[ 1 21 41]
  [ 6 26 46]
  [11 31 51]
  [16 36 56]]

 [[ 2 22 42]
  [ 7 27 47]
  [12 32 52]
  [17 37 57]]

 [[ 3 23 43]
  [ 8 28 48]
  [13 33 53]
  [18 38 58]]

 [[ 4 24 44]
  [ 9 29 49]
  [14 34 54]
  [19 39 59]]]


##### **============================================================** 
#### **1.7 flip() :** 
##### **============================================================** 
##### It is used to reverse the complete array. **OR** It is used to reverses the order of array elements along the specified axis, preserving the shape of the array.
##### **Syntax: np.flip(array, axis)**
##### Axis is Optional here
##### **Parameters :** 
##### array : Array to be input 
##### axis : axis along which array is reversed.
##### Returns :  reversed array with shape preserved

##### **1-Dimensional Array:**

In [121]:
arr = np.arange(10)
print(f'Original Array : {arr}')
print(f'Flip Array : {np.flip(arr)}')

Original Array : [0 1 2 3 4 5 6 7 8 9]
Flip Array : [9 8 7 6 5 4 3 2 1 0]


##### **2-Dimensional Array:**

In [123]:
arr = np.arange(10).reshape(5,2)
print(f'Original Array : \n{arr}')
print(f'Flip Array : \n{np.flip(arr)}')

Original Array : 
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
Flip Array : 
[[9 8]
 [7 6]
 [5 4]
 [3 2]
 [1 0]]


##### **3-Dimensional Array:**

In [125]:
arr = np.arange(20).reshape(2,5,2)
print(f'Original Array : \n{arr}')
print(f'Flip Array : \n{np.flip(arr)}')

Original Array : 
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]
Flip Array : 
[[[19 18]
  [17 16]
  [15 14]
  [13 12]
  [11 10]]

 [[ 9  8]
  [ 7  6]
  [ 5  4]
  [ 3  2]
  [ 1  0]]]


##### **axis :**

In [129]:
arr = np.arange(10).reshape(5,2)
print(f'Original Array : \n{arr}')
print(f'Flip Array : \n{np.flip(arr)}')

Original Array : 
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
Flip Array : 
[[9 8]
 [7 6]
 [5 4]
 [3 2]
 [1 0]]


##### **Axis=0** Row wise Expansion

In [127]:
arr = np.arange(10).reshape(5,2)
print(f'Original Array : \n{arr}')
print(f'Flip Array : \n{np.flip(arr,axis=0)}')

Original Array : 
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
Flip Array : 
[[8 9]
 [6 7]
 [4 5]
 [2 3]
 [0 1]]


In [130]:
arr = np.arange(12).reshape(3,2,2)
print(f'Original Array : \n{arr}')
print(f'Flip Array : \n{np.flip(arr,axis=0)}')

Original Array : 
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]
Flip Array : 
[[[ 8  9]
  [10 11]]

 [[ 4  5]
  [ 6  7]]

 [[ 0  1]
  [ 2  3]]]


##### **Axis=1** Column wise Expansion

In [127]:
arr = np.arange(10).reshape(5,2)
print(f'Original Array : \n{arr}')
print(f'Flip Array : \n{np.flip(arr,axis=1)}')

Original Array : 
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
Flip Array : 
[[8 9]
 [6 7]
 [4 5]
 [2 3]
 [0 1]]


In [131]:
arr = np.arange(12).reshape(3,2,2)
print(f'Original Array : \n{arr}')
print(f'Flip Array : \n{np.flip(arr,axis=1)}')

Original Array : 
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]
Flip Array : 
[[[ 2  3]
  [ 0  1]]

 [[ 6  7]
  [ 4  5]]

 [[10 11]
  [ 8  9]]]


##### **============================================================** 
#### **1.8 delete() :** 
##### **============================================================**
##### It removes the element based on given  index
##### **Syntax: np.delete(array_variable, object, axis = None)**
##### axis is optional here
##### **Parameters:** 
##### array - Input array.
##### object - Sub-array to delete
##### axis - Axis along which we want to delete sub-arrays. By default, it object is applied to flattened array
##### Return: A new NumPy array with the specified elements removed.
##### **Note:** It only removes the element based on index and return single dimension array
##### It will not support indexing like python supports [row][col] or [row][col][ele] like this, It supports only [row,col] or [row,col,ele]

##### **1-Dimensional Array:**

##### Single Element delete : use just index number [index]

In [138]:
arr = np.arange(1,10)
print(f'Original Array :{arr}')
print(f'After Deleted Array : {np.delete(arr,[1])}') # index 1 elemenet is removed 

Original Array :[1 2 3 4 5 6 7 8 9]
After Deleted Array : [1 3 4 5 6 7 8 9]


##### Multiple Element delete : use just index number [index1,index2], Where at a time 2 elemnets will be deleted bassed on index value

In [154]:
arr = np.arange(1,10)
print(f'Original Array :{arr}')
print(f'After Deleted Array : {np.delete(arr,[1,2])}')  

Original Array :[1 2 3 4 5 6 7 8 9]
After Deleted Array : [1 4 5 6 7 8 9]


In [153]:
arr = np.arange(1,10)
print(f'Original Array :{arr}')
print(f'After Deleted Array : {np.delete(arr,[1,2,4,3])}')  

Original Array :[1 2 3 4 5 6 7 8 9]
After Deleted Array : [1 6 7 8 9]


##### **2-Dimensional Array:** for 2D give both row and column index  [row-ide,col-idx]

In [166]:
arr = np.arange(1,21).reshape(5,4)
print(f'Original Array :\n{arr}')
print(f'After Deleted Array : \n{np.delete(arr,[1][0])}')  

Original Array :
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
After Deleted Array : 
[ 1  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [165]:
arr = np.arange(1,21).reshape(5,4)
print(f'Original Array :\n{arr}')
print(f'After Deleted Array : \n{np.delete(arr,[1,0])}')  

Original Array :
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
After Deleted Array : 
[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


##### Here if we not specify column index ,it will automatically take single index as a element index

In [164]:
arr = np.arange(1,21).reshape(5,4)
print(f'Original Array :\n{arr}')
print(f'After Deleted Array : \n{np.delete(arr,[12])}')   

Original Array :
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
After Deleted Array : 
[ 1  2  3  4  5  6  7  8  9 10 11 12 14 15 16 17 18 19 20]


##### **3-Dimensional Array:** for 3D give both row and column index [row_index,col_index,element_idx]

In [163]:
arr = np.arange(1,25).reshape(3,2,4)
print(f'Original Array :\n{arr}')
print(f'After Deleted Array : \n{np.delete(arr,1)}') 

Original Array :
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]
After Deleted Array : 
[ 1  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [162]:
arr = np.arange(1,25).reshape(3,2,4)
print(f'Original Array :\n{arr}')
print(f'After Deleted Array : \n{np.delete(arr,[1,2])}') 

Original Array :
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]
After Deleted Array : 
[ 1  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [169]:
arr = np.arange(1,25).reshape(3,2,4)
print(f'Original Array :\n{arr}')
print(f'After Deleted Array : \n{np.delete(arr,[1,2,3])}') 

Original Array :
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]
After Deleted Array : 
[ 1  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


##### **NOTE:** Without Axis arguement it will delete single elements only (or multiple elements but in order to delete entire row or column we need to use axis)

##### **Axis=0** (row wise operation)

##### **1D Array:** In 1D Array If we specify single index then it will delete that element only.

In [170]:
arr = np.arange(1,10)
print(f'Original Array :{arr}')
print(f'After Deleted Array : {np.delete(arr,[1],axis=0)}')  

Original Array :[1 2 3 4 5 6 7 8 9]
After Deleted Array : [1 3 4 5 6 7 8 9]


In [171]:
arr = np.arange(1,10)
print(f'Original Array :{arr}')
print(f'After Deleted Array : {np.delete(arr,[1,2],axis=0)}')  

Original Array :[1 2 3 4 5 6 7 8 9]
After Deleted Array : [1 4 5 6 7 8 9]


##### **2D Array:** In 2D Array If we specify single index then it will delete entire row.
##### Example I have 4 rows in 2D array and I mentioned index as 1 then 1th index entire row is deleted

In [148]:
# 2D Array 
arr = np.arange(24).reshape(4,6)
print(f'Original Array :\n{arr}')
print(f'After Deleted Array : \n{np.delete(arr,[1],axis=0)}') 

Original Array :
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
After Deleted Array : 
[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [151]:
# 2D Array 
arr = np.arange(24).reshape(4,6)
print(f'Original Array :\n{arr}')
print(f'After Deleted Array : \n{np.delete(arr,[0,1],axis=0)}')

Original Array :
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
After Deleted Array : 
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [175]:
# 2D Array 
arr = np.arange(24).reshape(4,6)
print(f'Original Array :\n{arr}')
print(f'After Deleted Array : \n{np.delete(arr,[0,2,3],axis=0)}')

Original Array :
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
After Deleted Array : 
[[ 6  7  8  9 10 11]]


##### Note : In 2D Entire row is deleted wtih axos=0, It will not delete specific elements like 1D

##### **3D Array:** In 3D Array If we specify single index then it will delete entire row.
##### Example I have 2 rows in 3D array and I mentioned index as 1 then 1th index entire row is deleted

In [149]:
arr = np.arange(24).reshape(2,4,3)
print(f'Original Array :\n{arr}')
print(f'After Deleted Array : \n{np.delete(arr,[1],axis=0)}') 

Original Array :
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]
After Deleted Array : 
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]]


In [176]:
arr = np.arange(24).reshape(2,4,3)
print(f'Original Array :\n{arr}')
print(f'After Deleted Array : \n{np.delete(arr,[0,1],axis=0)}') 

Original Array :
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]
After Deleted Array : 
[]


##### Note : In 3D Entire row is deleted wtih axos=0, It will not delete specific elements like 1D

##### **Axis=1** (column wise operation)

##### **Note:** Axis=1 Works with 2D or more than that nthD array

In [179]:
arr = np.arange(1,10)
print(f'Original Array :{arr}')
print(f'After Deleted Array : {np.delete(arr,[1],axis=0)}') 

Original Array :[1 2 3 4 5 6 7 8 9]
After Deleted Array : [1 3 4 5 6 7 8 9]


In [178]:
arr = np.arange(1,10)
print(f'Original Array :{arr}')
print(f'After Deleted Array : {np.delete(arr,[1],axis=1)}') 

Original Array :[1 2 3 4 5 6 7 8 9]


AxisError: axis 1 is out of bounds for array of dimension 1

##### **2D Array**

In [182]:
arr = np.arange(1,11).reshape(5,2)
print(f'Original Array :\n{arr}')
print(f'After Deleted Array : \n{np.delete(arr,[1],axis=1)}')

Original Array :
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
After Deleted Array : 
[[1]
 [3]
 [5]
 [7]
 [9]]


In [183]:
arr = np.arange(1,51).reshape(5,10)
print(f'Original Array :\n{arr}')
print(f'After Deleted Array : \n{np.delete(arr,[1],axis=1)}')

Original Array :
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]
After Deleted Array : 
[[ 1  3  4  5  6  7  8  9 10]
 [11 13 14 15 16 17 18 19 20]
 [21 23 24 25 26 27 28 29 30]
 [31 33 34 35 36 37 38 39 40]
 [41 43 44 45 46 47 48 49 50]]


In [184]:
arr = np.arange(1,51).reshape(5,10)
print(f'Original Array :\n{arr}')
print(f'After Deleted Array : \n{np.delete(arr,[1,3,5,7,9],axis=1)}')

Original Array :
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]
After Deleted Array : 
[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]
 [41 43 45 47 49]]


##### **3D Array:** : row of column will deleted from each row of column because column wise operation. Means We have 2 Rows 10 Columns & 5 Elements from each row of column(meanse 10 columns) each 1st index position column is deleted from each row

In [187]:
arr = np.arange(1,101).reshape(2,10,5)
print(f'Original Array :\n{arr}')
print(f'After Deleted Array : \n{np.delete(arr,[1],axis=1)}')

Original Array :
[[[  1   2   3   4   5]
  [  6   7   8   9  10]
  [ 11  12  13  14  15]
  [ 16  17  18  19  20]
  [ 21  22  23  24  25]
  [ 26  27  28  29  30]
  [ 31  32  33  34  35]
  [ 36  37  38  39  40]
  [ 41  42  43  44  45]
  [ 46  47  48  49  50]]

 [[ 51  52  53  54  55]
  [ 56  57  58  59  60]
  [ 61  62  63  64  65]
  [ 66  67  68  69  70]
  [ 71  72  73  74  75]
  [ 76  77  78  79  80]
  [ 81  82  83  84  85]
  [ 86  87  88  89  90]
  [ 91  92  93  94  95]
  [ 96  97  98  99 100]]]
After Deleted Array : 
[[[  1   2   3   4   5]
  [ 11  12  13  14  15]
  [ 16  17  18  19  20]
  [ 21  22  23  24  25]
  [ 26  27  28  29  30]
  [ 31  32  33  34  35]
  [ 36  37  38  39  40]
  [ 41  42  43  44  45]
  [ 46  47  48  49  50]]

 [[ 51  52  53  54  55]
  [ 61  62  63  64  65]
  [ 66  67  68  69  70]
  [ 71  72  73  74  75]
  [ 76  77  78  79  80]
  [ 81  82  83  84  85]
  [ 86  87  88  89  90]
  [ 91  92  93  94  95]
  [ 96  97  98  99 100]]]


In [188]:
arr = np.arange(1,101).reshape(2,10,5)
print(f'Original Array :\n{arr}')
print(f'After Deleted Array : \n{np.delete(arr,[1,3,5,7,9],axis=1)}')

Original Array :
[[[  1   2   3   4   5]
  [  6   7   8   9  10]
  [ 11  12  13  14  15]
  [ 16  17  18  19  20]
  [ 21  22  23  24  25]
  [ 26  27  28  29  30]
  [ 31  32  33  34  35]
  [ 36  37  38  39  40]
  [ 41  42  43  44  45]
  [ 46  47  48  49  50]]

 [[ 51  52  53  54  55]
  [ 56  57  58  59  60]
  [ 61  62  63  64  65]
  [ 66  67  68  69  70]
  [ 71  72  73  74  75]
  [ 76  77  78  79  80]
  [ 81  82  83  84  85]
  [ 86  87  88  89  90]
  [ 91  92  93  94  95]
  [ 96  97  98  99 100]]]
After Deleted Array : 
[[[ 1  2  3  4  5]
  [11 12 13 14 15]
  [21 22 23 24 25]
  [31 32 33 34 35]
  [41 42 43 44 45]]

 [[51 52 53 54 55]
  [61 62 63 64 65]
  [71 72 73 74 75]
  [81 82 83 84 85]
  [91 92 93 94 95]]]


##### **IMPORTANT POINT** : 
##### delete without axis = It will delete single or multiple elements at a time
##### delete with axis = It will delete single or multiple rows (with rows containe all elements) at a time

##### **============================================================** 
#### **1.9 Unique() :** 
##### **============================================================**
##### It returns all the unique elements present in a array variable.
##### **Syntax: np.unique(arr_var, return_index=False, return_inverse=False, return_counts=False, axis=None)**
##### **Parameter:**
##### **arr_var :** Input array from which unique values are extracted,It remoes Duplicated element and Returns sorted unique values
##### **return_index :** Returns the index of first occurrence of each unique element. Useful when you want original positions
##### **return_inverse :** Returns an array that can reconstruct original array using unique values. It Replace each element with its index in unique array
##### **return_counts :** Returns frequency of each unique value
##### **axis :** Used for multi-dimensional arrays. Default: axis=None → flatten array first
##### **Note**
##### return_index → original position
##### return_inverse → mapping to rebuild array
##### return_counts → frequency

##### **arra_var :** Input array from which it returns unique values are extracted.
##### For 1D/2D/3D Unique elements are return in single array

##### **1-Dimensional Array :**

In [2]:
import numpy as np
arr = np.array([1,2,3,4,2,3,5,6,7,2,9])
unique = np.unique(arr)
unique

array([1, 2, 3, 4, 5, 6, 7, 9])

##### **2-Dimensional Array :**

In [5]:
import numpy as np
arr = np.array([[1,2,3,4],[3,4,5,6]])
unique = np.unique(arr)
unique

array([1, 2, 3, 4, 5, 6])

##### **3-Dimensional Array :**

In [6]:
import numpy as np
arr = np.array([[[1,2,3,4],[3,4,5,6]],[[12,9,3,7],[1,0,9,8]]])
unique = np.unique(arr)
unique

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 12])

##### **return_index :** Returns the index of first occurrence of each unique element. Useful when you want original positions
##### Duplicate array elements should be included in both array and indexing
##### If array_index=True : Then returns array unique elements with array index of unique elements only
##### If array_index=False : Then returns array unique elements only.(By default it is False only)

In [7]:
import numpy as np
arr = np.array([1,2,3,4,2,3,5,6,7,2,9])
unique = np.unique(arr,return_index=True)
unique

(array([1, 2, 3, 4, 5, 6, 7, 9]), array([ 0,  1,  2,  3,  6,  7,  8, 10]))

In [8]:
import numpy as np
arr = np.array([1,2,3,4,2,3,5,6,7,2,9])
unique = np.unique(arr,return_index=False)
unique

array([1, 2, 3, 4, 5, 6, 7, 9])

##### **return_inverse :** Returns an array that can reconstruct original array using unique values. It Replace each element with its index in unique array.
##### First it returns the Unique array elements , after that Based on Unique Elements index , it returns unique element index to each element present in an original array
##### Ex : Original Array : [1,2,4,2,3,1]
##### return_inverse : first it will return unique elements in asscending order - [1,2,3,4] and unique elements index is - [0,1,2,3] Based in that unique elements it will return indexes to the original array - [0,1,3,1,2,0]
##### If return_inverse=True : Then returns array unique elements with array index of unique elements, Based on unique element indexs it will return an original array indexs
##### If return_inverse=False : Then returns array unique elements only in an ascending order.(By default it is False only)

In [12]:
import numpy as np
arr = np.array([1,2,3,4,2,3,5,6,7,2,9])
unique = np.unique(arr,return_inverse=True)
unique

(array([1, 2, 3, 4, 5, 6, 7, 9]), array([0, 1, 2, 3, 1, 2, 4, 5, 6, 1, 7]))

In [10]:
import numpy as np
arr = np.array([1,2,3,4,2,3,5,6,7,2,9])
unique = np.unique(arr,return_inverse=False)
unique

array([1, 2, 3, 4, 5, 6, 7, 9])

##### **return_counts :** Returns frequency of each unique value(Reuturns the counts of each array elements with their respective positions only after returning unique elements)
##### If return_counts=True : Then returns unique array elements with count of occurance of each array elements
##### If return_inverse=False : Then returns array unique elements only in an ascending order.(By default it is False only)¶

In [13]:
import numpy as np
arr = np.array([1,2,3,4,2,3,5,6,7,2,9])
unique = np.unique(arr,return_counts=True)
unique

(array([1, 2, 3, 4, 5, 6, 7, 9]), array([1, 3, 2, 1, 1, 1, 1, 1]))

In [14]:
import numpy as np
arr = np.array([1,2,3,4,2,3,5,6,7,2,9])
unique = np.unique(arr,return_counts=False)
unique 

array([1, 2, 3, 4, 5, 6, 7, 9])

##### **axis :** Used for multi-dimensional arrays. Default: axis=None → flatten array first
##### If axis=0 : Returns row wise unique elements
##### If axis=1 : Returns column wise unique elements. But for 1D Array with axis 1 is not supported because thier is only one row no column in 1D array
##### To perform axis operations array dimension must be greater than 1D array or it must and should be 2D or 3D array

In [16]:
import numpy as np
arr = np.array([1,2,3,4,2,3,5,6,7,2,9])
unique = np.unique(arr,axis=0)
unique 

array([1, 2, 3, 4, 5, 6, 7, 9])

##### axis=None : Returns unique rows

In [50]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[1,2,3]])
unique = np.unique(arr,axis=0)
unique 

array([[1, 2, 3],
       [4, 5, 6]])

##### axis=0 : Duplicate Rows Will be eliminated from the 2D array or 3D array, Only it returns unique rows of element

In [33]:
import numpy as np
arr = np.array([[1,2,3],[1,2,3],[4,2,5],[4,6,5]])
unique = np.unique(arr,axis=0)
print(f'Original Array :\n{arr}')
print(f'Axis Array :\n{unique}')

Original Array :
[[1 2 3]
 [1 2 3]
 [4 2 5]
 [4 6 5]]
Axis Array :
[[1 2 3]
 [4 2 5]
 [4 6 5]]


##### axis = 1 : in 2D Array if starting element conatins duplicate in each row then it will be eliminated duplicate elements
##### Starting elements in rows should be duplicated then only it will eliminate other wise if one element also not contain duplicate it will return as it is

In [51]:
# 2D Array
import numpy as np
arr = np.array([[2,2,3],[3,3,4],[2,2,4],[4,4,5]])
unique = np.unique(arr,axis=1)
print(f'Original Array :\n{arr}')
print(f'Axis Array :\n{unique}')

Original Array :
[[2 2 3]
 [3 3 4]
 [2 2 4]
 [4 4 5]]
Axis Array :
[[2 3]
 [3 4]
 [2 4]
 [4 5]]


In [52]:
# 2D Array
import numpy as np
arr = np.array([[2,2,3],[3,1,4],[2,2,4],[4,4,5]])
unique = np.unique(arr,axis=1)
print(f'Original Array :\n{arr}')
print(f'Axis Array :\n{unique}')

Original Array :
[[2 2 3]
 [3 1 4]
 [2 2 4]
 [4 4 5]]
Axis Array :
[[2 2 3]
 [1 3 4]
 [2 2 4]
 [4 4 5]]


In [53]:
# 3D Array
import numpy as np
arr = np.array([[[1,2,3],[1,2,3],[4,2,5],[4,6,5]],[[1,2,3],[1,2,3],[4,2,5],[4,6,5]],[[1,2,3],[10,20,30],[40,20,50],[42,6,5]]])
unique = np.unique(arr,axis=0)
print(f'Original Array :\n{arr}')
print(f'Axis Array :\n{unique}')

Original Array :
[[[ 1  2  3]
  [ 1  2  3]
  [ 4  2  5]
  [ 4  6  5]]

 [[ 1  2  3]
  [ 1  2  3]
  [ 4  2  5]
  [ 4  6  5]]

 [[ 1  2  3]
  [10 20 30]
  [40 20 50]
  [42  6  5]]]
Axis Array :
[[[ 1  2  3]
  [ 1  2  3]
  [ 4  2  5]
  [ 4  6  5]]

 [[ 1  2  3]
  [10 20 30]
  [40 20 50]
  [42  6  5]]]


In [54]:
# 3D Array
import numpy as np
arr = np.array([[[1,1,3],[1,2,2],[4,2,4],[4,5,5]],[[1,2,3],[10,20,30],[40,20,50],[42,6,5]]])
unique = np.unique(arr,axis=1)
print(f'Original Array :\n{arr}')
print(f'Axis Array :\n{unique}')

Original Array :
[[[ 1  1  3]
  [ 1  2  2]
  [ 4  2  4]
  [ 4  5  5]]

 [[ 1  2  3]
  [10 20 30]
  [40 20 50]
  [42  6  5]]]
Axis Array :
[[[ 1  1  3]
  [ 1  2  2]
  [ 4  2  4]
  [ 4  5  5]]

 [[ 1  2  3]
  [10 20 30]
  [40 20 50]
  [42  6  5]]]


##### **============================================================** 
#### **1.10 Concatenate() :** 
##### **============================================================**
##### It combines multiple arrays into a single array along a specified axis
##### **Syntax : np.concatenate((array1, array2, ...), axis=0, out=None, dtype=None)**
##### Here axis , out and dtype is optional, and axis=0(as default) out(out=None Default)) and dtype=None(default)
##### **Parameters:**
##### **arrays:** A sequence of input arrays to be concatenated. These arrays must have the same shape or same dimentsion with size can differ.
##### **axis:** The axis along which the arrays will be joined. Default is 0 (the first axis).
##### **out:** If provided the result will be placed in this array.
##### **dtype:** It overrides the data type of the output array.
##### Column Concatenation done with axis = 1

##### **arrays:** A sequence of input arrays to be concatenated. These arrays must have the same shape or same dimentsion with differ in array size.

##### array can be any collection of array elements like list & tuple ( [],() )

##### **1-Dimensional Array :**

In [14]:
import numpy as np
arr1=np.arange(1,12)
arr2=np.arange(12,20)
np.concatenate((arr1,arr2))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

##### **2-Dimensional Array:**

In [5]:
import numpy as np
arr1=np.arange(1,13).reshape(3,4)
arr2=np.arange(12,20).reshape(2,4)
np.concatenate((arr1,arr2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

##### Note : We can't concatenate 1D array with 2D and vice-versa

In [6]:
import numpy as np
arr1=np.arange(1,13).reshape(3,4)
arr2=np.arange(12,20)
np.concatenate((arr1,arr2))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

##### **3-Dimensional Array:**

##### For 3D array Axis(dimensions) Must be same.

In [10]:
import numpy as np
arr1=np.arange(1,13).reshape(2,2,3)
arr2=np.arange(12,24).reshape(2,2,3)
np.concatenate((arr1,arr2))

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]])

##### If we change the dimension it will not work in 3D

In [11]:
import numpy as np
arr1=np.arange(1,13).reshape(2,2,3)
arr2=np.arange(12,24).reshape(2,3,2)
np.concatenate((arr1,arr2))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

##### **axis:** The axis along which the arrays will be joined. Default is 0 (the first axis).

##### **1-Dimensional Array:**

##### We can't do with axis=1 for 1D array (axis works with 2D or 3D array)
##### In axis dimension must be same with shape also (Dimension matters in 2D & 3D array, in 1D array the shape doesn't matter)
##### axis=0 (row by row operation will done)
##### axis=1 (column by column wise operation will done)

In [25]:
import numpy as np
arr1=np.arange(1,13)
arr2=np.arange(12,25)
np.concatenate((arr1,arr2),axis=0)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [21]:
import numpy as np
arr1=np.arange(1,12)
arr2=np.arange(12,25)
np.concatenate((arr1,arr2),axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

##### **2-Dimensional Array:**

In [32]:
import numpy as np
arr1=np.arange(1,13).reshape(3,4)
arr2=np.arange(13,25).reshape(3,4)
print(f'Original Array 1 : \n{arr1}\nOriginal Array 2 : \n{arr2}')
print()
np.concatenate((arr1,arr2),axis=0)

Original Array 1 : 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Original Array 2 : 
[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]



array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

##### axis=1 : Row wise - 1st row in Array 1 concatenate with 2nd row in Array 2 

In [33]:
import numpy as np
arr1=np.arange(1,13).reshape(3,4)
arr2=np.arange(13,25).reshape(3,4)
print(f'Original Array 1 : \n{arr1}\nOriginal Array 2 : \n{arr2}')
print()
np.concatenate((arr1,arr2),axis=1)

Original Array 1 : 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Original Array 2 : 
[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]



array([[ 1,  2,  3,  4, 13, 14, 15, 16],
       [ 5,  6,  7,  8, 17, 18, 19, 20],
       [ 9, 10, 11, 12, 21, 22, 23, 24]])

##### **3-Dimensional Array:**

In [37]:
import numpy as np
arr1=np.arange(1,13).reshape(2,2,3)
arr2=np.arange(13,25).reshape(2,2,3)
print(f'Original Array 1 : \n{arr1}\nOriginal Array 2 : \n{arr2}')
print()
np.concatenate((arr1,arr2),axis=0)

Original Array 1 : 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Original Array 2 : 
[[[13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]]]



array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24]]])

##### Row wise - 1st row 1st column in Array 1 concatenate with 1st row with 1st column in Array 2 

In [38]:
import numpy as np
arr1=np.arange(1,13).reshape(2,2,3)
arr2=np.arange(13,25).reshape(2,2,3)
print(f'Original Array 1 : \n{arr1}\nOriginal Array 2 : \n{arr2}')
print()
np.concatenate((arr1,arr2),axis=1)

Original Array 1 : 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Original Array 2 : 
[[[13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]]]



array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [13, 14, 15],
        [16, 17, 18]],

       [[ 7,  8,  9],
        [10, 11, 12],
        [19, 20, 21],
        [22, 23, 24]]])

##### **out:** If provided the result by replacing existing array elemenets to pre allocated array memory

In [51]:
import numpy as np
arr1=np.arange(1,13)
arr2=np.arange(13,25)
print(f'Original Array 1 : \n{arr1}\nOriginal Array 2 : \n{arr2}')
print()
np.concatenate((arr1,arr2),out=None)

Original Array 1 : 
[ 1  2  3  4  5  6  7  8  9 10 11 12]
Original Array 2 : 
[13 14 15 16 17 18 19 20 21 22 23 24]



array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

##### Total number of array element should replace with pre allocated array

In [59]:
# 1D Array
import numpy as np
arr1=np.arange(1,13)
arr2=np.arange(13,25)
arr3=np.empty(24,dtype=int)   # Pre-allocated array
print(f'Original Array 1 : \n{arr1}\nOriginal Array 2 : \n{arr2}')
print()
np.concatenate((arr1,arr2),out=arr3)

Original Array 1 : 
[ 1  2  3  4  5  6  7  8  9 10 11 12]
Original Array 2 : 
[13 14 15 16 17 18 19 20 21 22 23 24]



array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [64]:
# 2D Array
import numpy as np
arr1=np.arange(1,13).reshape(3,4)
arr2=np.arange(13,25).reshape(3,4)
arr3=np.empty((6,4),dtype=int)   # Pre-allocated array
print(f'Original Array 1 : \n{arr1}\nOriginal Array 2 : \n{arr2}')
print()
np.concatenate((arr1,arr2),out=arr3)

Original Array 1 : 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Original Array 2 : 
[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]



array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [65]:
# 3D Array
import numpy as np
arr1=np.arange(1,13).reshape(2,2,3)
arr2=np.arange(13,25).reshape(2,2,3)
arr3=np.empty((4,2,3),dtype=int)   # Pre-allocated array
print(f'Original Array 1 : \n{arr1}\nOriginal Array 2 : \n{arr2}')
print()
np.concatenate((arr1,arr2),out=arr3)

Original Array 1 : 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Original Array 2 : 
[[[13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]]]



array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24]]])

##### **dtype:** It overrides the data type of the output array

In [66]:
import numpy as np
arr1=np.arange(1,13)
arr2=np.arange(13,25)
print(f'Original Array 1 : \n{arr1}\nOriginal Array 2 : \n{arr2}')
print()
np.concatenate((arr1,arr2),dtype=float)

Original Array 1 : 
[ 1  2  3  4  5  6  7  8  9 10 11 12]
Original Array 2 : 
[13 14 15 16 17 18 19 20 21 22 23 24]



array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.])

##### **============================================================** 
#### **1.11 Stack() :** 
##### **============================================================**
##### It is used to combine multiple arrays. It performs internally stacking operation (1 on 1 operation)
##### **Syntax : np.stack(arrays, axis=0, out=None)**
##### **Parameters:**
##### **arrays:** Sequence of input arrays with the same shape.
##### **axis:** Position of the new axis where arrays will be stacked (default: 0).
##### **out(Optional):** output array to store the result.

#### **==== 1.11.1 stack(): ====**

##### **1-Dimensional Array :** Normal Concatenation will done (row by row as default) - Return 1D array into 2D Array

In [67]:
# 1-Dimensional Array:
import numpy as np
arr1=np.arange(1,13)
arr2=np.arange(13,25)
print(f'Original Array 1 : \n{arr1}\nOriginal Array 2 : \n{arr2}')
print()
np.stack((arr1,arr2))

Original Array 1 : 
[ 1  2  3  4  5  6  7  8  9 10 11 12]
Original Array 2 : 
[13 14 15 16 17 18 19 20 21 22 23 24]



array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

##### **2-Dimensional Array :** Normal Concatenation will done (row by row as default) - Return 2D array into 3D Array
##### 1st array concatenate with 2nd row 

In [69]:
# 2-Dimensional Array:
import numpy as np
arr1=np.arange(1,13).reshape(3,4)
arr2=np.arange(13,25).reshape(3,4)
print(f'Original Array 1 : \n{arr1}\nOriginal Array 2 : \n{arr2}')
print()
np.stack((arr1,arr2))

Original Array 1 : 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Original Array 2 : 
[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]



array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

##### **3-Dimensional Array :** Normal Concatenation will done (row by row as default) - Return 3D array into 4D Array
##### 1st array concatenate with 2nd row 

In [71]:
# 3-Dimensional Array:
import numpy as np
arr1=np.arange(1,13).reshape(2,2,3)
arr2=np.arange(13,25).reshape(2,2,3)
print(f'Original Array 1 : \n{arr1}\nOriginal Array 2 : \n{arr2}')
print()
np.stack((arr1,arr2))

Original Array 1 : 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Original Array 2 : 
[[[13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]]]



array([[[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]],


       [[[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]]])

##### **axis=0:** side by side like queue

##### **1-Dimensional Array:**

In [82]:
# 1-Dimensional Array:
import numpy as np
arr1=np.arange(1,13)
arr2=np.arange(13,25)
print(f'Original Array 1 : \n{arr1}\nOriginal Array 2 : \n{arr2}')
print()
np.stack((arr1,arr2),axis=0)

Original Array 1 : 
[ 1  2  3  4  5  6  7  8  9 10 11 12]
Original Array 2 : 
[13 14 15 16 17 18 19 20 21 22 23 24]



array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

##### **2-Dimensional Array:**

In [83]:
# 2-Dimensional Array:
import numpy as np
arr1=np.arange(1,13).reshape(3,4)
arr2=np.arange(13,25).reshape(3,4)
print(f'Original Array 1 : \n{arr1}\nOriginal Array 2 : \n{arr2}')
print()
np.stack((arr1,arr2),axis=0)

Original Array 1 : 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Original Array 2 : 
[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]



array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

##### **3-Dimensional Array:**

In [84]:
# 3-Dimensional Array:
import numpy as np
arr1=np.arange(1,13).reshape(2,2,3)
arr2=np.arange(13,25).reshape(2,2,3)
print(f'Original Array 1 : \n{arr1}\nOriginal Array 2 : \n{arr2}')
print()
np.stack((arr1,arr2),axis=0)

Original Array 1 : 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Original Array 2 : 
[[[13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]]]



array([[[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]],


       [[[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]]])

##### **axis=1** : stack by stack means one above another element

##### **1-Dimensional Array:** one element above/below another element concatenation - 1st element of column in 1st row concatenate with 1st element of comlumn in 2nd row

In [85]:
# 1-Dimensional Array:
import numpy as np
arr1=np.arange(1,13)
arr2=np.arange(13,25)
print(f'Original Array 1 : \n{arr1}\nOriginal Array 2 : \n{arr2}')
print()
np.stack((arr1,arr2),axis=1)

Original Array 1 : 
[ 1  2  3  4  5  6  7  8  9 10 11 12]
Original Array 2 : 
[13 14 15 16 17 18 19 20 21 22 23 24]



array([[ 1, 13],
       [ 2, 14],
       [ 3, 15],
       [ 4, 16],
       [ 5, 17],
       [ 6, 18],
       [ 7, 19],
       [ 8, 20],
       [ 9, 21],
       [10, 22],
       [11, 23],
       [12, 24]])

##### **2-Dimensional Array:** one element above/below another element concatenation - 1st element of column in 1st row concatenate with 1st element of comlumn in 2nd row

In [86]:
# 2-Dimensional Array:
import numpy as np
arr1=np.arange(1,13).reshape(3,4)
arr2=np.arange(13,25).reshape(3,4)
print(f'Original Array 1 : \n{arr1}\nOriginal Array 2 : \n{arr2}')
print()
np.stack((arr1,arr2),axis=1)

Original Array 1 : 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Original Array 2 : 
[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]



array([[[ 1,  2,  3,  4],
        [13, 14, 15, 16]],

       [[ 5,  6,  7,  8],
        [17, 18, 19, 20]],

       [[ 9, 10, 11, 12],
        [21, 22, 23, 24]]])

##### **3-Dimensional Array:** one element above/below another element concatenation - 1st element of column in 1st row concatenate with 1st element of comlumn in 2nd row

In [87]:
# 3-Dimensional Array:
import numpy as np
arr1=np.arange(1,13).reshape(2,2,3)
arr2=np.arange(13,25).reshape(2,2,3)
print(f'Original Array 1 : \n{arr1}\nOriginal Array 2 : \n{arr2}')
print()
np.stack((arr1,arr2),axis=1)

Original Array 1 : 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Original Array 2 : 
[[[13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]]]



array([[[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[13, 14, 15],
         [16, 17, 18]]],


       [[[ 7,  8,  9],
         [10, 11, 12]],

        [[19, 20, 21],
         [22, 23, 24]]]])

##### **axis=-1:** same as axis 1 because it refers to the last dimension

In [9]:
# 1-Dimensional Array:
import numpy as np
arr1=np.arange(1,13)
arr2=np.arange(13,25)
print(f'Original Array 1 : \n{arr1}\nOriginal Array 2 : \n{arr2}')
print()
np.stack((arr1,arr2),axis=-1)

Original Array 1 : 
[ 1  2  3  4  5  6  7  8  9 10 11 12]
Original Array 2 : 
[13 14 15 16 17 18 19 20 21 22 23 24]



array([[ 1, 13],
       [ 2, 14],
       [ 3, 15],
       [ 4, 16],
       [ 5, 17],
       [ 6, 18],
       [ 7, 19],
       [ 8, 20],
       [ 9, 21],
       [10, 22],
       [11, 23],
       [12, 24]])

In [10]:
# 2-Dimensional Array:
import numpy as np
arr1=np.arange(1,13).reshape(3,4)
arr2=np.arange(13,25).reshape(3,4)
print(f'Original Array 1 : \n{arr1}\nOriginal Array 2 : \n{arr2}')
print()
np.stack((arr1,arr2),axis=-1)

Original Array 1 : 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Original Array 2 : 
[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]



array([[[ 1, 13],
        [ 2, 14],
        [ 3, 15],
        [ 4, 16]],

       [[ 5, 17],
        [ 6, 18],
        [ 7, 19],
        [ 8, 20]],

       [[ 9, 21],
        [10, 22],
        [11, 23],
        [12, 24]]])

In [11]:
# 3-Dimensional Array:
import numpy as np
arr1=np.arange(1,13).reshape(2,2,3)
arr2=np.arange(13,25).reshape(2,2,3)
print(f'Original Array 1 : \n{arr1}\nOriginal Array 2 : \n{arr2}')
print()
np.stack((arr1,arr2),axis=-1)

Original Array 1 : 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Original Array 2 : 
[[[13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]]]



array([[[[ 1, 13],
         [ 2, 14],
         [ 3, 15]],

        [[ 4, 16],
         [ 5, 17],
         [ 6, 18]]],


       [[[ 7, 19],
         [ 8, 20],
         [ 9, 21]],

        [[10, 22],
         [11, 23],
         [12, 24]]]])

##### **out=variable_name(pre allocated memory)**

##### **1-Dimensional Array:**

In [3]:
# 1D Array
import numpy as np
arr1=np.arange(1,13)
arr2=np.arange(13,25)
arr3=np.empty((2,12),dtype=int)   # Pre-allocated array
print(f'Original Array 1 : \n{arr1}\nOriginal Array 2 : \n{arr2}')
print()
np.stack((arr1,arr2),out=arr3)

Original Array 1 : 
[ 1  2  3  4  5  6  7  8  9 10 11 12]
Original Array 2 : 
[13 14 15 16 17 18 19 20 21 22 23 24]



array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

##### **2-Dimensional Array:**

In [7]:
# 2D Array
import numpy as np
arr1=np.arange(1,13).reshape(3,4)
arr2=np.arange(13,25).reshape(3,4)
arr3=np.empty((2,3,4),dtype=int)   # Pre-allocated array
print(f'Original Array 1 : \n{arr1}\nOriginal Array 2 : \n{arr2}')
print()
np.stack((arr1,arr2),out=arr3)

Original Array 1 : 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Original Array 2 : 
[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]



array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

##### **3-Dimensional Array:**

In [10]:
# 3D Array
import numpy as np
arr1=np.arange(1,13).reshape(2,2,3)
arr2=np.arange(13,25).reshape(2,2,3)
arr3=np.empty((2,2,2,3),dtype=int)   # Pre-allocated array
print(f'Original Array 1 : \n{arr1}\nOriginal Array 2 : \n{arr2}')
print()
np.stack((arr1,arr2),out=arr3)

Original Array 1 : 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Original Array 2 : 
[[[13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]]]



array([[[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]],


       [[[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]]])

#### **====1.11.2 hstack(): ====**
##### **Syntax : np.hstack((arr1,arr2...))

##### **1-Dimensional Array :** Horizonatal ( --- ) Concatenation will done (row by row as default) - Return 1D array into 1D Array
##### 1st array concatenate with 2nd row horizontally 

In [75]:
# 1-Dimensional Array:
import numpy as np
arr1=np.arange(1,13)
arr2=np.arange(13,25)
print(f'Original Array 1 : \n{arr1}\nOriginal Array 2 : \n{arr2}')
print()
np.hstack((arr1,arr2))

Original Array 1 : 
[ 1  2  3  4  5  6  7  8  9 10 11 12]
Original Array 2 : 
[13 14 15 16 17 18 19 20 21 22 23 24]



array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

##### **2-Dimensional Array :** Horizonatal ( --- ) Concatenation will done (row by row as default) - Return 2D array into 2D Array
##### 1st row of array1 concatenate with 1st row of 2nd array then 2nd row in both arrays followed by next

In [77]:
# 2-Dimensional Array:
import numpy as np
arr1=np.arange(1,13).reshape(3,4)
arr2=np.arange(13,25).reshape(3,4)
print(f'Original Array 1 : \n{arr1}\nOriginal Array 2 : \n{arr2}')
print()
np.hstack((arr1,arr2))

Original Array 1 : 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Original Array 2 : 
[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]



array([[ 1,  2,  3,  4, 13, 14, 15, 16],
       [ 5,  6,  7,  8, 17, 18, 19, 20],
       [ 9, 10, 11, 12, 21, 22, 23, 24]])

##### **3-Dimensional Array :** Horizonatal ( --- ) Concatenation will done (row by row as default) - Return 3D array into 3D Array
##### 1st row of array1 concatenate with 1st row of 2nd array then 2nd row in both arrays followed by next

In [80]:
# 3-Dimensional Array:
import numpy as np
arr1=np.arange(1,13).reshape(2,2,3)
arr2=np.arange(13,25).reshape(2,2,3)
print(f'Original Array 1 : \n{arr1}\nOriginal Array 2 : \n{arr2}')
print()
np.hstack((arr1,arr2))

Original Array 1 : 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Original Array 2 : 
[[[13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]]]



array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [13, 14, 15],
        [16, 17, 18]],

       [[ 7,  8,  9],
        [10, 11, 12],
        [19, 20, 21],
        [22, 23, 24]]])

#### **====1.11.3 vstack():====**
##### **Syntax : np.vstack((arr1,arr2....))**

##### **1-Dimensional Array :** Vertical ( | ) Concatenation will done (column by column as default) - Return 1D array into 2D Array
##### 1st row of array1 concatenate with 1st row of 2nd array then 2nd row in both arrays followed by next

In [76]:
# 1-Dimensional Array:
import numpy as np
arr1=np.arange(1,13)
arr2=np.arange(13,25)
print(f'Original Array 1 : \n{arr1}\nOriginal Array 2 : \n{arr2}')
print()
np.vstack((arr1,arr2))

Original Array 1 : 
[ 1  2  3  4  5  6  7  8  9 10 11 12]
Original Array 2 : 
[13 14 15 16 17 18 19 20 21 22 23 24]



array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

##### **2-Dimensional Array :** Vertical ( | ) Concatenation will done (column by column as default) - Return 2D array into 2D Array
##### 1st row of array1 concatenate with 1st row of 2nd array then 2nd row in both arrays followed by next

In [81]:
# 2-Dimensional Array:
import numpy as np
arr1=np.arange(1,13).reshape(3,4)
arr2=np.arange(13,25).reshape(3,4)
print(f'Original Array 1 : \n{arr1}\nOriginal Array 2 : \n{arr2}')
print()
np.vstack((arr1,arr2))

Original Array 1 : 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Original Array 2 : 
[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]



array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

##### **3-Dimensional Array :** Vertical ( | ) Concatenation will done (column by column as default) - Return 1D array into 2D Array
##### 1st row of array1 concatenate with 1st row of 2nd array then 2nd row in both arrays followed by next

In [79]:
# 3-Dimensional Array:
import numpy as np
arr1=np.arange(1,13).reshape(2,2,3)
arr2=np.arange(13,25).reshape(2,2,3)
print(f'Original Array 1 : \n{arr1}\nOriginal Array 2 : \n{arr2}')
print()
np.vstack((arr1,arr2))

Original Array 1 : 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Original Array 2 : 
[[[13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]]]



array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24]]])

##### **============================================================** 
#### **1.12 Split() :** 
##### **============================================================**
##### It is used to splits the complete array based on given n.
##### **Syntax : np.split(arr, indices_or_sections, axis=0)**
##### **Parameters:**
##### **arrays:** Sequence of input arrays with the same shape.
##### **indices_or_sections :** number of sections to be split the array (n- number of arrays to be split).
##### **axis:** Position of the new axis where arrays will be splited (default: 0).

#### **===== 1.12.1. Split() : =====** 
##### It is used to splits the complete array based on given n(indeices or sections). It can split array elements if they are equal only.
##### **Note** Split is used to split the array based on n value , If you given n value which is not possible to split it throws an error. Example : total 12 array elements we have, if i want to split the array into eqaul sizes of array means i can take n=6,n=4 or n=3 or n=2 or n=1, but if we give n=5 it will split unequally and raises error

##### **1-Dimensional Array:**

In [12]:
import numpy as np
arr=np.arange(1,13)
np.split(arr,4)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]

In [18]:
import numpy as np
arr=np.arange(1,13)
np.split(arr,1)

[array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])]

In [17]:
import numpy as np
arr=np.arange(1,13)
np.split(arr,2)

[array([1, 2, 3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12])]

In [19]:
import numpy as np
arr=np.arange(1,13)
np.split(arr,3)

[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]

In [20]:
import numpy as np
arr=np.arange(1,13)
np.split(arr,6)

[array([1, 2]),
 array([3, 4]),
 array([5, 6]),
 array([7, 8]),
 array([ 9, 10]),
 array([11, 12])]

In [21]:
import numpy as np
arr=np.arange(1,13)
np.split(arr,5)

ValueError: array split does not result in an equal division

##### **2-Dimensional Array:** If we are splitting 2D Array we need to take care of n value , Wherre n value should be split equally by number of rows, Here I have 4 rows I can split rows into 2-2 rows or 4 rows directly 

In [25]:
import numpy as np
arr=np.arange(1,13).reshape(4,3)
print(arr)
np.split(arr,2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]])]

In [26]:
import numpy as np
arr=np.arange(1,13).reshape(4,3)
print(arr)
np.split(arr,4)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


[array([[1, 2, 3]]),
 array([[4, 5, 6]]),
 array([[7, 8, 9]]),
 array([[10, 11, 12]])]

In [14]:
import numpy as np
arr=np.arange(1,13).reshape(4,3)
np.split(arr,3)

ValueError: array split does not result in an equal division

##### **3-Dimensional Array:** Spliting depend on number of rows in 2D or 3D , Based on that we need to split

In [29]:
import numpy as np
arr=np.arange(1,13).reshape(2,2,3)
print(arr)
np.split(arr,2)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


[array([[[1, 2, 3],
         [4, 5, 6]]]),
 array([[[ 7,  8,  9],
         [10, 11, 12]]])]

In [22]:
import numpy as np
arr=np.arange(1,13).reshape(2,2,3)
np.split(arr,4)

ValueError: array split does not result in an equal division

#### **===== 1.12.2. Array_Split() : =====** 
##### It is used to splits the complete array based on given n(indeices or sections) It can split even array elements are unequal
##### **Note** Split is used to split the array based on n value , If you given equal number to split - it will split equal number. If we provide n value which is not possible to divide equally then also it will split it equally and then remaining elements are filled by top rows which are already splitted
##### Example : total 12 array elements we have, if i want to split the array into eqaul sizes of array means i can take n=6,n=4 or n=3 or n=2 or n=1, but if we give n=5 it will split unequally but it will not raise an error It will split and remaining elements will filled from top to bottom

##### **1-Dimensional Array:**

In [34]:
# Equal split
import numpy as np
arr=np.arange(1,13)
print(arr)
np.array_split(arr,4)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]

In [32]:
# UnEqual split
import numpy as np
arr=np.arange(1,13)
print(arr)
np.array_split(arr,5)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


[array([1, 2, 3]),
 array([4, 5, 6]),
 array([7, 8]),
 array([ 9, 10]),
 array([11, 12])]

##### **2-Dimensional Array:**

In [39]:
# Equal split
import numpy as np
arr=np.arange(1,13).reshape(3,4)
print(arr)
np.array_split(arr,3)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]

In [37]:
# UnEqual split
import numpy as np
arr=np.arange(1,13).reshape(3,4)
print(arr)
np.array_split(arr,4)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


[array([[1, 2, 3, 4]]),
 array([[5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12]]),
 array([], shape=(0, 4), dtype=int64)]

In [38]:
# UnEqual split
import numpy as np
arr=np.arange(1,13).reshape(3,4)
print(arr)
np.array_split(arr,5)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


[array([[1, 2, 3, 4]]),
 array([[5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12]]),
 array([], shape=(0, 4), dtype=int64),
 array([], shape=(0, 4), dtype=int64)]

##### **3-Dimensional Array:**

In [40]:
# Equal split
import numpy as np
arr=np.arange(1,13).reshape(2,2,3)
print(arr)
np.array_split(arr,2)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


[array([[[1, 2, 3],
         [4, 5, 6]]]),
 array([[[ 7,  8,  9],
         [10, 11, 12]]])]

In [42]:
# UnEqual split
import numpy as np
arr=np.arange(1,13).reshape(2,2,3)
print(arr)
np.array_split(arr,3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


[array([[[1, 2, 3],
         [4, 5, 6]]]),
 array([[[ 7,  8,  9],
         [10, 11, 12]]]),
 array([], shape=(0, 2, 3), dtype=int64)]

#### **===== 1.12.3. hsplit() : =====** 
##### It is used to splits the complete array based on given n(indeices or sections) It can't split if array elements are unequal. It is same as like np.split() method.
##### **Note** It will split an array based on horizonatal n values

##### **1-Dimensional Array:**

In [45]:
import numpy as np
arr=np.arange(1,13)
print(arr)
np.hsplit(arr,4)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]

##### **2-Dimensional Array:** Columns wise split

In [46]:
import numpy as np
arr=np.arange(1,13).reshape(3,4)
print(arr)
np.hsplit(arr,4)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


[array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]]),
 array([[ 4],
        [ 8],
        [12]])]

In [47]:
import numpy as np
arr=np.arange(1,13).reshape(3,4)
print(arr)
np.hsplit(arr,3)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


ValueError: array split does not result in an equal division

##### **3-Dimensional Array:**

In [49]:
import numpy as np
arr=np.arange(1,13).reshape(2,2,3)
print(arr)
np.hsplit(arr,2)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


[array([[[1, 2, 3]],
 
        [[7, 8, 9]]]),
 array([[[ 4,  5,  6]],
 
        [[10, 11, 12]]])]

#### **===== 1.12.4. vsplit() : =====** 
##### It is used to splits the complete array based on given n(indeices or sections) It can't split if array elements are unequal. It is same as like np.split() method.
##### **Note** It will split an array based on vartical n values. It works with only 2 or more Dimensional

##### **1-Dimensional Array:**

In [50]:
import numpy as np
arr=np.arange(1,13)
print(arr)
np.vsplit(arr,4)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


ValueError: vsplit only works on arrays of 2 or more dimensions

##### **2-Dimensional Array:**

In [52]:
import numpy as np
arr=np.arange(1,13).reshape(4,3)
print(arr)
np.vsplit(arr,2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]])]

In [53]:
import numpy as np
arr=np.arange(1,13).reshape(4,3)
print(arr)
np.vsplit(arr,3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


ValueError: array split does not result in an equal division

##### **3-Dimensional Array:**

In [54]:
import numpy as np
arr=np.arange(1,13).reshape(2,2,3)
print(arr)
np.vsplit(arr,2)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


[array([[[1, 2, 3],
         [4, 5, 6]]]),
 array([[[ 7,  8,  9],
         [10, 11, 12]]])]

In [55]:
import numpy as np
arr=np.arange(1,13).reshape(2,2,3)
print(arr)
np.vsplit(arr,3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


ValueError: array split does not result in an equal division