# **Numpy(Numerical Python) Library :**

## **Indexing & Slicing**

#### **1.1 Indexing:**
##### 1.1.1 Normal Indexing 
##### -> 1.1.1(a) 1-Dimensional Indexing
##### -> 1.1.1(b) 2-Dimensional Indexing
##### -> 1.1.1(c) 3-Dimensional Indexing
##### 1.1.2 Boolean Indexing
##### -> 1.1.2(a) 1-Dimensional Boolean Indexing
##### -> 1.1.2(b) 2-Dimensional Boolean Indexing
##### -> 1.1.2(c) 3-Dimensional Boolean Indexing
##### 1.1.3 Fancy Indexing
##### -> 1.1.3(a) 1-Dimensional Fancy Indexing
##### -> 1.1.3(b) 2-Dimensional Fancy Indexing
##### -> 1.1.3(c) 3-Dimensional Fancy Indexing
##### **1.2 Slicing**
##### -> 1.2.1 1-Dimensional Slicing
##### -> 1.2.2 2-Dimensional Slicing
##### -> 1.2.3 3-Dimensional Slicing
##### **1.3 All()**
##### -> 1.3.1 1-Dimensional All()
##### -> 1.3.2 2-Dimensional All()
##### -> 1.3.3 3-Dimensional All()
##### **1.4 Any()**
##### -> 1.4.1 1-Dimensional Any()
##### -> 1.4.2 2-Dimensional Any()
##### -> 1.4.3 3-Dimensional Any()
##### **1.5 Where()**
##### -> 1.5.1 1-Dimensional Where()
##### -> 1.5.2 2-Dimensional Where()
##### -> 1.5.3 3-Dimensional Where()

#### **1.1 Indexing :**

##### It is the process of giving an subaddress for all elements present in a collection.Indexing is used to fetch single element or update a single element in array

##### **1.1.1(a) : 1-Dimensional Indexing :**
##### **Syntax for accessing : arr_var[index]**
##### **Syntax for Update : arra_var[index]=new_value**

##### **Example 1:**

In [30]:
import numpy as np
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

##### **Positive Indexing :** starts from 0 to lenght(array)-1

##### Accessing Array Elements based on Index 

In [31]:
# I want to access element 11
print(arr[0])
print(arr[0].item())
print(int(arr[0]))

11
11
11


In [32]:
# I want to access element 15 & 19
print(arr[4])
print(arr[8])

15
19


##### Updating Array Elements based on Index 

In [33]:
# I want to update element 11 to 100 and 16 to 150
arr[0]=100
arr[5]=150
print(arr)

[100  12  13  14  15 150  17  18  19  20]


##### **Negative Indexing :** starts from -1 to 1-lenght(array)

##### Accessing Array Elements based on Index 

In [17]:
import numpy as np
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [34]:
# I want to access last element
print(arr[-1])
print(arr[-1].item())
print(int(arr[-1]))

20
20
20


##### Updating Array Elements based on Index 

In [35]:
arr[-3]=400
arr[-8]=900
print(arr)

[100  12 900  14  15 150  17 400  19  20]


##### **1.1.1(b) : 2-Dimensional Indexing :**
##### **Syntax for accessing : arr_var[index_row,index_column]**
##### **Syntax for Update : arra_var[index_row,index_column]=new_value**

##### **Example 1 :**

In [48]:
arr = np.arange(10,30).reshape(4,5)
arr

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

##### Accessing Array elements based on Index :

In [49]:
# I want to access element 22 and 17
print(arr[2,2])
print(arr[1,2])

22
17


In [100]:
# I want to access element 22 and 17
print(arr[2][2])
print(arr[1][2])

IndexError: invalid index to scalar variable.

In [102]:
# I want to access element 22 and 17
print(arr[[2],[2]])
print(arr[[1],[2]])

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [50]:
# I want to access element 18 & 29 
print(arr[1,-2])
print(arr[-1,-1])

18
29


##### Updating Array elements based on Index :

In [51]:
# I want to update element 22 and 17
arr[2,2]=100
arr[1,2]=200
print(arr)

[[ 10  11  12  13  14]
 [ 15  16 200  18  19]
 [ 20  21 100  23  24]
 [ 25  26  27  28  29]]


In [46]:
# I want to update element 18 to 800 and 29 to 290
arr[1,-2]=100
arr[-1,-1]=290
print(arr)

[[ 10  11  12  13  14]
 [ 15  16 200 100  19]
 [ 20  21 100  23  24]
 [ 25  26  27  28 290]]


##### **1.1.1(b) : 3-Dimensional Indexing :**
##### **Syntax for accessing : arr_var[index_row,index_column,index_element]**
##### **Syntax for Update : arra_var[index_row,index_column,index_element]=new_value**

##### **Example :**

In [54]:
arr = np.arange(1,31).reshape(5,2,3)
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24]],

       [[25, 26, 27],
        [28, 29, 30]]])

##### Accessing Array Elements based on Index

In [64]:
# I need to access element 17 & 12 & 29
print(arr[2,1,1])
print(arr[1,-1,-1])
print(arr[-1,-1,-2])

17
12
29


In [63]:
print("Simple Tracing :")
print(f'Enitre Array : \n{arr}\n')
print(f'First Fectch the Row : \n{arr[2]}')
print(f'First Fectch the Column : \n{arr[2,1]}')
print(f'First Fectch the Element : \n{arr[2,1,1]}')
print(f'\nFinal Output : {arr[2,1,1]}')

Simple Tracing :
Enitre Array : 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]]]

First Fectch the Row : 
[[13 14 15]
 [16 17 18]]
First Fectch the Column : 
[16 17 18]
First Fectch the Element : 
17

Final Output : 17


##### Updating the elements based on index

In [65]:
# I need to update element 14 to 140
arr[2,0,-2]=140
print(arr)

[[[  1   2   3]
  [  4   5   6]]

 [[  7   8   9]
  [ 10  11  12]]

 [[ 13 140  15]
  [ 16  17  18]]

 [[ 19  20  21]
  [ 22  23  24]]

 [[ 25  26  27]
  [ 28  29  30]]]


In [67]:
print("Simple Tracing :")
print(f'Enitre Array : \n{arr}\n')
print(f'First Fectch the Row : \n{arr[2]}')
print(f'First Fectch the Column : \n{arr[2,1]}')
print(f'First Fectch the Element : \n{arr[2,1,-2]}')
arr[2,1,-2]=140
print(f'\nFinal Output : {arr}')

Simple Tracing :
Enitre Array : 
[[[  1   2   3]
  [  4   5   6]]

 [[  7   8   9]
  [ 10  11  12]]

 [[ 13 140  15]
  [ 16  17  18]]

 [[ 19  20  21]
  [ 22  23  24]]

 [[ 25  26  27]
  [ 28  29  30]]]

First Fectch the Row : 
[[ 13 140  15]
 [ 16  17  18]]
First Fectch the Column : 
[16 17 18]
First Fectch the Element : 
17

Final Output : [[[  1   2   3]
  [  4   5   6]]

 [[  7   8   9]
  [ 10  11  12]]

 [[ 13 140  15]
  [ 16 140  18]]

 [[ 19  20  21]
  [ 22  23  24]]

 [[ 25  26  27]
  [ 28  29  30]]]


#### **1.1.2 Boolean Indexing :**

##### It is the process of fetching the elements based on given conditions
##### **Syntax : array_variable[condition]**
##### If condition True then only it **returns the array elements** 
##### It always returns an single 1D array elements or flatten array elements

##### **1.1.2(a) : 1-Dimensional Boolean Indexing**

In [75]:
# Single Conditions
import numpy as np
arr = np.arange(10,20,2)
print(f'Orignal Array : {arr}')
print(f'After Condition Array : {arr[arr>15]}')

Orignal Array : [10 12 14 16 18]
After Condition Array : [16 18]


In [85]:
# Multiple Conditions
import numpy as np
arr = np.arange(10,50,2)
print(f'Orignal Array : \n{arr}')
print(f'After Condition Array : {arr[(arr > 20) & (arr < 30)]}')
print(f'After Condition Array : {arr[(arr > 20) | (arr < 30)]}')
print(f'After Condition Array : {arr[~(arr > 20)]}')

Orignal Array : 
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]
After Condition Array : [22 24 26 28]
After Condition Array : [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]
After Condition Array : [10 12 14 16 18 20]


##### **1.1.2(b) : 2-Dimensional Boolean Indexing**

In [77]:
# Single Conditions
import numpy as np
arr = np.arange(10,20).reshape(2,5)
print(f'Orignal Array : {arr}')
print(f'After Condition Array : {arr[arr>15]}')

Orignal Array : [[10 11 12 13 14]
 [15 16 17 18 19]]
After Condition Array : [16 17 18 19]


In [83]:
# Multiple Conditions
import numpy as np
arr = np.arange(10,20).reshape(2,5)
print(f'Orignal Array : {arr}')
print(f'After Condition Array : {arr[(arr > 15) & (arr < 18)]}')
print(f'After Condition Array : {arr[(arr > 15) | (arr < 18)]}')
print(f'After Condition Array : {arr[~(arr > 15)]}')

Orignal Array : [[10 11 12 13 14]
 [15 16 17 18 19]]
After Condition Array : [16 17]
After Condition Array : [10 11 12 13 14 15 16 17 18 19]
After Condition Array : [10 11 12 13 14 15]


##### **1.1.2(c) : 3-Dimensional Boolean Indexing**

In [87]:
# Single Conditions
import numpy as np
arr = np.arange(10,30).reshape(5,2,2)
print(f'Orignal Array : {arr}')
print(f'After Condition Array : {arr[arr>15]}')

Orignal Array : [[[10 11]
  [12 13]]

 [[14 15]
  [16 17]]

 [[18 19]
  [20 21]]

 [[22 23]
  [24 25]]

 [[26 27]
  [28 29]]]
After Condition Array : [16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [127]:
# Multiple Conditions
import numpy as np
arr = np.arange(10,30).reshape(5,2,2)
print(f'Orignal Array : {arr}')
print(f'After Condition Array : {arr[(arr > 15) & (arr < 18)]}')
print(f'After Condition Array : {arr[(arr > 15) | (arr < 18)]}')
print(f'After Condition Array : {arr[~(arr > 15)]}')

Orignal Array : [[[10 11]
  [12 13]]

 [[14 15]
  [16 17]]

 [[18 19]
  [20 21]]

 [[22 23]
  [24 25]]

 [[26 27]
  [28 29]]]
After Condition Array : [16 17]
After Condition Array : [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
After Condition Array : [10 11 12 13 14 15]


#### **1.1.3 Fancy Indexing :**

##### It is the process of fetching the elements based on group of indexs
##### **Syntax : array_variable[[index1],[index2],[index3]....]**
##### It always returns an single 1D array elements or flatten array elements
##### We need to create two array 1 is for creating entire array and another one is for giving indexes to the created entire array (or we can directly give the indexes)
##### It depends how we are passing array indexs whether we are passing in 1D [] or 2D [[]] or 3D [[[]]]

#### **1.1.3(a) 1-Dimensional Fancy Indexing :**
##### If we are returning an array in 1D means we should use just [] square brackets
##### If we are retruning 2D means [[],[]] or [[index1,index2]] 
##### If we are returning 3D means [[[]]] or [[[],[]],[[],[]]]
##### If we are passing multiple arr_indexes Then it must be [[index1,index2]] form or [[[index1,index2]]]

In [158]:
# 1D array with 1D array index , that returns 1D Array
arr1 = np.arange(10,20)
print(f'Original Array : {arr1}')
arr2 = [-1,-2,-3,-4,-5] #indexes of arr1
arr = arr1[arr2]
print(f'1-D Array : {arr}')
print(arr.shape)

Original Array : [10 11 12 13 14 15 16 17 18 19]
1-D Array : [19 18 17 16 15]
(5,)


In [159]:
# 1D array with 1D array index , that returns 2D Array
arr1 = np.arange(10,20)
print(f'Original Array : {arr1}')
arr2 = [-1,-2,-3,-4,-5] #indexes of arr1
arr = arr1[[arr2]]
print(f'2-D Array : \n{arr}')
print(arr.shape)
arr = arr1[[arr2,arr2]]
print(f'2-D Array : \n{arr}')
print(arr.shape)

Original Array : [10 11 12 13 14 15 16 17 18 19]
2-D Array : 
[[19 18 17 16 15]]
(1, 5)
2-D Array : 
[[19 18 17 16 15]
 [19 18 17 16 15]]
(2, 5)


In [160]:
# 1D array with 1D array index , that returns 2D Array
arr1 = np.arange(10,20)
print(f'Original Array : {arr1}')
arr2 = [-1,-2,-3,-4,-5] #indexes of arr1
arr = arr1[[arr2],[arr2]] #Error not possible
print(f'2-D Array : \n{arr}')
print(arr.shape)
arr = arr1[arr2,arr2] # Error not possible
print(f'2-D Array : \n{arr}')
print(arr.shape)

Original Array : [10 11 12 13 14 15 16 17 18 19]


IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [161]:
# 1D array with 1D array index , that returns 3D Array
arr1 = np.arange(10,20)
print(arr1)
arr2 = [-1,-2,-3,-4,-5] #indexes of arr1
arr = arr1[[[arr2]]]
print(f'3-D Array : \n{arr}')
print(arr.shape)
arr = arr1[[[arr2],[arr2]]]
print(f'3-D Array : \n{arr}')
print(arr.shape)
arr = arr1[[[arr2,arr2],[arr2,arr2]]]
print(f'3-D Array : \n{arr}')
print(arr.shape)

[10 11 12 13 14 15 16 17 18 19]
3-D Array : 
[[[19 18 17 16 15]]]
(1, 1, 5)
3-D Array : 
[[[19 18 17 16 15]]

 [[19 18 17 16 15]]]
(2, 1, 5)
3-D Array : 
[[[19 18 17 16 15]
  [19 18 17 16 15]]

 [[19 18 17 16 15]
  [19 18 17 16 15]]]
(2, 2, 5)


In [167]:
# 1D array with 1D array index , that returns 1D,2D & 3D Array
arr1 = np.arange(10,20)
print(arr1)
arr2 = [0,-1] #indexes of arr1
arr3 = [1,-2] #indexes of arr1
arr_11 = arr1[arr2] #returns 1D array
print(f'1D Array : \n{arr_11}')
print(arr_11.shape)
arr_12 = arr1[arr3] #returns 1D array
print(f'1D Array : \n{arr_12}\n')
print(arr_12.shape)
arr_2 = arr1[[arr2,arr3]] #returns 2D array
print(f'2D Array : \n{arr_2}\n')
print(arr_2.shape)
arr_3 = arr1[[[arr2,arr3]]] #returns 3D array
print(f'3D Array : \n{arr_3}\n')
print(arr_3.shape)

[10 11 12 13 14 15 16 17 18 19]
1D Array : 
[10 19]
(2,)
1D Array : 
[11 18]

(2,)
2D Array : 
[[10 19]
 [11 18]]

(2, 2)
3D Array : 
[[[10 19]
  [11 18]]]

(1, 2, 2)


In [171]:
arr1 = np.arange(10,20)
print(arr1)
arr2 = [-1,-2,-3,-4,-5] #indexes of arr1
arr3 = [-6,-7,-8,-9,-10] #indexes of arr1
arr_1 = arr1[arr2] #returns 1D array
arr_2 = arr1[[arr2,arr3]] #returns 2D array
arr_3 = arr1[[[arr2,arr3]]] #returns 3D array
print(f'1D Array : \n{arr_1}\n2D Array : \n{arr_2}\n3D Array : \n{arr_3}')
print(arr_1.shape)
print(arr_2.shape)
print(arr_3.shape)

[10 11 12 13 14 15 16 17 18 19]
1D Array : 
[19 18 17 16 15]
2D Array : 
[[19 18 17 16 15]
 [14 13 12 11 10]]
3D Array : 
[[[19 18 17 16 15]
  [14 13 12 11 10]]]
(5,)
(2, 5)
(1, 2, 5)


In [173]:
arr1 = np.arange(10,20)
print(f'Original : {arr1}')
arr2 = [-1,-2,-3] #indexes of arr1
arr3 = [-4,-5,-6] #indexes of arr1
arr4 = [-7,-8,-9] #indexes of arr1
arr = arr1[[arr2,arr3,arr4]] #returns 3D array
print(arr)

Original : [10 11 12 13 14 15 16 17 18 19]
[[19 18 17]
 [16 15 14]
 [13 12 11]]


##### what if we are passing directly the indexs : It works only 1D if you try with gettig 2D it will raises an error

In [174]:
arr1 = np.arange(10,20)
print(arr1)
arr = arr1[[-1,-2,-3,-4,-5]] #returns 1D array
print(arr)

[10 11 12 13 14 15 16 17 18 19]
[19 18 17 16 15]


In [176]:
arr1 = np.arange(10,20)
print(arr1)
arr = arr1[[[-1,-2,-3,-4,-5],[-6,-7,-8]]] #It will not work if we pass directly indexes in 2D or 3D
print(arr)

[10 11 12 13 14 15 16 17 18 19]


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

#### **1.1.2(b) : 2-Dimensional Fancy Indexing**
##### **NOTE :**  For 2-Dimensional Fancy Indexing 
##### If we are passing single 1-Dimensional Array Indexs, It will fetches rows based on index values ...
##### For example I have 4 rows and 5 columns , and i am passing 3 indexes [1,2,3] then we will get 3 rows values based on indexs like for index 1 complete row will display followed by index 2 and 3.
##### FOr 2D Array It will return 2D Only By defaulf : If **Syntax is : arr_var[indexes]**

In [181]:
arr1 = np.arange(1,21).reshape(4,5)
print(f'Array 1 : \n{arr1}')
arr2 = [1,2,3] 
arr = arr1[arr2]
print(f' Final Array : \n{arr}')
print(arr.shape)

Array 1 : 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
 Final Array : 
[[ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
(3, 5)


In [182]:
# Returns 3D array because [[]]
arr1 = np.arange(1,21).reshape(4,5)
print(f'Array 1 : \n{arr1}')
arr2 = [0,-1] 
arr = arr1[[arr2]]
print(f' Final Array : \n{arr}')
print(arr.shape)

Array 1 : 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
 Final Array : 
[[[ 1  2  3  4  5]
  [16 17 18 19 20]]]
(1, 2, 5)


In [185]:
arr1 = np.arange(1,21).reshape(4,5)
print(f'Array 1 : \n{arr1}')
arr2 = [-1,0]
arr3 = [0,-1]
arr = arr1[[arr2,arr3]] # If we mention arr2,arr2 means 2 time it will display in 3D(return 3D) 
                        #It depends how we are passing array indexs whether we are passing in 1D [] or 2D [[]] or 3D [[[]]]
print(f' Final Array : \n{arr}')
print(arr.shape)

Array 1 : 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
 Final Array : 
[[[16 17 18 19 20]
  [ 1  2  3  4  5]]

 [[ 1  2  3  4  5]
  [16 17 18 19 20]]]
(2, 2, 5)


In [186]:
arr1 = np.arange(1,21).reshape(4,5)
print(arr1)
arr2 = [3,0,-2] #I can pass any index (positive or negative) in any order
arr = arr1[[arr2,[-1,0]]] #It depends how we are passing array indexs whether we are passing in 1D [] or 2D [[]] or 3D [[[]]]
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [190]:
arr1 = np.arange(1,21).reshape(4,5)
print(arr1,'\n')
arr = arr1[[3,0,-2,-1,0]] #It depends how we are passing array indexs whether we are passing in 1D [] or 2D [[]] or 3D [[[]]]
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]] 

[[16 17 18 19 20]
 [ 1  2  3  4  5]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [ 1  2  3  4  5]]


##### I Can reshape 2D array to any(1D or 3D) Array by using Fansy Indexing

In [200]:
# We can't convert 2D to 2D array
arr1 = np.arange(1,21).reshape(4,5)
print(arr1,'\n')
arr2 = [-1,0]
arr3 = [0,-3]
arr_1 = arr1[arr2,arr3]
arr_2 = arr1[[arr2,arr3]]
arr_3 = arr1[[[arr2,arr3]]]
print(f'2D Array to 1D Array : \n{arr_1}')
print(f'Shape of Array :{arr_1.shape}\n')
print(f'2D Array to 3D Array : \n{arr_2}')
print(f'Shape of Array :{arr_2.shape}\n')
print(f'2D Array to 4D Array : \n{arr_3}')
print(f'Shape of Array :{arr_3.shape}\n')

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]] 

2D Array to 1D Array : 
[16  3]
Shape of Array :(2,)

2D Array to 3D Array : 
[[[16 17 18 19 20]
  [ 1  2  3  4  5]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 10]]]
Shape of Array :(2, 2, 5)

2D Array to 4D Array : 
[[[[16 17 18 19 20]
   [ 1  2  3  4  5]]

  [[ 1  2  3  4  5]
   [ 6  7  8  9 10]]]]
Shape of Array :(1, 2, 2, 5)



#### **1.1.2(c) : 3-Dimensional Fancy Indexing**

In [205]:
arr1 = np.arange(1,19).reshape(3,2,3)
print(f'Array 1 : \n{arr1}')
arr2 = [1,-2] 
arr = arr1[arr2]
print(f' Final Array : \n{arr}')
print(arr.shape)

Array 1 : 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
 Final Array : 
[[[ 7  8  9]
  [10 11 12]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


#### **1.2 Slicing :**

##### It is the process of fetching elements in sequencial order

##### **Syntax for 1D Slicing : arr_var[start:stop:step]**
##### **Syntax for 2D Slicing : arr_var[start_row:stop_row:step_row , start_col:stop_col:step_col]**
##### **Syntax for 3D Slicing : arr_var[start_row:stop_row:step_row , start_col:stop_col:step_col , start_ele:stop_ele:step_ele,]**

#### **1.2.1 : 1-Dimensional Slicing**

In [210]:
import numpy as np
arr = np.random.randint(1,100,20)
print(arr)

[91 20 26 17 58 40  8 28  7 86 20 68 69 36 54 77 13 33 17 94]


In [211]:
# I need to access elements 20 to 77
print(arr[1:16])

[20 26 17 58 40  8 28  7 86 20 68 69 36 54 77]


In [212]:
# I need to access elements 20,17,40,28,86,68,36 & 77
print(arr[1:16:2])

[20 17 40 28 86 68 36 77]


In [223]:
# I need to access elements 77,36,68,86,28,40,17,20
print(arr[15::-2])

[77 36 68 86 28 40 17 20]


In [227]:
# I need to access alternative elements 
a=arr[::2]
print(arr[::2])
print(a.size)

[91 26 58  8  7 20 69 54 13 17]
10


##### To Understand it we need to trace 

In [230]:
print(f'Original Array : {arr}')
# I need to acces 8 ,7 ,20
print(f'Access Start Index : {arr[6]}')
print(f'Access Stop Index : {arr[6:10+1]}')
print(f'Access Step Index : {arr[6:11:2]}')

Original Array : [91 20 26 17 58 40  8 28  7 86 20 68 69 36 54 77 13 33 17 94]
Access Start Index : 8
Access Stop Index : [ 8 28  7 86 20]
Access Step Index : [ 8  7 20]


#### **1.2.2 : 2-Dimensional Slicing**

In [235]:
import numpy as np
arr = np.random.randint(1,100,20).reshape(4,5)
print(arr)

[[41  2 75 24 41]
 [89 11 79 79 73]
 [47 88  9 13 65]
 [73 36  6 72 78]]


In [247]:
# I need to access the element 
# [41,75,41]
# [47,9,65]
print(arr[0:3:2,0::2])

[[41 75 41]
 [47  9 65]]


In [250]:
# I need to access the element 
# [11,79]
# [36,72]
print(arr[1::2,1::2])

[[11 79]
 [36 72]]


In [251]:
# I need to access the element 
# [41,2]
# [65,88]
print(arr[0::2,-1:-5:-3])

[[41  2]
 [65 88]]


In [254]:
# I need to access the element 
# [78,73]
# [6,79]
# [73,89]
print(arr[-1::-2,-1::-2].T)

[[78 73]
 [ 6 79]
 [73 89]]


In [255]:
# I need to access the element 
# [41,65]
# [75,9]
# [41,47]
print(arr[0::2,-1::-2].T)

[[41 65]
 [75  9]
 [41 47]]


#### **1.2.3 : 3-Dimensional Slicing**

In [269]:
import numpy as np
arr = np.random.randint(1,100,24).reshape(2,3,4)
print(arr)

[[[45 20 72 98]
  [35 85 88 13]
  [37 38 79 36]]

 [[21 24 73 89]
  [53 89 23 42]
  [46 30 16 45]]]


In [276]:
# Access the following elements from the array
# [[45,72]
# [37,79]]
# [[21,73]
# [46,16]]
print(arr[0:,0::2,0::2])

[[[45 72]
  [37 79]]

 [[21 73]
  [46 16]]]


##### Tracing to understand the work flow

In [282]:
# Access the following elements from the array
# [[45,72]
# [37,79]]
# [[21,73]
# [46,16]]
print(f'Original Array : \n{arr}\nShape :{arr.shape}\n')
print(f'Access Row Array : \n{arr[0:]}\n')
print(f'Access Column Array : \n{arr[0:,0::2]}\n')
print(f'Access Elements of Array : \n{arr[0:,0::2,0::2]}\n')
print(f'Final Array : \n{arr[0:,0::2,0::2]}')

Original Array : 
[[[45 20 72 98]
  [35 85 88 13]
  [37 38 79 36]]

 [[21 24 73 89]
  [53 89 23 42]
  [46 30 16 45]]]
Shape :(2, 3, 4)

Access Row Array : 
[[[45 20 72 98]
  [35 85 88 13]
  [37 38 79 36]]

 [[21 24 73 89]
  [53 89 23 42]
  [46 30 16 45]]]

Access Column Array : 
[[[45 20 72 98]
  [37 38 79 36]]

 [[21 24 73 89]
  [46 30 16 45]]]

Access Elements of Array : 
[[[45 72]
  [37 79]]

 [[21 73]
  [46 16]]]

Final Array : 
[[[45 72]
  [37 79]]

 [[21 73]
  [46 16]]]


#### **1.3 : All()**
##### It is a numpy method which is used to check the condition and values.
##### If all the conditions or values are True Then only it returns True.
##### If any one condition or value are False Then it returns False.
##### **Syntax : np.all(condition)**

In [285]:
import numpy as np
arr = np.random.randint(1,100,10)
print(arr)

[89 92 99 43 77  1 27 87 54 73]


In [287]:
print(np.all(arr>1))

False


In [288]:
print(np.all(arr>0))

True


In [289]:
print(np.all(arr%2==0))

False


In [290]:
arr = np.arange(1,20,2)
print(np.all(arr%2!=0))

True


In [291]:
arr = np.arange(0,20,2)
print(np.all(arr%2==0))

True


In [292]:
arr = np.arange(0,20,2)
print(np.all(arr%2!=0))

False


#### **1.4 : Any()**
##### It is a numpy method which is used to check the condition or values is True or Not.
##### If any one condition or value are True Then it returns True.
##### If all the conditions or values are False Then it returns False.
##### **Syntax : np.any(condition)**

In [294]:
import numpy as np
arr = np.random.randint(1,100,10)
print(arr)

[41 24 97 46 92 20 39 55 15 56]


In [295]:
print(np.any(arr>1))

True


In [296]:
print(np.any(arr<1))

False


In [297]:
print(np.any(arr%2==0))

True


In [298]:
print(np.any(arr%2!=0))

True


#### **1.5 : Where()**
##### It is used to fetch the values based on given conditions
##### By using where we fill the values according to the condition and those values must be scalar
##### **Syntax : np.where(condition)** - It return Indexs of that elements where condtion is satisfies
##### **Syntax : np.where(condition,TSB,FSB)** - It returns Values or Fills Values Based on Conditions
##### Where TSB-True Statement Block & FSB-False Statement Block is Optional

In [299]:
import numpy as np
arr = np.random.randint(1,100,10)
print(arr)

[55 22 50 62 88 58 63 69  8 14]


In [300]:
print(np.where(arr%2==0))

(array([1, 2, 3, 4, 5, 8, 9]),)


In [301]:
print(np.where(arr%2==0,1,0))

[0 1 1 1 1 1 0 0 1 1]


In [302]:
print(np.where(arr%2==0,arr,0))

[ 0 22 50 62 88 58  0  0  8 14]
