# **Numpy(Numerical Python) Library :**

## **Random Values:**

#### 1.1 Randint()
#### 1.2 Rand()
#### 1.3 Randn()
#### 1.4 Choice()
#### 1.5 Uniform()

#### **1.1 Randint():**

##### It always generates the random integer value.It is an numpy method which is used to generate random integers based on given n values
##### **Syntax 1: np.random.randint(value)** 
##### **Syntax 1: np.random.randint(low,high)**
##### **Syntax 1: np.random.randint(low,high,n)**
##### **Syntax for 1D Array : np.random.randint(low,high,(number of elements(n)))**
##### **Syntax for 2D Array : np.random.randint(low,high,(row,column))**
##### **Syntax for 3D Array : np.random.randint(low,high,(row,column,elements))**
##### **Low included,High Excluded**
##### **Note:** For Single Element Array - It returns Single Random value => np.random.randint(value1)
#####  For Single Element low and hight Between two values - It returns Single Random value between low(included) and high(excluded)
#####  For Number of elements between two values  - It returns Number of Random values between hig and low with n(number of random elemenets between low and high)  
##### Every time we will get an different number
##### We can provide only positive n value for 1D Array - negative random values it won't work
##### We can provide positive or negative value in between low and high and low,high with n
##### Always **low >= high**
##### **NOTE : It will generate both positive and negative random values based on the high and low values**

##### **Note:** It works only positive n value and it return single value, Output will change every time

In [10]:
# Positive Value
import numpy as np
arr = np.random.randint(50)
arr

46

In [15]:
# Negative Value
import numpy as np
arr = np.random.randint(-50)
arr

ValueError: high <= 0

##### **Note:** It works with both positive start value and negative stop value only,(no vice-versa) and it return single value, Output will change every time

In [13]:
# Positive low and high value
import numpy as np
arr = np.random.randint(5,100)
arr

11

In [14]:
# Negative low and Positive high value
import numpy as np
arr = np.random.randint(-50,100)
arr

-46

In [16]:
# Positive low and Negative hogh value
import numpy as np
arr = np.random.randint(5,-100)
arr

ValueError: low >= high

##### **Note:** It works with both positive start value and negative stop value only,(no vice-versa) and it return single value, Output will change every time

In [12]:
# Positive low and High value
import numpy as np
arr = np.random.randint(5,100,10)
arr

array([98, 17, 52, 90, 85, 61, 29, 90, 31, 58], dtype=int32)

In [17]:
# Negative Low and Positive High value
import numpy as np
arr = np.random.randint(-50,100,10)
arr

array([ 87,  33,  34,  35,  39, -44, -24, -37,  -7,   8], dtype=int32)

In [20]:
# Negative Low and Negative High value
import numpy as np
arr = np.random.randint(-50,-10,10)
arr

array([-44, -17, -42, -16, -35, -41, -41, -25, -29, -40], dtype=int32)

In [21]:
# Negative Low and Positive High value
import numpy as np
arr = np.random.randint(50,-100,10)
arr

ValueError: low >= high

##### **1-Dimensional Array:**

In [22]:
import numpy as np
arr = np.random.randint(5,100,10)
arr

array([61, 13, 96, 39, 68, 75, 55, 24, 90, 57], dtype=int32)

##### **2-Dimensional Array:**

In [28]:
import numpy as np
arr = np.random.randint(5,100,(5,4))
arr

array([[26, 24, 67,  8],
       [83, 84, 98, 14],
       [89, 68,  8, 47],
       [34, 46, 19, 53],
       [27, 15, 88, 94]], dtype=int32)

##### **3-Dimensional Array:**

In [29]:
import numpy as np
arr = np.random.randint(5,100,(3,5,5))
arr

array([[[24, 18, 68, 15, 53],
        [26, 63, 43, 37, 43],
        [40, 36, 60, 81, 50],
        [14, 36, 53, 94, 76],
        [89, 95, 30, 86, 93]],

       [[22, 15, 68, 63, 20],
        [46, 21, 59, 43, 58],
        [81, 88,  8, 22, 65],
        [70, 58, 49, 13, 66],
        [51, 18, 76, 45, 50]],

       [[75, 24, 71, 22, 14],
        [26, 46, 58, 79, 77],
        [66, 53, 62, 83, 97],
        [56, 60, 33, 45, 55],
        [24, 52, 22, 48, 52]]], dtype=int32)

#### **1.2. Rand():**

##### It always generates the random values between 0 to 1. It generates values based on uniform 
##### **Syntax for 1D Array : np.random.rand(n)**
##### **Syntax for 2D Array : np.random.rand(row,column)**
##### **Syntax for 3D Array : np.random.rand(row,column,elements)**
##### **NOTE : It will generate only positive random values between 0 to 1**

##### **1-Dimensional Array:**

In [30]:
import numpy as np
arr = np.random.rand(10)
arr

array([0.40383902, 0.16615148, 0.80013758, 0.01023291, 0.50879701,
       0.10326608, 0.80566883, 0.51629705, 0.03367209, 0.65032479])

##### **2-Dimensional Array:**

In [31]:
import numpy as np
arr = np.random.rand(1,21)
arr

array([[0.86138277, 0.59769948, 0.8859511 , 0.52410218, 0.61622341,
        0.75476108, 0.7854075 , 0.70263094, 0.91594578, 0.10288314,
        0.38141336, 0.79281938, 0.83974758, 0.62040834, 0.45816746,
        0.75617385, 0.89360566, 0.6098203 , 0.67334776, 0.14738046,
        0.19821408]])

##### **3-Dimensional Array:**

In [33]:
import numpy as np
arr = np.random.rand(2,3,4)
arr

array([[[0.09802667, 0.69658601, 0.17434097, 0.76033976],
        [0.27592014, 0.69948618, 0.62181014, 0.46576187],
        [0.39041758, 0.05947604, 0.09039792, 0.70199865]],

       [[0.26181784, 0.38899945, 0.78208678, 0.98054789],
        [0.60874495, 0.62103462, 0.15949401, 0.28661384],
        [0.64090199, 0.62422347, 0.93586396, 0.43537155]]])

In [37]:
import numpy as np
arr = np.random.rand(2,3,3)
arr

array([[[0.56489107, 0.85907804, 0.9082556 ],
        [0.9362098 , 0.67152514, 0.37225943],
        [0.69259876, 0.85338421, 0.82115345]],

       [[0.08334655, 0.45007699, 0.27441146],
        [0.30921446, 0.02875647, 0.6702178 ],
        [0.9356476 , 0.94322693, 0.6992805 ]]])

#### **1.3. Randn():**

##### It generates the values based on Normal Distribution & the values will generate both positive and negative [To create noisy data we use randn(). (Values are distributed around the mean)
##### **Syntax for 1D : np.random.randn(n)**
##### **Syntax for 2D : np.random.randn(rows,colmns)**
##### **Syntax for 3D : np.random.randn(rows,columns,n)**
##### **NOTE : It will generate both positive and negative random values**

##### **1-Dimensional Array:**

In [38]:
import numpy as np
arr = np.random.randn(20)
arr

array([-1.2108072 ,  0.82763813, -1.73808357, -1.34227611,  0.44535311,
       -0.6062721 , -1.474367  ,  0.53286622, -0.09433437,  2.50956503,
        0.07470082,  1.81957223, -0.35931256,  0.97872031, -1.90449973,
        0.45817137, -0.17928922, -0.303579  ,  0.58822226, -2.62810588])

##### **2-Dimensional Array:**

In [40]:
import numpy as np
arr = np.random.randn(2,4)
arr

array([[ 0.04528114, -0.62525188, -1.55120495,  1.30454912],
       [-2.32698647,  1.2215383 , -0.38984508, -0.15474997]])

##### **3-Dimensional Array:**

In [41]:
import numpy as np
arr = np.random.randn(2,3,4)
arr

array([[[ 1.39421427e+00,  3.45830248e-03, -1.40961507e+00,
          9.06417356e-01],
        [ 1.72985532e+00, -2.36330586e-01,  1.33805298e+00,
         -5.91356798e-01],
        [ 2.12377642e-01,  6.91370855e-01, -9.74769993e-01,
         -1.26302477e+00]],

       [[ 1.71599413e+00, -1.29213290e+00,  2.19442842e-01,
         -6.06359778e-01],
        [ 5.02300003e-01, -6.55874011e-01,  2.82108274e-01,
         -6.23250409e-01],
        [ 1.41298252e+00,  4.84798764e-04,  3.89277578e-01,
         -1.81967758e+00]]])

#### **1.4. Choice():**

##### **Syntax : np.random.choice(array/colllection, size=None, replace=True, p=None)**
##### It return one random value from given collections
##### **Parameters:**
##### **array/collection:** 1D array-like or int. If int n, samples from np.arange(n). 1D array
##### **size:** Number of samples (int or tuple). Default is one value.
##### **replace:** If True, samples with replacement. Default is True.
##### **p:** probability distribution for choosing elements. Default is None.

##### **1-Dimensional Array:** It return an output - np.int64(2), to get element we need to use .item() or type casting int()

In [48]:
import numpy as np
np.random.choice([1,2,3,4])

np.int64(3)

In [54]:
import numpy as np
np.random.choice([1,2,3,4]).item()

3

In [57]:
import numpy as np
int(np.random.choice([1,2,3,4]))

3

##### **Note:** It will not work with 2D or 3D array. Array must be 1-dimensional

In [62]:
import numpy as np
np.random.choice([[1,2,3,4],[4,5,6,7]])

ValueError: a must be 1-dimensional

##### If we want n values then we use np.arange()

In [66]:
import numpy as np
np.random.choice(np.arange(10))

np.int64(2)

In [68]:
import numpy as np
np.random.choice(np.arange(10)).item()

8

In [67]:
import numpy as np
int(np.random.choice(np.arange(10)))

3

##### **size:** If we want only n random values means we need to mention n values. We can also give n value greater than the collection it will generate that many number of random values

In [69]:
import numpy as np
np.random.choice([1,2,3,4,5,6,7],3)

array([6, 4, 5])

In [71]:
import numpy as np
np.random.choice([1,2,3,4,5,6,7],8)

array([6, 4, 5, 5, 1, 4, 5, 3])

##### **replace:** It is used to repeat the element. If replace=True then the random elements from collection will return, else if replace=False then random elements will not repeate. 
##### **Note:** If we are using replacce as arguement then make sure that n value should be less than or equalt to lenght or collection

In [78]:
import numpy as np
np.random.choice([1,2,3,4,5,6,7],7,replace=True)

array([4, 2, 3, 6, 2, 2, 2])

In [79]:
import numpy as np
np.random.choice([1,2,3,4,5,6,7],10,replace=True)

array([6, 3, 6, 3, 5, 7, 5, 4, 5, 5])

In [83]:
import numpy as np
np.random.choice([1,2,3,4,5,6,7],7,replace=False)

array([5, 4, 6, 3, 1, 7, 2])

In [84]:
import numpy as np
np.random.choice([1,2,3,4,5,6,7],10,replace=False)

ValueError: Cannot take a larger sample than population when 'replace=False'

##### **p** probability distribution for choosing elements.
##### 'array/collection' and 'p' must have same size.
##### p=[0.1, 0.4, 0.1, 0.1, 0.1, 0.1, 0.1] = 1 then only it will execute.
##### The probability of 2 is 0.9 and 1 is 0.1

In [97]:
import numpy as np
np.random.choice([1,2,3,4,5,6,7],10, p=[0.1, 0.9, 0.0, 0.0, 0.0, 0.0, 0.0])

array([1, 2, 2, 2, 2, 2, 2, 2, 2, 2])

##### We can perform array variable with string also.

In [106]:
import numpy as np
print(np.random.choice([1,2,3,'A','B'],10))
print(np.random.choice([1.7,2.3],10))

['2' 'A' '1' '1' 'A' 'B' '1' 'B' 'B' '3']
[1.7 2.3 1.7 2.3 2.3 2.3 1.7 1.7 2.3 1.7]


ValueError: a must be 1-dimensional or an integer

#### **1.5. Uniform():**

##### Generates random numbers from a uniform distribution (All values have equal probability) and it return float values only. Low value(included) High value (Excluded)
##### **Syntax : np.random.uniform(low=0.0, high=1.0, size=None)**

In [100]:
import numpy as np
np.random.uniform(low=1,high=4,size=10)

array([1.40371426, 1.86986765, 1.64981998, 1.09570663, 3.26185107,
       2.10874322, 3.252365  , 3.18480681, 3.37297573, 3.55138778])

In [103]:
import numpy as np
np.random.uniform(low=1,high=10,size=10)

array([7.8532336 , 1.34773895, 3.6190904 , 8.25499598, 6.35835693,
       7.92922503, 6.57879943, 5.63173731, 3.31171637, 2.21968865])