# **Numpy(Numerical Python) Library :**

### **1.Creating NumPy Arrays :**
#### **1.1 np.array()**
#### **1.2 np.arange()**
#### **1.3 np.ones()**
#### **1.4 np.zeros()**
#### **1.5 np.eye()**
#### **1.6 np.linspace()**
#### **1.7 np.fromIter()**
#### **1.8 np.full()**
#### **1.9 np.empty()**
#### **1.10 np.identity()**

##### **============================================================** 
#### **1.1 np.array() :** 
##### **============================================================** 
##### Use np.array() when you want to convert Python lists into NumPy arrays.

##### **Syntax : np.array(arrayElements)**
##### **Parameters:**
##### **arrayelements** - Pass the set of array element collection

##### **1.1.1. 1-Dimensional Array :** We can create a 1D Array by passing a one set of array elements 

In [35]:
# 1 Dimension Array : 
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


##### **1.1.2 2-Dimension Array :** We can create a 2D Array by passing 2 set of array elements 

In [7]:
# 2 Dimension Array : 
import numpy as np
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


##### **1.1.3 3-Dimension Array :** We can create a 3D Array by passing 2-3 set of array elements 

In [2]:
# 3 Dimension Array : 
import numpy as np
arr3 = np.array([[[1,2,3],[6,7,8]],[[11,12,13],[15,17,19]]])
print(arr3)

[[[ 1  2  3]
  [ 6  7  8]]

 [[11 12 13]
  [15 17 19]]]


##### **dtype:** we can change the data type of array using dtype.
##### It supports all types of single value and multi value data types exists in python

In [38]:
# 1 Dimension Array : 
import numpy as np
arr = np.array([1,2,3,4,5],dtype=int)
print(arr)
arr = np.array([1,2,3,4,5],dtype=float)
print(arr)
arr = np.array([1,2,3,4,5],dtype=complex)
print(arr)
arr = np.array([1,2,3,4,5],dtype=bool)
print(arr)
arr = np.array([1,2,3,4,5],dtype=str)
print(arr)
arr = np.array([1,2,3,4,5],dtype=list)
print(arr)
arr = np.array([1,2,3,4,5],dtype=tuple)
print(arr)
arr = np.array([1,2,3,4,5],dtype=set)
print(arr)
arr = np.array([1,2,3,4,5],dtype=frozenset)
print(arr)
arr = np.array([1,2,3,4,5],dtype=dict)
print(arr)
arr = np.array([1,2,3,4,5],dtype=range)
print(arr)

[1 2 3 4 5]
[1. 2. 3. 4. 5.]
[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]
[ True  True  True  True  True]
['1' '2' '3' '4' '5']
[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5]


##### **Note** : We can process not only numerical data we can pass any kind of data type, If we pass string data type in array it will execute as it is
##### But if we trying to convert string to any other data type such as int,flaot,complex it will raise an error [Type Casting Concept should be clear to understand this]

In [39]:
arr = np.array(["A","B","C"])
print(arr)

['A' 'B' 'C']


In [40]:
arr = np.array(["A","B","C"],dtype=int)
print(arr)

ValueError: invalid literal for int() with base 10: 'A'

In [43]:
arr = np.array(["A","B","C"],dtype=list)
print(arr)
arr = np.array(["A","B","C"],dtype=tuple)
print(arr)
arr = np.array(["A","B","C"],dtype=set)
print(arr)
arr = np.array(["A","B","C"],dtype=frozenset)
print(arr)
arr = np.array(["A","B","C"],dtype=dict)
print(arr)
arr = np.array(["A","B","C"],dtype=range)
print(arr)

['A' 'B' 'C']
['A' 'B' 'C']
['A' 'B' 'C']
['A' 'B' 'C']
['A' 'B' 'C']
['A' 'B' 'C']


##### **IMPORTANT NOTE**
##### While creating any Dimension of array we must pass same size of array elements at the both side.
##### If we pass different sizes of array elements in 2D or 3D array ot throws an error

In [9]:
# 1 Dimension Array : 
import numpy as np
arr2 = np.array([[1,2,3],[4,5]])
print(arr2)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

##### **Note :** raise an error : Because number of **rows** and **columns** from both array must be **same**

##### **Note2 :** While Creating an 2D and 3D Array ( Any type of array excluding 1D.......) 2D or 3D We must pass same number of rows and columns

##### **============================================================** 
##### **1.1.4.Priority in Numpy :**
##### While creating any type of array , If we pass entire array elements as as int then it will display array elements as it is....
##### If we pass any one array element as as float or complex then it will display array elements based on the **Order of Priority**....

##### **Order of Priority from Lowest Priority to Highest Priority :**
##### 1.bool
##### 2.int
##### 3.float
##### 4.Complex
##### 5.string
##### 6.object

##### **1.1.5.Normal Array :** Entire array elements are integer type only

In [14]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


##### **1.1.6.Mixed Data type Array :** (int + float)
##### Suppose if I am passing integer elements and float elements then, 
##### It will returns the array elements based on the Order of Priority :::::::

In [41]:
import numpy as np
arr = np.array([1 , 2 , 3.6 , 4 , 5.8])
print(arr) 

[1.  2.  3.6 4.  5.8]


##### **Note :** We will get float elements in array, BECAUSE FLOAT HAVING HIGHEST PRIORITY THAN INT

##### **1.1.7.Mixed Data type Array :** (int + float + complex)
##### Suppose if I am passing integer,float and complex elements then, 
##### It will returns the array elements based on the Order of Priority :::::::

In [23]:
import numpy as np
arr = np.array([1+9j , 2 , 3 , 4 , 5])
print(arr) 

[1.+9.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]


##### **Note :** We will get float elements in array with complex elements,BECAUSE FLOAT HAVING HIGHEST PRIORITY THAN INT AND COMPLEX HAVING HIGHER PRIORITY THAN FLOAT

##### **1.1.8.Mixed Data type Array :** (int + float + complex + string)

In [27]:
import numpy as np
arr = np.array([4+7j , 2 , 3.8 , 4 , "5"])
print(arr)

['(4+7j)' '2' '3.8' '4' '5']


##### **NOTE :** Here In example 4 we passed integer elements as well as float elements and string elements and String Has Highest priority than int and float, But here it will conver the entire array list elements to the string only with considering int and float and complex also directly converted to the string as it is

##### **1.1.9.Mixed Data type Array :** (bool + int)

In [42]:
import numpy as np
arr = np.array([1,2,3,True,False,9])
print(arr)

[1 2 3 1 0 9]


##### **Note :** In Boolean Data Type **True** will return as **1** and **False** will return as **0**

##### **1.1.10.Mixed Data type Array :** (bool + int + float + complex + string + object)

In [44]:
import numpy as np
_obj = "Object" 
arr = np.array([1 , 2.8 , 3+7j , True , False , "Hello" , "100" , _obj])
print(arr)
print(_obj)
print(type(_obj))

['1' '2.8' '(3+7j)' 'True' 'False' 'Hello' '100' 'Object']
Object
<class 'str'>


##### **Note :** Object May be Any Type(int,flaot,str,list,set,tuple,dictionary) But when we checking th particular element type from array elements,It always returns a string object only Because Array object returns the objects interms of string only

In [45]:
import numpy as np
obj = 893232  
arr = np.array([1 , 2.8 , 3+7j , True , False , "Hello" , "100" , obj])
print(arr)
print(obj)
print(type(obj))

['1' '2.8' '(3+7j)' 'True' 'False' 'Hello' '100' '893232']
893232
<class 'int'>


In [51]:
print(type(arr[0]))

<class 'numpy.str_'>


##### **============================================================** 
#### **Using Numpy Functions :** 
##### **============================================================** 
##### NumPy provides quick utility functions for creating arrays filled with zeros, ones, or ranges:

##### **============================================================** 
#### **1.2 np.arange():**
##### **============================================================** 
##### This is an inbuilt NumPy function that returns evenly spaced values within a given interval.
##### **Syntax :** **np.arange( start , stop, step , dtype=None )**
##### It returns array elements interms of Float as a Default array data type
##### dtype is optional here
##### start value is also optional if you dont want to specify, but if you want specific start value we can use start value. Similar step value is optional, If we want specific step we can use it
##### **Parameters:**
##### **start** - starting value of array(including starting value) 
##### **stop** - ending value of array(excluding ending value)
##### **step** - step is used to increment or decrement step value
##### **dtype** - used to change the type of data and convert the data from one data type of array to other type of array
##### default Data type (dtype) is **Float**

##### **start & stop** : We need to speicify the start and stop value while creating an array
##### start value is not manadatory, if we doesn't specify it will consider default value as 0

In [24]:
# 1D Array :
import numpy as np
arr=np.arange(10)
print(arr)
print(type(arr))
print(arr.dtype)

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
int64


In [23]:
# 1D Array :
import numpy as np
arr=np.arange(1,10)
print(arr)
print(type(arr))
print(arr.dtype)

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
int64


##### **start,stop & step** : We need to speicify the start and stop value while creating an array
##### start value is not manadatory, if we doesn't specify it will consider default value as 0
##### But if we doesn't specify start value directly we specify step value means the interpreter will treat as start and stope value and returns empty array
##### By Default step value is 1 always

In [25]:
# 1D Array :
import numpy as np
arr=np.arange(1,10,2)
print(arr)
print(type(arr))
print(arr.dtype)

[1 3 5 7 9]
<class 'numpy.ndarray'>
int64


In [26]:
# 1D Array :
import numpy as np
arr=np.arange(10,2)
print(arr)
print(type(arr))
print(arr.dtype)

[]
<class 'numpy.ndarray'>
int64


##### **Note :** If we specify step value as negative then it gives same result as empty array

In [28]:
# 1D Array :
import numpy as np
arr=np.arange(10,200,-1)
print(arr)
print(type(arr))
print(arr.dtype)

[]
<class 'numpy.ndarray'>
int64


##### **Note :** It doesn't support creating 2D or 3D array elemenets, just it will generate series of array elements. 

In [29]:
# 2D Array :
import numpy as np
arr=np.arange((1,10),50)
print(arr)
print(type(arr))
print(arr.dtype)

TypeError: unsupported operand type(s) for -: 'int' and 'tuple'

##### **dtype :** used to convert array elements default data type to needed data type but it will not support string data type as well as a for Boolean data type values must be 1/2 onl,More than 2 values it will throws an error

In [30]:
# 1D Array :
import numpy as np
arr=np.arange(1,20,2,dtype=int)
print(arr)
print(type(arr))
print(arr.dtype)

[ 1  3  5  7  9 11 13 15 17 19]
<class 'numpy.ndarray'>
int64


##### **Note :** 
##### -> dtype is option field in the arange() where we need to specify the type of dtype that being used to generate the array elements such as int,float,complex,list,tuple,set,dict and range (but for str it is not supported)
##### -> int,float,complex,bool - these are numeric dtype | list,tuple,set,dict and range - these all are objects

In [84]:
# 1D Array :
import numpy as np
arr=np.arange(1,21,2,dtype=float)
print(arr)
print(arr.dtype)

[ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19.]
float64


In [85]:
# 1D Array :
import numpy as np
arr=np.arange(1,21,3,dtype=complex)
print(arr)
print(arr.dtype)

[ 1.+0.j  4.+0.j  7.+0.j 10.+0.j 13.+0.j 16.+0.j 19.+0.j]
complex128


In [74]:
# 1D Array :
import numpy as np
arr=np.arange(1,21,2,dtype=list)
print(arr)
print(arr.dtype)

[1 3 5 7 9 11 13 15 17 19]
object


In [75]:
# 1D Array :
import numpy as np
arr=np.arange(1,21,2,dtype=tuple)
print(arr)
print(arr.dtype)

[1 3 5 7 9 11 13 15 17 19]
object


In [76]:
# 1D Array :
import numpy as np
arr=np.arange(1,21,2,dtype=dict)
print(arr)
print(arr.dtype)

[1 3 5 7 9 11 13 15 17 19]
object


In [77]:
# 1D Array :
import numpy as np
arr=np.arange(1,21,2,dtype=set)
print(arr)
print(arr.dtype)

[1 3 5 7 9 11 13 15 17 19]
object


In [78]:
# 1D Array :
import numpy as np
arr=np.arange(1,21,2,dtype=range)
print(arr)
print(arr.dtype)

[1 3 5 7 9 11 13 15 17 19]
object


##### **Note:** We can also pass dtype as **np.int32** specifically

In [90]:
# 1D Array :
import numpy as np
arr=np.arange(1,21,2,dtype=np.int32)
print(arr)
print(arr.dtype)

[ 1  3  5  7  9 11 13 15 17 19]
int32


In [118]:
# 1D Array :
import numpy as np
arr=np.arange(1,5,2,dtype=bool)
print(arr)
print(arr.dtype)

[ True  True]
bool


##### **Note** : dtype for boolen value, It will take only 1/2 boolen data's. If we give more than 2 boolean elements it trows an error

In [5]:
# 1D Array :
import numpy as np
arr=np.arange(1,2,1,dtype=bool)
print(arr)
print(arr.dtype)

[ True]
bool


In [4]:
# 1D Array :
import numpy as np
arr=np.arange(1,3,1,dtype=bool)
print(arr)
print(arr.dtype)

[ True  True]
bool


In [6]:
# 1D Array :
import numpy as np
arr=np.arange(1,20,2,dtype=bool)
print(arr)
print(arr.dtype)

TypeError: arange() is only supported for booleans when the result has at most length 2.

##### **Note :** arange() function will not support string data type

In [119]:
# 1D Array :
import numpy as np
arr=np.arange(1,21,2,dtype=str)
print(arr)
print(arr.dtype)

TypeError: arange() not supported for inputs with DType <class 'numpy.dtypes.StrDType'>.

##### **Note :** np.arange() is only supported for booleans when the result has at most length 2. 
##### means the generate array elements length should be 2 only..Not more than that,if we enter more than 2 array elements it will rises an error

In [44]:
# 1D Array :
import numpy as np
arr=np.arange(1,21,2,dtype=int)
print(arr,arr.dtype)
arr=np.arange(1,21,2,dtype=float)
print(arr,arr.dtype)
arr=np.arange(1,21,4,dtype=complex)
print(arr,arr.dtype)
arr=np.arange(1,5,2,dtype=bool)
print(arr,arr.dtype)
arr=np.arange(1,21,2,dtype=list)
print(arr,arr.dtype)
arr=np.arange(1,21,2,dtype=tuple)
print(arr,arr.dtype)
arr=np.arange(1,21,2,dtype=set)
print(arr,arr.dtype)
arr=np.arange(1,21,2,dtype=frozenset)
print(arr,arr.dtype)
arr=np.arange(1,21,2,dtype=dict)
print(arr,arr.dtype)
arr=np.arange(1,21,2,dtype=range)
print(arr,arr.dtype)

[ 1  3  5  7  9 11 13 15 17 19] int64
[ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19.] float64
[ 1.+0.j  5.+0.j  9.+0.j 13.+0.j 17.+0.j] complex128
[ True  True] bool
[1 3 5 7 9 11 13 15 17 19] object
[1 3 5 7 9 11 13 15 17 19] object
[1 3 5 7 9 11 13 15 17 19] object
[1 3 5 7 9 11 13 15 17 19] object
[1 3 5 7 9 11 13 15 17 19] object
[1 3 5 7 9 11 13 15 17 19] object


##### To Create **2D or 3D Array** we should use **reshape()** function , without reshape() we cannot create 2D or 3D Array....
##### np.arange() is only used to generate the array elements 
##### **NOTE :** If we want to create 2D array with arange() we can't do only with arange() methon we need to use reshape() to change the 1D array to 2D and 1D to 3D array

##### **============================================================** 
#### **1.3. np.ones():**
##### **============================================================** 
##### This function is used to get a new array of given shape and type filled with ones (1).
##### **Syntax:** **np.ones(shape, dtype=None, order='C')**
##### Default data type is float
##### dtype and order is optional
##### **Parameters:**
##### **shape** - Used for dimension,It gives shape for array to create any(1D,2D,3D) dimension of array.
##### shape(for 1D) - [rows]
##### shape(for 2D) - [rows,cols]
##### shape(for 3D) - [rows,cols,n(elements)]
##### **dtype** - Used to convert the type of data from one data type to another data type
##### **order** - Used to store the array elements in a memory
##### The order="C" parameter defines how the array is stored in memory, specifically using Row-Major Order(Row by Row). 
##### The order="F" parameter defines how the array is stored in memory, specifically using Column-Major Order(Column by Column). 

##### **1D Array :** If we want to create 1 Dimension array just we need to specify the single element. 
##### we can declare array elements size inside the square brackets[] or paranthesis () or keep as it is

##### **1-Dimensional Array:** To create 1D array we need to pass single element as n value, so that many number of arrays can be created
##### By default it returns array elements as floating data type
##### For 1D Array we can pass directly size of array (n) , and you can pass n value inside [] or ()   

In [32]:
# 1D Array :
import numpy as np
arr=np.ones(4)
print(arr)
print(arr.dtype)

[1. 1. 1. 1.]
float64


In [15]:
# 1D Array :
import numpy as np
arr=np.ones((4))
print(arr)
print(arr.dtype)

[1. 1. 1. 1.]
float64


In [16]:
# 1D Array :
import numpy as np
arr=np.ones([4])
print(arr)
print(arr.dtype)

[1. 1. 1. 1.]
float64


##### **2D Array :** If we want to create 2 Dimension array just we need to specify the row and column values to create an array element 
##### we can declare array elements size inside the square brackets[] or paranthesis () or keep as it is
##### For 2D array must and should pass row and column value is manadatory

In [17]:
# 2D Array :
import numpy as np
arr=np.ones([4,4])
print(arr)
print(arr.dtype)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
float64


##### **Note:** Its Manadatory to pass 2D or 3D array inside the parenthesis () or square brackets []
##### Otherwise it consider two positional arguement, 1st arguement as a array size , and second arguement as a dtype and throws an error

In [18]:
# 2D Array :
import numpy as np
arr=np.ones(4,4)
print(arr)
print(arr.dtype)

TypeError: Cannot interpret '4' as a data type

##### **3D Array :** If we want to create 3 Dimension array just we need to specify the row and column values with number of elements (n) to create an array element 
##### we can declare array elements size inside the square brackets[] or paranthesis () or keep as it is
##### For 3D array must and should pass row and column value with number of elements is manadatory

In [19]:
# 3D Array :
import numpy as np
arr=np.ones([2,3,2])
print(arr)
print(arr.dtype)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]
float64


##### **dtype :**  If we want to change the data type of array from default data type(float) to another specified data type

In [20]:
# 1D Array :
import numpy as np
arr=np.ones(4,dtype=int)
print(arr)
print(arr.dtype)

[1 1 1 1]
int64


In [21]:
# 1D Array :
import numpy as np
arr=np.ones(4,dtype=np.int32)
print(arr)
print(arr.dtype)

[1 1 1 1]
int32


In [103]:
# 2D Array :
import numpy as np
arr=np.ones([4,4],dtype=float)
print(arr)
print(arr.dtype)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
float64


In [104]:
# 2D Array :
import numpy as np
arr=np.ones([4,4],dtype=complex)
print(arr)
print(arr.dtype)

[[1.+0.j 1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j 1.+0.j]]
complex128


In [105]:
# 2D Array :
import numpy as np
arr=np.ones([4,4],dtype=str)
print(arr)
print(arr.dtype)

[['1' '1' '1' '1']
 ['1' '1' '1' '1']
 ['1' '1' '1' '1']
 ['1' '1' '1' '1']]
<U1


In [106]:
# 2D Array :
import numpy as np
arr=np.ones([4,4],dtype=list)
print(arr)
print(arr.dtype)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
object


In [107]:
# 2D Array :
import numpy as np
arr=np.ones([4,4],dtype=tuple)
print(arr)
print(arr.dtype)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
object


In [108]:
# 2D Array :
import numpy as np
arr=np.ones([4,4],dtype=set)
print(arr)
print(arr.dtype)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
object


In [109]:
# 2D Array :
import numpy as np
arr=np.ones([4,4],dtype=dict)
print(arr)
print(arr.dtype)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
object


In [110]:
# 2D Array :
import numpy as np
arr=np.ones([4,4],dtype=range)
print(arr)
print(arr.dtype)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
object


In [111]:
# 2D Array :
import numpy as np
arr=np.ones([4,4],dtype=frozenset)
print(arr)
print(arr.dtype)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
object


In [112]:
# 2D Array :
import numpy as np
arr=np.ones([4,4],dtype=bool)
print(arr)
print(arr.dtype)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
bool


##### **order :** It will store the array elements which is optional to declare

In [121]:
# 2D Array :
import numpy as np
arr=np.ones([4,4],dtype=int,order="C")
print(arr)
print(arr.dtype)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
int64


In [122]:
# 2D Array :
import numpy as np
arr=np.ones([4,4],dtype=int,order="F")
print(arr)
print(arr.dtype)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
int64


##### **Note :** Here for order "C" and "F" the output is same but internally the array elements are either row by row or column by column

##### **============================================================** 
#### **1.4. np.zeros():**
##### **============================================================** 
##### This function is used to get a new array of given shape and type filled with zeros (0). 
##### **Syntax: numpy.zeros(shape, dtype=None, order='C')**
##### Default data type is float
##### dtype and order is optional
##### **Parameters:**
##### **shape** - Used for dimension,It gives shape for array to create any(1D,2D,3D) dimension of array.
##### shape(for 1D) - [rows]
##### shape(for 2D) - [rows,cols]
##### shape(for 3D) - [rows,cols,n(elements)]
##### **dtype** - Used to convert the type of data from one data type to another data type
##### **order** - Used to store the array elements in a memory
##### The order="C" parameter defines how the array is stored in memory, specifically using Row-Major Order(Row by Row). 
##### The order="F" parameter defines how the array is stored in memory, specifically using Column-Major Order(Column by Column). 

##### **1-Dimensional Array:** To create 1D array we need to pass single element as n value, so that many number of arrays can be created
##### By default it returns array elements as floating data type
##### For 1D Array we can pass directly size of array (n) , and you can pass n value inside [] or ()   

In [48]:
# 1D Array :
import numpy as np
arr=np.zeros(4)
print(arr)
print(arr.dtype)

[0. 0. 0. 0.]
float64


##### **2D Arrya :** If we want to create 2 Dimension array just we need to specify the row and column values to create an array element 
##### we can declare array elements size inside the square brackets[] or paranthesis () or keep as it is
##### For 2D array must and should pass row and column value is manadatory

In [47]:
# 2D Array :
import numpy as np
arr=np.zeros([4,4])
print(arr)
print(arr.dtype)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
float64


##### **3D Array :** If we want to create 3 Dimension array just we need to specify the row and column values with number of elements as n to create an array element 
##### we can declare array elements size inside the square brackets[] or paranthesis () or keep as it is
##### For 3D array must and should pass row and column value with number of elements is manadatory

In [46]:
# 3D Array :
import numpy as np
arr=np.zeros([4,4,2])
print(arr)
print(arr.dtype)

[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]
float64


##### **dtype :** Used to convert the array element data type to specific elements data type

In [49]:
# 2D Array :
import numpy as np
arr=np.zeros([4,4],dtype=int)
print(arr)
print(arr.dtype)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
int64


In [126]:
# 2D Array :
import numpy as np
arr=np.zeros([4,4],dtype=float)
print(arr)
print(arr.dtype)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
float64


In [5]:
# 2D Array :
import numpy as np
arr=np.zeros([2,3],dtype=complex)
print(arr)
print(arr.dtype)

[[0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]]
complex128


In [6]:
# 2D Array :
import numpy as np
arr=np.ones([4,4],dtype=bool)
print(arr)
print(arr.dtype)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
bool


In [14]:
# 2D Array :
import numpy as np
arr=np.zeros([4,3],dtype=list)
print(arr)
print(arr.dtype)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
object


In [15]:
# 2D Array :
import numpy as np
arr=np.zeros([4,4],dtype=str)
print(arr)
print(arr.dtype)

[['' '' '' '']
 ['' '' '' '']
 ['' '' '' '']
 ['' '' '' '']]
<U1


In [16]:
# 2D Array :
import numpy as np
arr=np.zeros([4,4],dtype=list)
print(arr)
print(arr.dtype)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
object


In [17]:
# 2D Array :
import numpy as np
arr=np.zeros([4,4],dtype=tuple)
print(arr)
print(arr.dtype)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
object


In [18]:
# 2D Array :
import numpy as np
arr=np.zeros([4,4],dtype=set)
print(arr)
print(arr.dtype)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
object


In [19]:
# 2D Array :
import numpy as np
arr=np.zeros([4,4],dtype=frozenset)
print(arr)
print(arr.dtype)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
object


In [20]:
# 2D Array :
import numpy as np
arr=np.zeros([4,4],dtype=dict)
print(arr)
print(arr.dtype)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
object


In [21]:
# 2D Array :
import numpy as np
arr=np.zeros([4,4],dtype=range)
print(arr)
print(arr.dtype)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
object


##### **order :** It stores the array elements in order inside the memory

In [50]:
# 2D Array :
import numpy as np
arr=np.zeros([4,4],dtype=range,order="C")
print(arr)
print(arr.dtype)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
object


##### **============================================================** 
#### **1.5. np.empty():**
##### **============================================================** 
##### This function create a new array of given shape and type without initializing value.
##### **Syntax:** **np.empty(shape, dtype=None, order='C')**
##### Default data type is float
##### dtype and order is optional
##### It takes the array elemeents from the **Garbage Collection** where it will gives random array elements which are stored in our system storage
##### For 1D Array : np.empty(n) - n=number of elements
##### For 2D Array : np.empty((rows,cols))
##### For 3D Array : np.empty((rows,cols,n))
##### Note : While creating arrays for 2D and 3D array , need to maintain the parentheses compulsory, other wise it will consider as a second arguement
##### For example np.empty(10,20) Here, 10 will consider 1st arguement as n and 20 consider 2nd arguement dtype but it trows as error
##### dtype and order is optional here
##### Note : By default it will take integer only
##### **Parameters:**
##### **shape** - Used for dimension,It gives shape for array to create any(1D,2D,3D) dimension of array.
##### shape(for 1D) - [rows]
##### shape(for 2D) - [rows,cols]
##### shape(for 3D) - [rows,cols,n(elements)]
##### **dtype** - Used to convert the type of data from one data type to another data type
##### **order** - Used to store the array elements in a memory
##### The order="C" parameter defines how the array is stored in memory, specifically using Row-Major Order(Row by Row). 
##### The order="F" parameter defines how the array is stored in memory, specifically using Column-Major Order(Column by Column). 

##### **1D Array :** If we want to create 1 Dimension array just we need to specify the single value to create an array element 
##### we can declare array elements size inside the square brackets[] or paranthesis () or keep as it is

In [56]:
# 1D Array :
import numpy as np
arr = np.empty(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [41]:
# 1D Array :
import numpy as np
arr = np.empty(30)
arr

array([ 1.32467631e-311,  1.01283457e-321,  0.00000000e+000,
        0.00000000e+000,  0.00000000e+000,  1.16097020e-028,
        1.26138597e-076,  2.67489370e-028,  1.68931656e-052,
        1.04917183e-153,  5.23081515e-143,  1.10952247e-047,
        4.50516490e-033,  3.59650889e+175,  1.46339129e-047,
       -7.27444195e-311,  3.59751658e+252,  1.46901661e+179,
        8.37404147e+242,  4.31999013e-096,  4.82337723e+228,
        1.77231619e-051,  2.80055469e-032,  5.64544252e-091,
        4.15919284e-061,  4.12058442e-033,  5.04621343e+180,
        1.94918963e-153,  1.14484251e+243,  2.59903827e-144])

##### **2D Array :** If we want to create 2 Dimension array just we need to specify the row and column values to create an array element 
##### we can declare array elements size inside the square brackets[] or paranthesis () or keep as it is
##### For 2D array must and should pass row and column value is manadatory

In [58]:
# 2D Array :
import numpy as np
arr = np.empty((5,4))
arr

array([[0.0e+000, 4.9e-324, 9.9e-324, 1.5e-323],
       [2.0e-323, 2.5e-323, 3.0e-323, 3.5e-323],
       [4.0e-323, 4.4e-323, 4.9e-323, 5.4e-323],
       [5.9e-323, 6.4e-323, 6.9e-323, 7.4e-323],
       [7.9e-323, 8.4e-323, 8.9e-323, 9.4e-323]])

##### **3D Array :** If we want to create 3 Dimension array just we need to specify the row and column values with number of elements as n to create an array element 
##### we can declare array elements size inside the square brackets[] or paranthesis () or keep as it is
##### For 3D array must and should pass row and column value with number of elements is manadatory

In [57]:
# 3D Array :
import numpy as np
arr = np.empty((3,4,2))
arr

array([[[6.23042070e-307, 3.56043053e-307],
        [1.37961641e-306, 1.05695167e-307],
        [8.01097889e-307, 1.78020169e-306],
        [7.56601165e-307, 1.02359984e-306]],

       [[8.90092016e-307, 1.02361342e-306],
        [6.89804133e-307, 8.90104239e-307],
        [8.90098127e-307, 8.90111708e-307],
        [6.23054633e-307, 8.90111708e-307]],

       [[6.89806849e-307, 8.90104239e-307],
        [1.42417221e-306, 1.95820216e-306],
        [1.37961302e-306, 1.24611674e-306],
        [2.22522596e-306, 2.56765117e-312]]])

##### **dtype :** Used to convert datatype from one type to another type in arrays
##### If we converting float data type to int it just removes decimal point then return array as it is
##### Example : 12.423 -> 12423

In [67]:
# 2D Array :
import numpy as np
arr = np.empty((2,3),dtype=int)
arr

array([[25895968444448860, 30962749956620365, 29555349301231732],
       [27303403461017710, 28429415035764846, 14355657603940466]])

In [50]:
# 1D Array :
import numpy as np
arr = np.empty(4,dtype=int)
print(arr,arr.dtype)
arr = np.empty(4,dtype=float)
print(arr,arr.dtype)
arr = np.empty(4,dtype=complex)
print(arr,arr.dtype)
arr = np.empty(2,dtype=bool)
print(arr,arr.dtype)
arr = np.empty(4,dtype=str)
print(arr,arr.dtype)
arr = np.empty(4,dtype=list)
print(arr,arr.dtype)
arr = np.empty(4,dtype=tuple)
print(arr,arr.dtype)
arr = np.empty(4,dtype=set)
print(arr,arr.dtype)
arr = np.empty(4,dtype=frozenset)
print(arr,arr.dtype)
arr = np.empty(4,dtype=dict)
print(arr,arr.dtype)
arr = np.empty(4,dtype=range)
print(arr,arr.dtype)

[0 0 0 0] int64
[0. 0. 0. 0.] float64
[0.+0.j 0.+0.j 0.+0.j 0.+0.j] complex128
[ True  True] bool
['' '' '' ''] <U1
[None None None None] object
[None None None None] object
[None None None None] object
[None None None None] object
[None None None None] object
[None None None None] object


##### **Note :** empty() returns None Value for all the objects

##### **============================================================** 
#### **1.6. np.linspace():**
##### **============================================================** 
##### This function returns evenly spaced numbers over a specified between two limits. 
##### **Syntax: np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)**
##### return float value as default array elements data type
##### num,endpoint,retstep,dtype and axis is optional here
##### Note : start and stop value is manadatory, that must and should be included in the array creation
##### ****PARAMETERS****
##### start - starting value to create array (start value is inclusive)
##### stop - ending value to create array ( end value is inclusive)
##### num - number of elements to create array by default its 50
##### endpoint - If endpoint is False then
##### retstep: Returns step size if True (default False)
##### dtype: Output array data type
##### axis: Axis for generation when inputs are array-like (default 0)

##### **IMPORTANT POINTS TO BE REMEMBER**
##### start and stop value is manadatory.
##### Here Default num is 50 (num=50) and we can change default value .
##### num,endpoint,retstep,dtype and axis is optional
##### Array elements are always return float value between the start and stop value
##### And always start and stop value is in the form of single float digit (1. --- 21.) because start value is starts with 1. as float value is started

In [2]:
# 1D Array :
import numpy as np
arr = np.linspace(1,21)
arr

array([ 1.        ,  1.40816327,  1.81632653,  2.2244898 ,  2.63265306,
        3.04081633,  3.44897959,  3.85714286,  4.26530612,  4.67346939,
        5.08163265,  5.48979592,  5.89795918,  6.30612245,  6.71428571,
        7.12244898,  7.53061224,  7.93877551,  8.34693878,  8.75510204,
        9.16326531,  9.57142857,  9.97959184, 10.3877551 , 10.79591837,
       11.20408163, 11.6122449 , 12.02040816, 12.42857143, 12.83673469,
       13.24489796, 13.65306122, 14.06122449, 14.46938776, 14.87755102,
       15.28571429, 15.69387755, 16.10204082, 16.51020408, 16.91836735,
       17.32653061, 17.73469388, 18.14285714, 18.55102041, 18.95918367,
       19.36734694, 19.7755102 , 20.18367347, 20.59183673, 21.        ])

##### We can change default num value to num=20 where 20 number of array elements are generated in float data type
##### Its total depend on number of elements (num value), If num is not mentioned by default it will take 50 float array elements........
##### No matter what is start and stop value, it depends on num value only

In [53]:
# 1D Array :
import numpy as np
arr = np.linspace(1,10,num=20)
arr

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

##### If we not mentioned the start value , It will throws an error Because start and stop value is manadatory

In [54]:
# 1D Array :
import numpy as np
arr = np.linspace(21,num=40)
arr

TypeError: linspace() missing 1 required positional argument: 'stop'

##### If we mentioned the start value and stop value , It will execute Because start and stop value is mentioned

In [55]:
# 1D Array :
import numpy as np
arr = np.linspace(1,21,num=40)
arr

array([ 1.        ,  1.51282051,  2.02564103,  2.53846154,  3.05128205,
        3.56410256,  4.07692308,  4.58974359,  5.1025641 ,  5.61538462,
        6.12820513,  6.64102564,  7.15384615,  7.66666667,  8.17948718,
        8.69230769,  9.20512821,  9.71794872, 10.23076923, 10.74358974,
       11.25641026, 11.76923077, 12.28205128, 12.79487179, 13.30769231,
       13.82051282, 14.33333333, 14.84615385, 15.35897436, 15.87179487,
       16.38461538, 16.8974359 , 17.41025641, 17.92307692, 18.43589744,
       18.94871795, 19.46153846, 19.97435897, 20.48717949, 21.        ])

##### We can change default num value to num=20 where 20 number of array elements are generated in float data type
##### **endpoint** : If we set endpoint is **False**  then it will **exculding** the last **stop value**, By default endpoint is True
##### But still it returns the float value only because we are not specified the data type by default it will take float data type

In [56]:
# 1D Array :
import numpy as np
arr = np.linspace(1,21,num=40,endpoint=False)
arr

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5, 11. , 11.5,
       12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. , 16.5, 17. ,
       17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5])

##### We can change default num value to num=20 where 20 number of array elements are generated in float data type
##### **endpoint** : If we set endpoint is **True**  then it will **including** the last **stop value**
##### But still it returns the float value only because we are not specified the data type by default it will take float data type

In [57]:
# 1D Array :
import numpy as np
arr = np.linspace(1,21,num=5,endpoint=True)
arr

array([ 1.,  6., 11., 16., 21.])

##### **retstep** : Menas it returns the difference in value between the array elements ( at end of the array elements it will return retstep(menas difference in the array elements)
##### If retstep is **False** then it will not return retstep value
##### But still it returns the float value only because we are not specified the data type by default it will take float data type

In [63]:
# 1D Array :
import numpy as np
arr = np.linspace(1,21,num=10,endpoint=True,retstep=False)
arr

array([ 1.        ,  3.22222222,  5.44444444,  7.66666667,  9.88888889,
       12.11111111, 14.33333333, 16.55555556, 18.77777778, 21.        ])

##### **retstep** : Menas it returns the difference in value between the array elements ( at end of the array elements it will return retstep(menas difference in the array elements)
##### If **retstep** is **True** then it will return **retstep** value
##### But still it returns the float value only because we are not specified the data type by default it will take float data type
##### If retstep is True then it also return difference in values between the array elements. np.float64(2.2222222222222223))

In [64]:
# 1D Array :
import numpy as np
arr = np.linspace(1,21,num=10,endpoint=True,retstep=True)
arr

(array([ 1.        ,  3.22222222,  5.44444444,  7.66666667,  9.88888889,
        12.11111111, 14.33333333, 16.55555556, 18.77777778, 21.        ]),
 np.float64(2.2222222222222223))

##### **dtype** : If we want to change the data type we need to specify the data type, But the **retstep** is always returns the float value even after changing the data type

In [66]:
# 1D Array :
import numpy as np
arr = np.linspace(1,21,num=10,endpoint=True,retstep=True,dtype=int)
arr

(array([ 1,  3,  5,  7,  9, 12, 14, 16, 18, 21]),
 np.float64(2.2222222222222223))

In [71]:
# 1D Array :
import numpy as np
arr = np.linspace(1,21,num=3,endpoint=True,dtype=int)
print(arr,arr.dtype)
arr = np.linspace(1,21,num=3,endpoint=True,dtype=float)
print(arr,arr.dtype)
arr = np.linspace(1,21,num=3,endpoint=True,dtype=complex)
print(arr,arr.dtype)
arr = np.linspace(1,21,num=3,endpoint=True,dtype=bool)
print(arr,arr.dtype)
arr = np.linspace(1,21,num=3,endpoint=True,dtype=str)
print(arr,arr.dtype)
arr = np.linspace(1,21,num=3,endpoint=True,dtype=list)
print(arr,arr.dtype)
arr = np.linspace(1,21,num=3,endpoint=True,dtype=tuple)
print(arr,arr.dtype)
arr = np.linspace(1,21,num=3,endpoint=True,dtype=set)
print(arr,arr.dtype)
arr = np.linspace(1,21,num=3,endpoint=True,dtype=frozenset)
print(arr,arr.dtype)
arr = np.linspace(1,21,num=5,endpoint=True,dtype=dict)
print(arr,arr.dtype)
arr = np.linspace(1,21,num=3,endpoint=True,dtype=range)
print(arr,arr.dtype)

[ 1 11 21] int64
[ 1. 11. 21.] float64
[ 1.+0.j 11.+0.j 21.+0.j] complex128
[ True  True  True] bool
['1.0' '11.0' '21.0'] <U32
[1.0 11.0 21.0] object
[1.0 11.0 21.0] object
[1.0 11.0 21.0] object
[1.0 11.0 21.0] object
[1.0 6.0 11.0 16.0 21.0] object
[1.0 11.0 21.0] object


##### **axis** : When You are working with multi-dimensional data([1,2,3],[5,4,3]) and we want control over how interpolation is arranged
##### If start and stop values are scalars (numbers), Then axis does NOT matter,It Always gives a 1D array
##### If start and stop values are arrays (vectors), Then axis controls how output is structured
##### axis = 0 (default) → values grow row-wise (downwards) 
##### axis = 1 → values grow column-wise (sideways)
##### For axis = 0 
##### => [ [start]
#####    [middle]
#####     [stop] ]
##### For axis = 1
##### => [ start → middle → stop ]
##### we can't pass more than 2 arrays...... because 1st array takes as start value and 2nd array takes as stop value as an arguement
##### If we pass more than 2 the third array takes num value as an 3rd arguemnet and throws error

##### **For axis=0 :**
##### We need to pass only start and stop value , it will return 1D array as normal linspace() will do same like that
##### Even if we doesn't specify the axis it will take by Default as 0 (axis=0)

In [93]:
# 1D Array :
import numpy as np
arr = np.linspace(1,21,num=10,dtype=int,axis=0)
arr

array([ 1,  3,  5,  7,  9, 12, 14, 16, 18, 21])

##### **For axis=1 :**
##### We need to pass multiple array elements (multi dimensional array) for axis = 1
##### Then it will return output array based on the number of elements(num=10)
##### First it will count the number of elements i.e, num=10
##### then it will takes multi dimensional array elements(both size of array elements should be same or equal)
##### then based on the size of array elements it will gives that many number of rows (as values works column wise)

##### **[row1,col1],[row2,col2]**
##### first row values starts from row1 and stop value col1(start=row1,stop=col1)
##### Second row values starts from row2 and stop value col2(start=row2,stop=col2)

In [98]:
# 2D Array :
import numpy as np
arr = np.linspace([1,2],[5,6],num=10,dtype=int,axis=1)
arr

array([[1, 1, 1, 2, 2, 3, 3, 4, 4, 5],
       [2, 2, 2, 3, 3, 4, 4, 5, 5, 6]])

##### The output array elements are equally generating the values between 1 to 5 in 1st row and 2 to 6 in 2nd row ( for int data type)
##### array([[1, 1, 1, 2, 2, 3, 3, 4, 4, 5],
#####       [2, 2, 2, 3, 3, 4, 4, 5, 5, 6]])

In [104]:
# 2D Array :
import numpy as np
arr = np.linspace([1,2,3],[5,6,7],num=6,axis=1)
arr

array([[1. , 1.8, 2.6, 3.4, 4.2, 5. ],
       [2. , 2.8, 3.6, 4.4, 5.2, 6. ],
       [3. , 3.8, 4.6, 5.4, 6.2, 7. ]])

##### **NOTE(For Axis)**
##### we have two multi dimensional arrays [1,2,3] and [5,6,7] and num=6
##### In each row total 6 elements will generate
##### For First Row : start = 1 & stop = 5 (elements are between 1 to 5)
##### For Second Row : start = 2 & stop = 6 (elements are between 2 to 6)
##### For Third Row : start = 3 & stop = 7 (elements are between 3 to 7)

##### **NOTE** It throws an error if we pass the array unequal size,which that are not equal and we can't pass more than 2 arrays...... because 1st array takes as start and 2nd array takes as stop value in arguement
##### If we pass more than 2 the third array takes num value as an 3rd arguemnet and throws error

In [105]:
# 2D Array :
import numpy as np
arr = np.linspace([1,2,3,4,5],[5,6,7],num=6,axis=1)
arr

ValueError: operands could not be broadcast together with shapes (3,) (5,) 

In [106]:
# 2D Array :
import numpy as np
arr = np.linspace([1,2,3,4,5],[5,6,7,8,9],num=6,axis=1)
arr

array([[1. , 1.8, 2.6, 3.4, 4.2, 5. ],
       [2. , 2.8, 3.6, 4.4, 5.2, 6. ],
       [3. , 3.8, 4.6, 5.4, 6.2, 7. ],
       [4. , 4.8, 5.6, 6.4, 7.2, 8. ],
       [5. , 5.8, 6.6, 7.4, 8.2, 9. ]])

##### When we pass multidimensional arrays as a start and stop value in 1D array,It will return output array element as , It takes start value([1,2]).So the array elements are starting from [1,2] then stop value([5,6]).SO upto the end value it will generate that many number of array elements in the form same as we passed as start and end value

In [111]:
# 1D Array :
import numpy as np
arr = np.linspace([1,2],[5,6],num=6,axis=0)
arr

array([[1. , 2. ],
       [1.8, 2.8],
       [2.6, 3.6],
       [3.4, 4.4],
       [4.2, 5.2],
       [5. , 6. ]])

##### **============================================================** 
##### **1.7. np.formiter():**
##### **============================================================** 
##### The fromiter() function create a new one-dimensional array from an iterable object.
##### **Syntax: np.fromiter(iterable, dtype, count=-1)**
##### count is optional here
##### **Parameter :**
##### **iterable** - The Object which are iterable
##### **dtype** - Data type to conver one type to another type
##### **count** - Number of items to read.

##### **Note:**
##### Only Iterable Objects are used to create an array elemenets
##### It will not support int,float and complex datat type
##### iterable object and data type must and should be declare,its manadatory to create array, So that interpretar can understand which datatype we are passing for iterable objects
##### for string data type we need to take "U1" as an data type

In [8]:
import numpy as np
var = "Hello World"
arr = np.fromiter(var,dtype="U1")
print("fromiter() array :",arr)

fromiter() array : ['H' 'e' 'l' 'l' 'o' ' ' 'W' 'o' 'r' 'l' 'd']


In [9]:
import numpy as np
var = "Hello World"
arr = np.fromiter(var,dtype=str)
print("fromiter() array :",arr)

ValueError: Must specify length when using variable-size data-type.

In [10]:
import numpy as np
var = 123456
arr = np.fromiter(var,dtype=int)
print("fromiter() array :",arr)

TypeError: 'int' object is not iterable

##### We can pass the iterable objects only such as : str , list , tuple, set,dict, range, frozenset also
##### It works with list, tuple,set,range and dict and string aswell frozenset also ..

In [33]:
import numpy as np
var = "Basavanagudi" #string
arr = np.fromiter(var,dtype="U1")
print("fromiter() String array :",arr)
arr = np.fromiter(var,dtype=list)
print("fromiter() List array :",arr)
arr = np.fromiter(var,dtype=tuple)
print("fromiter() Tuple array :",arr)
arr = np.fromiter(var,dtype=set)
print("fromiter() Set array :",arr)
arr = np.fromiter(var,dtype=frozenset)
print("fromiter() Frozenset array :",arr)
arr = np.fromiter(var,dtype=dict)
print("fromiter() Dict array :",arr)
arr = np.fromiter(var,dtype=range)
print("fromiter() Range array :",arr)
arr = np.fromiter(var,dtype=bool)
print("fromiter() Boolean array :",arr)

fromiter() String array : ['B' 'a' 's' 'a' 'v' 'a' 'n' 'a' 'g' 'u' 'd' 'i']
fromiter() List array : ['B' 'a' 's' 'a' 'v' 'a' 'n' 'a' 'g' 'u' 'd' 'i']
fromiter() Tuple array : ['B' 'a' 's' 'a' 'v' 'a' 'n' 'a' 'g' 'u' 'd' 'i']
fromiter() Set array : ['B' 'a' 's' 'a' 'v' 'a' 'n' 'a' 'g' 'u' 'd' 'i']
fromiter() Frozenset array : ['B' 'a' 's' 'a' 'v' 'a' 'n' 'a' 'g' 'u' 'd' 'i']
fromiter() Dict array : ['B' 'a' 's' 'a' 'v' 'a' 'n' 'a' 'g' 'u' 'd' 'i']
fromiter() Range array : ['B' 'a' 's' 'a' 'v' 'a' 'n' 'a' 'g' 'u' 'd' 'i']
fromiter() Boolean array : [ True  True  True  True  True  True  True  True  True  True  True  True]


In [22]:
import numpy as np
var = [1,2,3,4,5] #list
arr = np.fromiter(var,dtype="U1")
print("fromiter() String array :",arr)
arr = np.fromiter(var,dtype=list)
print("fromiter() List array :",arr)
arr = np.fromiter(var,dtype=tuple)
print("fromiter() Tuple array :",arr)
arr = np.fromiter(var,dtype=set)
print("fromiter() Set array :",arr)
arr = np.fromiter(var,dtype=frozenset)
print("fromiter() Frozenset array :",arr)
arr = np.fromiter(var,dtype=dict)
print("fromiter() Dict array :",arr)
arr = np.fromiter(var,dtype=range)
print("fromiter() Range array :",arr)
arr = np.fromiter(var,dtype=bool)
print("fromiter() Boolean array :",arr)

fromiter() String array : ['1' '2' '3' '4' '5']
fromiter() List array : [1 2 3 4 5]
fromiter() Tuple array : [1 2 3 4 5]
fromiter() Set array : [1 2 3 4 5]
fromiter() Frozenset array : [1 2 3 4 5]
fromiter() Dict array : [1 2 3 4 5]
fromiter() Range array : [1 2 3 4 5]
fromiter() Boolean array : [ True  True  True  True  True]


In [27]:
import numpy as np
var = {1,2,3,4,5,6} #set
arr = np.fromiter(var,dtype="U1")
print("fromiter() String array :",arr)
arr = np.fromiter(var,dtype=list)
print("fromiter() List array :",arr)
arr = np.fromiter(var,dtype=tuple)
print("fromiter() Tuple array :",arr)
arr = np.fromiter(var,dtype=set)
print("fromiter() Set array :",arr)
arr = np.fromiter(var,dtype=frozenset)
print("fromiter() Frozenset array :",arr)
arr = np.fromiter(var,dtype=dict)
print("fromiter() Dict array :",arr)
arr = np.fromiter(var,dtype=range)
print("fromiter() Range array :",arr)
arr = np.fromiter(var,dtype=bool)
print("fromiter() Boolean array :",arr)

fromiter() String array : ['1' '2' '3' '4' '5' '6']
fromiter() List array : [1 2 3 4 5 6]
fromiter() Tuple array : [1 2 3 4 5 6]
fromiter() Set array : [1 2 3 4 5 6]
fromiter() Frozenset array : [1 2 3 4 5 6]
fromiter() Dict array : [1 2 3 4 5 6]
fromiter() Range array : [1 2 3 4 5 6]
fromiter() Boolean array : [ True  True  True  True  True  True]


In [26]:
import numpy as np
var = (1,2,3,4,5,6) #tuple
arr = np.fromiter(var,dtype="U1")
print("fromiter() String array :",arr)
arr = np.fromiter(var,dtype=list)
print("fromiter() List array :",arr)
arr = np.fromiter(var,dtype=tuple)
print("fromiter() Tuple array :",arr)
arr = np.fromiter(var,dtype=set)
print("fromiter() Set array :",arr)
arr = np.fromiter(var,dtype=frozenset)
print("fromiter() Frozenset array :",arr)
arr = np.fromiter(var,dtype=dict)
print("fromiter() Dict array :",arr)
arr = np.fromiter(var,dtype=range)
print("fromiter() Range array :",arr)
arr = np.fromiter(var,dtype=bool)
print("fromiter() Boolean array :",arr)

fromiter() String array : ['1' '2' '3' '4' '5' '6']
fromiter() List array : [1 2 3 4 5 6]
fromiter() Tuple array : [1 2 3 4 5 6]
fromiter() Set array : [1 2 3 4 5 6]
fromiter() Frozenset array : [1 2 3 4 5 6]
fromiter() Dict array : [1 2 3 4 5 6]
fromiter() Range array : [1 2 3 4 5 6]
fromiter() Boolean array : [ True  True  True  True  True  True]


In [28]:
import numpy as np
var = {1:2,3:4,5:6} #dictionary
arr = np.fromiter(var,dtype="U1")
print("fromiter() String array :",arr)
arr = np.fromiter(var,dtype=list)
print("fromiter() List array :",arr)
arr = np.fromiter(var,dtype=tuple)
print("fromiter() Tuple array :",arr)
arr = np.fromiter(var,dtype=set)
print("fromiter() Set array :",arr)
arr = np.fromiter(var,dtype=frozenset)
print("fromiter() Frozenset array :",arr)
arr = np.fromiter(var,dtype=dict)
print("fromiter() Dict array :",arr)
arr = np.fromiter(var,dtype=range)
print("fromiter() Range array :",arr)
arr = np.fromiter(var,dtype=bool)
print("fromiter() Boolean array :",arr)

fromiter() String array : ['1' '3' '5']
fromiter() List array : [1 3 5]
fromiter() Tuple array : [1 3 5]
fromiter() Set array : [1 3 5]
fromiter() Frozenset array : [1 3 5]
fromiter() Dict array : [1 3 5]
fromiter() Range array : [1 3 5]
fromiter() Boolean array : [ True  True  True]


In [32]:
import numpy as np
var = {'A':2,'B':4,'C':6} #dict
arr = np.fromiter(var,dtype="U1")
print("fromiter() String array :",arr)
arr = np.fromiter(var,dtype=list)
print("fromiter() List array :",arr)
arr = np.fromiter(var,dtype=tuple)
print("fromiter() Tuple array :",arr)
arr = np.fromiter(var,dtype=set)
print("fromiter() Set array :",arr)
arr = np.fromiter(var,dtype=frozenset)
print("fromiter() Frozenset array :",arr)
arr = np.fromiter(var,dtype=dict)
print("fromiter() Dict array :",arr)
arr = np.fromiter(var,dtype=range)
print("fromiter() Range array :",arr)
arr = np.fromiter(var,dtype=bool)
print("fromiter() Boolean array :",arr)

fromiter() String array : ['A' 'B' 'C']
fromiter() List array : ['A' 'B' 'C']
fromiter() Tuple array : ['A' 'B' 'C']
fromiter() Set array : ['A' 'B' 'C']
fromiter() Frozenset array : ['A' 'B' 'C']
fromiter() Dict array : ['A' 'B' 'C']
fromiter() Range array : ['A' 'B' 'C']
fromiter() Boolean array : [ True  True  True]


In [31]:
import numpy as np
var = range(1,10) # range
arr = np.fromiter(var,dtype="U1")
print("fromiter() String array :",arr)
arr = np.fromiter(var,dtype=list)
print("fromiter() List array :",arr)
arr = np.fromiter(var,dtype=tuple)
print("fromiter() Tuple array :",arr)
arr = np.fromiter(var,dtype=set)
print("fromiter() Set array :",arr)
arr = np.fromiter(var,dtype=frozenset)
print("fromiter() Frozenset array :",arr)
arr = np.fromiter(var,dtype=dict)
print("fromiter() Dict array :",arr)
arr = np.fromiter(var,dtype=range)
print("fromiter() Range array :",arr)
arr = np.fromiter(var,dtype=bool)
print("fromiter() Boolean array :",arr)

fromiter() String array : ['1' '2' '3' '4' '5' '6' '7' '8' '9']
fromiter() List array : [1 2 3 4 5 6 7 8 9]
fromiter() Tuple array : [1 2 3 4 5 6 7 8 9]
fromiter() Set array : [1 2 3 4 5 6 7 8 9]
fromiter() Frozenset array : [1 2 3 4 5 6 7 8 9]
fromiter() Dict array : [1 2 3 4 5 6 7 8 9]
fromiter() Range array : [1 2 3 4 5 6 7 8 9]
fromiter() Boolean array : [ True  True  True  True  True  True  True  True  True]


In [36]:
import numpy as np
var = [True,False] #Boolean
arr = np.fromiter(var,dtype="U1")
print("fromiter() String array :",arr)
arr = np.fromiter(var,dtype=list)
print("fromiter() List array :",arr)
arr = np.fromiter(var,dtype=tuple)
print("fromiter() Tuple array :",arr)
arr = np.fromiter(var,dtype=set)
print("fromiter() Set array :",arr)
arr = np.fromiter(var,dtype=frozenset)
print("fromiter() Frozenset array :",arr)
arr = np.fromiter(var,dtype=dict)
print("fromiter() Dict array :",arr)
arr = np.fromiter(var,dtype=range)
print("fromiter() Range array :",arr)
arr = np.fromiter(var,dtype=bool)
print("fromiter() Boolean array :",arr)

fromiter() String array : ['T' 'F']
fromiter() List array : [True False]
fromiter() Tuple array : [True False]
fromiter() Set array : [True False]
fromiter() Frozenset array : [True False]
fromiter() Dict array : [True False]
fromiter() Range array : [True False]
fromiter() Boolean array : [ True False]


In [2]:
import numpy as np
var = frozenset({1,2,3,4,5,6}) #frozenset
arr = np.fromiter(var,dtype="U1")
print("fromiter() String array :",arr)
arr = np.fromiter(var,dtype=list)
print("fromiter() List array :",arr)
arr = np.fromiter(var,dtype=tuple)
print("fromiter() Tuple array :",arr)
arr = np.fromiter(var,dtype=set)
print("fromiter() Set array :",arr)
arr = np.fromiter(var,dtype=frozenset)
print("fromiter() Frozenset array :",arr)
arr = np.fromiter(var,dtype=dict)
print("fromiter() Dict array :",arr)
arr = np.fromiter(var,dtype=range)
print("fromiter() Range array :",arr)
arr = np.fromiter(var,dtype=bool)
print("fromiter() Boolean array :",arr)

fromiter() String array : ['1' '2' '3' '4' '5' '6']
fromiter() List array : [1 2 3 4 5 6]
fromiter() Tuple array : [1 2 3 4 5 6]
fromiter() Set array : [1 2 3 4 5 6]
fromiter() Frozenset array : [1 2 3 4 5 6]
fromiter() Dict array : [1 2 3 4 5 6]
fromiter() Range array : [1 2 3 4 5 6]
fromiter() Boolean array : [ True  True  True  True  True  True]


##### **count** : It is an optional, If we want to access particular count of elements only then we can make use of count to access number of array elements from the arrays 

In [4]:
import numpy as np
arr = np.fromiter([1,2,3,4,5,6],dtype=int)
arr

array([1, 2, 3, 4, 5, 6])

In [6]:
import numpy as np
arr = np.fromiter([1,2,3,4,5,6],dtype=int,count=3)
arr

array([1, 2, 3])

##### If we pass, count more than that the array elements , it will raise an error

In [7]:
import numpy as np
arr = np.fromiter([1,2,3,4,5,6],dtype=int,count=7)
arr

ValueError: iterator too short: Expected 7 but iterator had only 6 items.

##### **============================================================** 
#### **1.8 np.full() :** 
##### **============================================================** 
##### It fills the entire array with specific value based on shape and specific value
##### **syntax: np.full(shape, fill_value, dtype=None, order='C')**
##### Pass the desired shape and fill value.
##### datatype and order is optional here
##### Its manadatory to pass shape of array and specific value to fill the entire array
##### **Parameters:**
##### shape (tuple of int): Shape of the new array (1D/2D/3D).
##### For 1D - np.full(n)
##### For 2D - np.full(rows,cols)
##### FOr 3D - np.full(rows,cols,n)
##### fill_value (scalar): The constant value to fill the entire array with that specific value.
##### dtype : data type of the array.
##### order ({'C', 'F'} : Stroing array elements in an memory

##### **1-Dimensional Array :**  We can give any type of value such as (int , float , complex , bool , str , set )

In [13]:
# 1D Array - Integer type Value
import numpy as np
arr = np.full((4),5)
arr

array([5, 5, 5, 5])

In [14]:
# 1D Array - Float type Value
import numpy as np
arr = np.full((4),3.2)
arr

array([3.2, 3.2, 3.2, 3.2])

In [15]:
# 1D Array - Complex type Value
import numpy as np
arr = np.full((4),5+7j)
arr

array([5.+7.j, 5.+7.j, 5.+7.j, 5.+7.j])

In [16]:
# 1D Array - Boolena type Value
import numpy as np
arr = np.full((4),True)
arr

array([ True,  True,  True,  True])

In [17]:
# 1D Array - String type Value
import numpy as np
arr = np.full((4),"PySpider")
arr

array(['PySpider', 'PySpider', 'PySpider', 'PySpider'], dtype='<U8')

##### **Note** : We can't pass multivalue data type(list,range and frozenset,some time tuple(when more than 2 values))  as a specific value

In [20]:
# 1D Array - List type Value
import numpy as np
arr = np.full((4),[1,2])
arr

ValueError: could not broadcast input array from shape (2,) into shape (4,)

##### **Note:** Here we can pass tuple data type but It accepts single tuple value only,If we pass more than 1 tuple value it raises an error

In [23]:
# 1D Array - Tuple type Value
import numpy as np
arr = np.full((4),(1,))
arr

array([1, 1, 1, 1])

In [24]:
# 1D Array - Tuple type Value
import numpy as np
arr = np.full((4),(1,2))
arr

ValueError: could not broadcast input array from shape (2,) into shape (4,)

In [27]:
# 1D Array - Set type Value
import numpy as np
arr = np.full((4),{8})
arr

array([{8}, {8}, {8}, {8}], dtype=object)

In [28]:
# 1D Array - Set type Value
import numpy as np
arr = np.full((4),{8,20,13})
arr

array([{8, 20, 13}, {8, 20, 13}, {8, 20, 13}, {8, 20, 13}], dtype=object)

##### It Will not works with frozenset

In [33]:
# 1D Array - Frozseset type Value
import numpy as np
arr = np.full((4),frozenset{5})
arr

SyntaxError: invalid syntax. Perhaps you forgot a comma? (614656580.py, line 3)

##### It Will not works with range

In [34]:
# 1D Array - Range type Value
import numpy as np
arr = np.full((4),range(5))
arr

ValueError: could not broadcast input array from shape (5,) into shape (4,)

In [36]:
# 1D Array - Dictionary type Value
import numpy as np
arr = np.full((4),{5:3})
arr

array([{5: 3}, {5: 3}, {5: 3}, {5: 3}], dtype=object)

##### **2-Dimensional Array:**

In [5]:
import numpy as np
arr = np.full((4,5),5)
arr

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

##### **3-Dimensional Array:**

In [9]:
import numpy as np
arr = np.full((3,2,2),5)
arr

array([[[5, 5],
        [5, 5]],

       [[5, 5],
        [5, 5]],

       [[5, 5],
        [5, 5]]])

##### **dtype** : Convert one data type to another data type : While converting float to int , the floating decimal values will be removed (no roundup and rouddown)

##### **Int to Other Data Type Conversion**

In [52]:
import numpy as np
arr = np.full((4,5),5,dtype=int)
print(arr,arr.dtype)
print()
arr = np.full((4,5),5,dtype=complex)
print(arr,arr.dtype)
print()
arr = np.full((4,5),5,dtype=bool)
print(arr,arr.dtype)
print()
arr = np.full((4,5),5,dtype=str)
print(arr,arr.dtype)
print()
arr = np.full((4,5),5,dtype=list)
print(arr,arr.dtype)
print()
arr = np.full((4,5),5,dtype=tuple)
print(arr,arr.dtype)
print()
arr = np.full((4,5),5,dtype=float)
print(arr,arr.dtype)
print()
arr = np.full((4,5),5,dtype=set)
print(arr,arr.dtype)
print()
arr = np.full((4,5),5,dtype=frozenset)
print(arr,arr.dtype)
print()
arr = np.full((4,5),5,dtype=dict)
print(arr,arr.dtype)
print()
arr = np.full((4,5),5,dtype=range)
print(arr,arr.dtype)
print()

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]] int64

[[5.+0.j 5.+0.j 5.+0.j 5.+0.j 5.+0.j]
 [5.+0.j 5.+0.j 5.+0.j 5.+0.j 5.+0.j]
 [5.+0.j 5.+0.j 5.+0.j 5.+0.j 5.+0.j]
 [5.+0.j 5.+0.j 5.+0.j 5.+0.j 5.+0.j]] complex128

[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]] bool

[['5' '5' '5' '5' '5']
 ['5' '5' '5' '5' '5']
 ['5' '5' '5' '5' '5']
 ['5' '5' '5' '5' '5']] <U1

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]] object

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]] object

[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]] float64

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]] object

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]] object

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]] object

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]] object



##### **Float to Other Data Type Conversion**

In [51]:
import numpy as np
arr = np.full((4,5),5.7090,dtype=int)
print(arr,arr.dtype)
print()
arr = np.full((4,5),5.7090,dtype=complex)
print(arr,arr.dtype)
print()
arr = np.full((4,5),5.7090,dtype=bool)
print(arr,arr.dtype)
print()
arr = np.full((4,5),5.7090,dtype=str)
print(arr,arr.dtype)
print()
arr = np.full((4,5),5.7090,dtype=list)
print(arr,arr.dtype)
print()
arr = np.full((4,5),5.7090,dtype=tuple)
print(arr,arr.dtype)
print()
arr = np.full((4,5),5.7090,dtype=float)
print(arr,arr.dtype)
print()
arr = np.full((4,5),5.7090,dtype=set)
print(arr,arr.dtype)
print()
arr = np.full((4,5),5.7090,dtype=frozenset)
print(arr,arr.dtype)
print()
arr = np.full((4,5),5.7090,dtype=dict)
print(arr,arr.dtype)
print()
arr = np.full((4,5),5.7090,dtype=range)
print(arr,arr.dtype)
print()

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]] int64

[[5.709+0.j 5.709+0.j 5.709+0.j 5.709+0.j 5.709+0.j]
 [5.709+0.j 5.709+0.j 5.709+0.j 5.709+0.j 5.709+0.j]
 [5.709+0.j 5.709+0.j 5.709+0.j 5.709+0.j 5.709+0.j]
 [5.709+0.j 5.709+0.j 5.709+0.j 5.709+0.j 5.709+0.j]] complex128

[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]] bool

[['5' '5' '5' '5' '5']
 ['5' '5' '5' '5' '5']
 ['5' '5' '5' '5' '5']
 ['5' '5' '5' '5' '5']] <U1

[[5.709 5.709 5.709 5.709 5.709]
 [5.709 5.709 5.709 5.709 5.709]
 [5.709 5.709 5.709 5.709 5.709]
 [5.709 5.709 5.709 5.709 5.709]] object

[[5.709 5.709 5.709 5.709 5.709]
 [5.709 5.709 5.709 5.709 5.709]
 [5.709 5.709 5.709 5.709 5.709]
 [5.709 5.709 5.709 5.709 5.709]] object

[[5.709 5.709 5.709 5.709 5.709]
 [5.709 5.709 5.709 5.709 5.709]
 [5.709 5.709 5.709 5.709 5.709]
 [5.709 5.709 5.709 5.709 5.709]] float64

[[5.709 5.709 5.709 5.709 5.709]
 [5.709 5.709 5.709 5

##### **Complex to Other Data Type Conversion**

In [54]:
import numpy as np
arr = np.full((4,5),5+9j,dtype=int)
print(arr,arr.dtype)
print()
arr = np.full((4,5),5+9j,dtype=complex)
print(arr,arr.dtype)
print()
arr = np.full((4,5),5+9j,dtype=bool)
print(arr,arr.dtype)
print()
arr = np.full((4,5),5+9j,dtype=str)
print(arr,arr.dtype)
print()
arr = np.full((4,5),5+9j,dtype=list)
print(arr,arr.dtype)
print()
arr = np.full((4,5),5+9j,dtype=tuple)
print(arr,arr.dtype)
print()
arr = np.full((4,5),5+9j,dtype=float)
print(arr,arr.dtype)
print()
arr = np.full((4,5),5+9j,dtype=set)
print(arr,arr.dtype)
print()
arr = np.full((4,5),5+9j,dtype=frozenset)
print(arr,arr.dtype)
print()
arr = np.full((4,5),5+9j,dtype=dict)
print(arr,arr.dtype)
print()
# Complex to Range data type is not possible

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]] int64

[[5.+9.j 5.+9.j 5.+9.j 5.+9.j 5.+9.j]
 [5.+9.j 5.+9.j 5.+9.j 5.+9.j 5.+9.j]
 [5.+9.j 5.+9.j 5.+9.j 5.+9.j 5.+9.j]
 [5.+9.j 5.+9.j 5.+9.j 5.+9.j 5.+9.j]] complex128

[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]] bool

[['(' '(' '(' '(' '(']
 ['(' '(' '(' '(' '(']
 ['(' '(' '(' '(' '(']
 ['(' '(' '(' '(' '(']] <U1

[[(5+9j) (5+9j) (5+9j) (5+9j) (5+9j)]
 [(5+9j) (5+9j) (5+9j) (5+9j) (5+9j)]
 [(5+9j) (5+9j) (5+9j) (5+9j) (5+9j)]
 [(5+9j) (5+9j) (5+9j) (5+9j) (5+9j)]] object

[[(5+9j) (5+9j) (5+9j) (5+9j) (5+9j)]
 [(5+9j) (5+9j) (5+9j) (5+9j) (5+9j)]
 [(5+9j) (5+9j) (5+9j) (5+9j) (5+9j)]
 [(5+9j) (5+9j) (5+9j) (5+9j) (5+9j)]] object

[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]] float64

[[(5+9j) (5+9j) (5+9j) (5+9j) (5+9j)]
 [(5+9j) (5+9j) (5+9j) (5+9j) (5+9j)]
 [(5+9j) (5+9j) (5+9j) (5+9j) (5+9j)]
 [(5+9j) (5+9j) (5+9

##### **String to Other Data Type Conversion**

In [57]:
import numpy as np
## Int and Float and Complex Not possible
arr = np.full((2,3),"QSPider",dtype=bool)
print(arr,arr.dtype)
print()
arr = np.full((2,3),"QSPider",dtype=str)
print(arr,arr.dtype)
print()
arr = np.full((2,3),"QSPider",dtype=list)
print(arr,arr.dtype)
print()
arr = np.full((2,3),"QSPider",dtype=tuple)
print(arr,arr.dtype)
print()
arr = np.full((2,3),"QSPider",dtype=set)
print(arr,arr.dtype)
print()
arr = np.full((2,3),"QSPider",dtype=frozenset)
print(arr,arr.dtype)
print()
arr = np.full((2,3),"QSPider",dtype=dict)
print(arr,arr.dtype)
print()
arr = np.full((2,3),"QSPider",dtype=range)
print(arr,arr.dtype)
print()

[[ True  True  True]
 [ True  True  True]] bool

[['Q' 'Q' 'Q']
 ['Q' 'Q' 'Q']] <U1

[['QSPider' 'QSPider' 'QSPider']
 ['QSPider' 'QSPider' 'QSPider']] object

[['QSPider' 'QSPider' 'QSPider']
 ['QSPider' 'QSPider' 'QSPider']] object

[['QSPider' 'QSPider' 'QSPider']
 ['QSPider' 'QSPider' 'QSPider']] object

[['QSPider' 'QSPider' 'QSPider']
 ['QSPider' 'QSPider' 'QSPider']] object

[['QSPider' 'QSPider' 'QSPider']
 ['QSPider' 'QSPider' 'QSPider']] object

[['QSPider' 'QSPider' 'QSPider']
 ['QSPider' 'QSPider' 'QSPider']] object



In [58]:
import numpy as np
arr = np.full((2,3),"123",dtype=int)
print(arr,arr.dtype)
print()
arr = np.full((2,3),"123",dtype=complex)
print(arr,arr.dtype)
print()
arr = np.full((2,3),"123",dtype=bool)
print(arr,arr.dtype)
print()
arr = np.full((2,3),"123",dtype=str)
print(arr,arr.dtype)
print()
arr = np.full((2,3),"123",dtype=list)
print(arr,arr.dtype)
print()
arr = np.full((2,3),"123",dtype=tuple)
print(arr,arr.dtype)
print()
arr = np.full((2,3),"123",dtype=float)
print(arr,arr.dtype)
print()
arr = np.full((2,3),"123",dtype=set)
print(arr,arr.dtype)
print()
arr = np.full((2,3),"123",dtype=frozenset)
print(arr,arr.dtype)
print()
arr = np.full((2,3),"123",dtype=dict)
print(arr,arr.dtype)
print()
arr = np.full((2,3),"123",dtype=range)
print(arr,arr.dtype)
print()

[[123 123 123]
 [123 123 123]] int64

[[123.+0.j 123.+0.j 123.+0.j]
 [123.+0.j 123.+0.j 123.+0.j]] complex128

[[ True  True  True]
 [ True  True  True]] bool

[['1' '1' '1']
 ['1' '1' '1']] <U1

[['123' '123' '123']
 ['123' '123' '123']] object

[['123' '123' '123']
 ['123' '123' '123']] object

[[123. 123. 123.]
 [123. 123. 123.]] float64

[['123' '123' '123']
 ['123' '123' '123']] object

[['123' '123' '123']
 ['123' '123' '123']] object

[['123' '123' '123']
 ['123' '123' '123']] object

[['123' '123' '123']
 ['123' '123' '123']] object



##### **Boolean to Other Data Type Conversion**

In [60]:
import numpy as np
# Int , float and complex not possible
arr = np.full((2,3),True,dtype=bool)
print(arr,arr.dtype)
print()
arr = np.full((2,3),False,dtype=str)
print(arr,arr.dtype)
print()
arr = np.full((2,3),False,dtype=list)
print(arr,arr.dtype)
print()
arr = np.full((2,3),True,dtype=tuple)
print(arr,arr.dtype)
print()
arr = np.full((2,3),True,dtype=set)
print(arr,arr.dtype)
print()
arr = np.full((2,3),True,dtype=frozenset)
print(arr,arr.dtype)
print()
arr = np.full((2,3),True,dtype=dict)
print(arr,arr.dtype)
print()
arr = np.full((2,3),True,dtype=range)
print(arr,arr.dtype)
print()

[[ True  True  True]
 [ True  True  True]] bool

[['F' 'F' 'F']
 ['F' 'F' 'F']] <U1

[[False False False]
 [False False False]] object

[[True True True]
 [True True True]] object

[[True True True]
 [True True True]] object

[[True True True]
 [True True True]] object

[[True True True]
 [True True True]] object

[[True True True]
 [True True True]] object



##### **List to Other Data Type Conversion** : Not Possible

##### **Tuple to Other Data Type Conversion** : Possible only for single value tuple data

##### **Set to Other Data Type Conversion**

In [62]:
import numpy as np
# Int , float and complex not possible
arr = np.full((2,3),{"QSPider",123},dtype=bool)
print(arr,arr.dtype)
print()
arr = np.full((2,3),{"QSPider",123},dtype=str)
print(arr,arr.dtype)
print()
arr = np.full((2,3),{"QSPider",123},dtype=list)
print(arr,arr.dtype)
print()
arr = np.full((2,3),{"QSPider",123},dtype=tuple)
print(arr,arr.dtype)
print()
arr = np.full((2,3),{"QSPider",123},dtype=set)
print(arr,arr.dtype)
print()
arr = np.full((2,3),{"QSPider",123},dtype=frozenset)
print(arr,arr.dtype)
print()
arr = np.full((2,3),{"QSPider",123},dtype=dict)
print(arr,arr.dtype)
print()
arr = np.full((2,3),{"QSPider",123},dtype=range)
print(arr,arr.dtype)
print()

[[ True  True  True]
 [ True  True  True]] bool

[['{' '{' '{']
 ['{' '{' '{']] <U1

[[{123, 'QSPider'} {123, 'QSPider'} {123, 'QSPider'}]
 [{123, 'QSPider'} {123, 'QSPider'} {123, 'QSPider'}]] object

[[{123, 'QSPider'} {123, 'QSPider'} {123, 'QSPider'}]
 [{123, 'QSPider'} {123, 'QSPider'} {123, 'QSPider'}]] object

[[{123, 'QSPider'} {123, 'QSPider'} {123, 'QSPider'}]
 [{123, 'QSPider'} {123, 'QSPider'} {123, 'QSPider'}]] object

[[{123, 'QSPider'} {123, 'QSPider'} {123, 'QSPider'}]
 [{123, 'QSPider'} {123, 'QSPider'} {123, 'QSPider'}]] object

[[{123, 'QSPider'} {123, 'QSPider'} {123, 'QSPider'}]
 [{123, 'QSPider'} {123, 'QSPider'} {123, 'QSPider'}]] object

[[{123, 'QSPider'} {123, 'QSPider'} {123, 'QSPider'}]
 [{123, 'QSPider'} {123, 'QSPider'} {123, 'QSPider'}]] object



##### **Frozenset to Other Data Type Conversion** : not Possible

##### **Range to Other Data Type Conversion** : Not Possible

##### **Dict to Other Data Type Conversion**

In [63]:
import numpy as np
# Int , float and complex not possible
arr = np.full((2,3),{"QSPider":123},dtype=bool)
print(arr,arr.dtype)
print()
arr = np.full((2,3),{"QSPider":123},dtype=str)
print(arr,arr.dtype)
print()
arr = np.full((2,3),{"QSPider":123},dtype=list)
print(arr,arr.dtype)
print()
arr = np.full((2,3),{"QSPider":123},dtype=tuple)
print(arr,arr.dtype)
print()
arr = np.full((2,3),{"QSPider":123},dtype=set)
print(arr,arr.dtype)
print()
arr = np.full((2,3),{"QSPider":123},dtype=frozenset)
print(arr,arr.dtype)
print()
arr = np.full((2,3),{"QSPider":123},dtype=dict)
print(arr,arr.dtype)
print()
arr = np.full((2,3),{"QSPider":123},dtype=range)
print(arr,arr.dtype)
print()

[[ True  True  True]
 [ True  True  True]] bool

[['{' '{' '{']
 ['{' '{' '{']] <U1

[[{'QSPider': 123} {'QSPider': 123} {'QSPider': 123}]
 [{'QSPider': 123} {'QSPider': 123} {'QSPider': 123}]] object

[[{'QSPider': 123} {'QSPider': 123} {'QSPider': 123}]
 [{'QSPider': 123} {'QSPider': 123} {'QSPider': 123}]] object

[[{'QSPider': 123} {'QSPider': 123} {'QSPider': 123}]
 [{'QSPider': 123} {'QSPider': 123} {'QSPider': 123}]] object

[[{'QSPider': 123} {'QSPider': 123} {'QSPider': 123}]
 [{'QSPider': 123} {'QSPider': 123} {'QSPider': 123}]] object

[[{'QSPider': 123} {'QSPider': 123} {'QSPider': 123}]
 [{'QSPider': 123} {'QSPider': 123} {'QSPider': 123}]] object

[[{'QSPider': 123} {'QSPider': 123} {'QSPider': 123}]
 [{'QSPider': 123} {'QSPider': 123} {'QSPider': 123}]] object



##### **order** : used to store array elements in a memory

In [64]:
arr = np.full((2,3),1,dtype=float,order="C")
print(arr,arr.dtype)
print()

[[1. 1. 1.]
 [1. 1. 1.]] float64



##### **============================================================** 
#### **1.9 np.empty() :** 
##### **============================================================** 
##### It creates a new array with old existing values from our main memory(Garbage Memory).
##### **Syntax : np.empty(shape, dtype=None, order='C')**
##### It generating the garbage values from main memory.
##### datatype(returns float data type) and order is optional here 
##### Its manadatory to pass shape of array and specific shape value to create the entire array
##### **Parameters:**
##### shape (tuple of int): Shape of the new array (1D/2D/3D).
##### For 1D - np.empty(n)
##### For 2D - np.empty(rows,cols)
##### FOr 3D - np.empty(rows,cols,n)
##### dtype : data type of the array.
##### order ({'C', 'F'} : Stroing array elements in an memory

##### **1-Dimensional Array :** We Need to pass number of elements

In [9]:
import numpy as np
arr = np.empty(4)
arr

array([6.23042070e-307, 4.67296746e-307, 1.69121096e-306, 9.34609111e-307])

##### **2-Dimensional Array :** We Need to pass number of rows and columns

In [10]:
import numpy as np
arr = np.empty((3,4))
arr

array([[1.28489503e-311, 2.47032823e-322, 0.00000000e+000,
        0.00000000e+000],
       [1.78020168e-306, 6.82116729e-043, 6.25886937e-091,
        4.91127535e-062],
       [5.41557685e-067, 8.60991320e-043, 3.99910963e+252,
        8.34443015e-308]])

##### **3-Dimensional Array :** We Need to pass number of rows and columns with elements

In [12]:
import numpy as np
arr = np.empty((2,2,3))
arr

array([[[1.28489503e-311, 2.47032823e-322, 0.00000000e+000],
        [0.00000000e+000, 1.78020168e-306, 6.82116729e-043]],

       [[6.25886937e-091, 4.91127535e-062, 5.41557685e-067],
        [8.60991320e-043, 3.99910963e+252, 8.34443015e-308]]])

##### **1-Dimensional with dtype :**

In [19]:
import numpy as np
arr = np.empty(4,dtype=int)
print(arr,arr.dtype)
arr = np.empty(4,dtype=float)
print(arr,arr.dtype)
arr = np.empty(4,dtype=complex)
print(arr,arr.dtype)
arr = np.empty(4,dtype=bool)
print(arr,arr.dtype)
arr = np.empty(4,dtype=str)
print(arr,arr.dtype)
arr = np.empty(4,dtype=list)
print(arr,arr.dtype)
arr = np.empty(4,dtype=tuple)
print(arr,arr.dtype)
arr = np.empty(4,dtype=set)
print(arr,arr.dtype)
arr = np.empty(4,dtype=frozenset)
print(arr,arr.dtype)
arr = np.empty(4,dtype=dict)
print(arr,arr.dtype)
arr = np.empty(4,dtype=range)
print(arr,arr.dtype)

[0 0 0 0] int64
[0. 0. 0. 0.] float64
[1.28489620e-311+1.77863633e-322j 1.42413554e-306+1.42134691e+161j
 3.88586220e-033+6.51175403e-091j 4.50653790e-033+4.67431346e-315j] complex128
[ True  True  True  True] bool
['' '' '' ''] <U1
[None None None None] object
[None None None None] object
[None None None None] object
[None None None None] object
[None None None None] object
[None None None None] object


##### **order** : used to store array elements in a memory

In [22]:
arr = np.empty((2,3),dtype=int,order="C")
print(arr,arr.dtype)

[[25895968444448860 23925768161198147 32370111954616435]
 [28429466574585948 31525476570497138 32651513914720368]] int64


##### **============================================================** 
#### **1.10 np.identity() :** 
##### **============================================================** 
##### It generates identity matrix by default and It performs n*n matrix operation
##### **Syntax : np.identity(n , dtype=None)**
##### dtype is optional here, Default data type as float.
##### Diagonal elements are all **1's** only and non diagonal elements are **0's**
##### **Parameter:**
##### n - It takes int value and is Dimension n x n of output array
##### dtype : data type of the array.

In [26]:
import numpy as np 
arr = np.identity(4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [30]:
import numpy as np 
arr = np.identity(4,dtype=int)
print(arr,arr.dtype)
arr = np.identity(4,dtype=float)
print(arr,arr.dtype)
arr = np.identity(4,dtype=complex)
print(arr,arr.dtype)
arr = np.identity(4,dtype=bool)
print(arr,arr.dtype)
arr = np.identity(4,dtype=str)
print(arr,arr.dtype)
arr = np.identity(4,dtype=list)
print(arr,arr.dtype)
arr = np.identity(4,dtype=tuple)
print(arr,arr.dtype)
arr = np.identity(4,dtype=set)
print(arr,arr.dtype)
arr = np.identity(4,dtype=frozenset)
print(arr,arr.dtype)
arr = np.identity(4,dtype=dict)
print(arr,arr.dtype)
arr = np.identity(4,dtype=range)
print(arr,arr.dtype)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]] int64
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] float64
[[1.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 1.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 1.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 1.+0.j]] complex128
[[ True False False False]
 [False  True False False]
 [False False  True False]
 [False False False  True]] bool
[['1' '' '' '']
 ['' '1' '' '']
 ['' '' '1' '']
 ['' '' '' '1']] <U1
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]] object
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]] object
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]] object
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]] object
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]] object
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]] object
