# **Numpy(Numerical Python) Library :**

### **1.Array with Constant :**

##### **1.Array with Constant :** Create a values of array and that array values can be performed with constant value to the entire array

In [4]:
import numpy as np
arr = np.random.randint(1,10,5)
print(arr)

[8 6 4 8 4]


##### The entire array will be adding to the one constant value

In [15]:
arr+1

array([9, 7, 5, 9, 5], dtype=int32)

##### Substraction

In [16]:
arr-1

array([7, 5, 3, 7, 3], dtype=int32)

##### Multiplication

In [17]:
arr*2

array([16, 12,  8, 16,  8], dtype=int32)

##### True Division

In [18]:
arr/2

array([4., 3., 2., 4., 2.])

##### Floor Division

In [19]:
arr//2

array([4, 3, 2, 4, 2], dtype=int32)

##### Moduls

In [20]:
arr%10

array([8, 6, 4, 8, 4], dtype=int32)

##### Power

In [21]:
arr**2

array([64, 36, 16, 64, 16], dtype=int32)

##### The ^ operator performs bitwise XOR, not exponentiation.

In [22]:
arr^2 

array([10,  4,  6, 10,  6], dtype=int32)

### 2. Array with Array
##### **2.Array with Array :** Create a values of array and that array values can be performed with another array values to the entire array from one another, Array size in both array must be same

In [23]:
import numpy as np
arr1 = np.random.randint(1,10,5)
arr2 = np.random.randint(1,10,5)
print(arr1)
print(arr2)
a1=np.array([1,2,3])
a2=np.array([2,3])
a1+a2

[5 5 2 9 6]
[4 6 5 6 2]


ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [24]:
arr1+arr2

array([ 9, 11,  7, 15,  8], dtype=int32)

In [25]:
arr1-arr2

array([ 1, -1, -3,  3,  4], dtype=int32)

In [26]:
arr1*arr2

array([20, 30, 10, 54, 12], dtype=int32)

In [27]:
arr1/arr2

array([1.25      , 0.83333333, 0.4       , 1.5       , 3.        ])

In [28]:
arr1//arr2

array([1, 0, 0, 1, 3], dtype=int32)

In [29]:
arr1**arr2

array([   625,  15625,     32, 531441,     36], dtype=int32)

In [30]:
arr1%arr2

array([1, 5, 2, 3, 0], dtype=int32)

In [31]:
arr1^arr2

array([ 1,  3,  7, 15,  4], dtype=int32)

### 3.Array with Built-in Methods
##### **3.Array with Built-in Methods :** Create a values of array and that array values can be performed with built in methods

##### **3.1 Sort() :** it sorts the array elements

In [33]:
import numpy as np
arr = np.random.randint(1,10,5)
print(arr)
print(np.sort(arr))

[4 2 4 8 7]
[2 4 4 7 8]


##### **3.2 argsort() :** it will returns the sorted indexs of array elements

In [34]:
arr = np.random.randint(1,10,5)
print(arr)
print(np.argsort(arr))

[2 2 3 3 4]
[0 1 2 3 4]


##### **3.3 min() :** Minimum array value will be returned

In [39]:
arr = np.random.randint(1,10,5)
print(arr)
print(np.min(arr))

[9 8 4 4 9]
4


##### **3.4 argmin() :** Minimum array values index will be returned

In [40]:
arr = np.random.randint(1,10,5)
print(arr)
print(np.argmin(arr))

[4 3 6 5 5]
1


##### **3.5 max() :** Maximum array value will be returned

In [41]:
arr = np.random.randint(1,10,5)
print(arr)
print(np.max(arr))

[9 2 8 8 6]
9


##### **3.6 argmax() :** Maximum array values index will be returned

In [43]:
arr = np.random.randint(1,10,5)
print(arr)
print(np.argmax(arr))

[8 6 6 6 9]
4


##### **3.7 sum() :** Sum of array value will be returned, Entire arrays sum will be returned

In [44]:
arr = np.random.randint(1,10,5)
print(arr)
print(np.sum(arr))

[6 2 6 8 9]
31


##### **3.8 average() :** Average of array value will be returned, Entire arrays average will be returned

In [52]:
arr = np.random.randint(1,10,5)
print(arr)
print(np.average(arr))

[9 4 5 9 1]
5.6


##### **3.9 mean() :** Mean of array value will be returned, Entire arrays mean will be returned
##### **Formula : Mean=Σx/n**
##### where:
##### Σx = Sum of all values
##### n = Number of values

In [53]:
arr = np.random.randint(1,10,5)
print(arr)
print(np.mean(arr))

[2 4 8 7 2]
4.6


##### **3.10 median() :** Median of array value will be returned, Entire arrays median will be returned
##### **Formula : Median=((n+1)/2)th value**
##### Middle value after sorting

In [67]:
arr = np.random.randint(1,10,5)
print(arr)
print(np.median(arr)) #Sorted array ka middle value , If even → average of two middle values

[4 5 2 1 4]
4.0


##### **3.11 sqrt() :** it will returns the square of the each elements.

In [62]:
arr = np.random.randint(1,10,5)
print(arr)
print(np.sqrt(arr)) 

[9 8 8 6 2]
[3.         2.82842712 2.82842712 2.44948974 1.41421356]


##### **3.12 var() :** Variance of array value will be returned, Entire arrays variance will be returned
##### **Formula :** variance=∑(x−μ)2​/N
##### where:
##### x = value
##### μ = mean
##### N = number of observations

In [64]:
arr = np.random.randint(1,10,5) #Variance=n∑(x−mean)^2/total numbers
print(arr)
print(np.var(arr)) # mean=2.8 => (0.64+4.84+0.04+3.24+0.04)/5=1.76

[2 5 3 1 3]
1.7600000000000002


##### **3.13 std() :** Standard of array value will be returned, Entire arrays Standar will be returned
##### **Formula :** σ=sqrt(σ2)

In [71]:
arr = np.random.randint(1,10,5)
print(arr)
print(np.mean(arr))
print(np.var(arr)) 
print(np.std(arr)) #sqrt(var)

[6 4 3 4 9]
5.2
4.5600000000000005
2.1354156504062622


##### **mode() :** method will not support
##### Most frequently occurring value. **Formula :** Mode=Value with highest frequency

In [63]:
arr = np.random.randint(1,10,5)
print(arr)
print(np.mode(arr)) 

[5 9 5 8 4]


AttributeError: module 'numpy' has no attribute 'mode'

##### **3.14 prod() :** Product of array value will be returned, Entire arrays Product will be returned

In [59]:
arr = np.random.randint(1,10,5)
print(arr)
print(np.prod(arr)) 

[4 8 4 8 3]
3072


In [44]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


##### **axis=0** column wise product, Works only with 2D and more than 2D array

In [45]:
np.prod(arr, axis=0)

array([ 4, 10, 18])

##### **axis=1** row wise product

In [46]:
np.prod(arr, axis=1)

array([  6, 120])

##### **3.15 dot() :** Product of two array value will be returned, Entire two arrays product will be returned.
##### Why dot() Has No axis? Because dot() combines two arrays according to matrix multiplication rules.

In [35]:
arr = np.random.randint(1,10,5)
print(arr)
print(np.dot(arr)) 

[7 2 5 4 3]


TypeError: dot() missing 1 required positional argument: 'b'

##### **1D Array**

In [42]:
arr1 = np.random.randint(1,10,5)
arr2 = np.random.randint(1,10,5)
print(arr1)
print(arr2)
print(np.dot(arr1,arr2)) 

[2 6 9 1 3]
[5 4 5 9 3]
97


##### **2D Array**

In [43]:
a = np.array([[1,2],
              [3,4]])
b = np.array([[5,6],
              [7,8]])
np.dot(a,b)

array([[19, 22],
       [43, 50]])

##### dot() is different. It performs matrix multiplication (dot product), not row-wise/column-wise aggregation.np.dot() does not have an axis parameter.

In [39]:
arr1 = np.random.randint(1,10,5)
arr2 = np.random.randint(1,10,5)
print(arr1)
print(arr2)
print(np.dot(arr1,arr2),axis=0) 

[8 4 4 6 7]
[6 2 2 2 8]


TypeError: print() got an unexpected keyword argument 'axis'

| Feature | `np.prod()`                  | `np.dot()`                          |
| ------- | ---------------------------- | ----------------------------------- |
| Purpose | Product of all elements      | Dot Product / Matrix Multiplication |
| Inputs  | One array                    | Two arrays                          |
| Formula | a×b×c×d                      | a₁b₁+a₂b₂+a₃b₃                      |
| Output  | Single multiplication result | Sum of element-wise products        |
| Used In | Statistics                   | Linear Algebra, ML, AI              |

##### **Sum with axis=0** : **Row wise operation Column wise output**, correct works with only 2D and more than 2D array

##### **1D array**

In [48]:
arr = np.random.randint(1,10,5)
print(arr)
print(np.sum(arr,axis=0))

[3 5 1 5 4]
18


##### **2D array**

In [49]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr)
print(np.sum(arr,axis=0))

[[1 2 3]
 [4 5 6]]
[5 7 9]


##### **Sum with axis=1 :** **Column wise operation Row wise output**, correct works with only 2D and more than 2D array¶

##### **1D Array**

In [48]:
arr = np.random.randint(1,10,5)
print(arr)
print(np.sum(arr,axis=1))

[3 2 2 8 5]


AxisError: axis 1 is out of bounds for array of dimension 1

##### **2D Array**

In [51]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr)
print(np.sum(arr,axis=1))

[[1 2 3]
 [4 5 6]]
[ 6 15]


##### **Sum with axis=0 (multiple array):** **Row wise operation Column wise output**

##### **1D Array**

In [52]:
arr1 = np.random.randint(1,10,5)
arr2 = np.random.randint(1,10,5)
print(arr1)
print(arr2)
print(np.sum((arr1,arr2),axis=0))

[1 8 4 4 2]
[6 3 6 8 3]
[ 7 11 10 12  5]


##### **2D Array**

In [55]:
arr1 = np.array([[1,2,3],
                [4,5,6]])
arr2 = np.array([[5,6,1],
                [7,4,2]])
print(arr1,'\n',arr2)
print(np.sum((arr1,arr2),axis=0))

[[1 2 3]
 [4 5 6]] 
 [[5 6 1]
 [7 4 2]]
[[ 6  8  4]
 [11  9  8]]


##### **Sum with axis=1 (multiple array):** **Column wise operation Row wise output**

##### **1D Array**

In [53]:
print(arr1)
print(arr2)
print(np.sum((arr1,arr2),axis=1))

[1 8 4 4 2]
[6 3 6 8 3]
[19 26]


##### **2D Array**

In [56]:
arr1 = np.array([[1,2,3],
                [4,5,6]])
arr2 = np.array([[5,6,1],
                [7,4,2]])
print(arr1,'\n',arr2)
print(np.sum((arr1,arr2),axis=1))

[[1 2 3]
 [4 5 6]] 
 [[5 6 1]
 [7 4 2]]
[[ 5  7  9]
 [12 10  3]]


##### **min() with two arrays (axis=0)**

##### **1D Array**

In [59]:
arr1 = np.random.randint(1,10,5)
arr2 = np.random.randint(1,10,5)
print(arr1)
print(arr2)
print(np.min((arr1,arr2),axis=0))

[8 5 8 1 5]
[9 2 6 9 4]
[8 2 6 1 4]


##### **2D Array**

In [90]:
arr1 = np.random.randint(1,10,(2,3))
arr2 = np.random.randint(1,10,(2,3))
print(arr1)
print(arr2)
print(np.min((arr1,arr2),axis=0))

[[4 4 6]
 [9 4 9]]
[[8 6 1]
 [9 1 9]]
[[4 4 1]
 [9 1 9]]


##### **min() with two arrays (axis=1)**

##### **1D Array**

In [75]:
arr1 = np.random.randint(1,10,5)
arr2 = np.random.randint(1,10,5)
print(arr1)
print(arr2)
print(np.min((arr1,arr2),axis=1))

[8 6 4 6 7]
[7 2 1 5 1]
[4 1]


##### **2D Array**

In [91]:
arr1 = np.random.randint(1,10,(2,3))
arr2 = np.random.randint(1,10,(2,3))
print(arr1)
print(arr2)
print(np.min((arr1,arr2),axis=1))

[[7 5 9]
 [4 2 5]]
[[6 5 1]
 [7 1 6]]
[[4 2 5]
 [6 1 1]]


##### **argmin() with two arrays (axis=0)**

##### **1D Array**

In [62]:
arr1 = np.random.randint(1,10,5)
arr2 = np.random.randint(1,10,5)
print(arr1)
print(arr2)
print(np.argmin((arr1,arr2),axis=0))

[2 1 1 5 2]
[6 5 6 2 8]
[0 0 0 1 0]


##### **2D Array**

In [92]:
arr1 = np.random.randint(1,10,(2,3))
arr2 = np.random.randint(1,10,(2,3))
print(arr1)
print(arr2)
print(np.min((arr1,arr2),axis=0))

[[7 1 8]
 [3 2 9]]
[[7 1 8]
 [7 4 9]]
[[7 1 8]
 [3 2 9]]


##### **argmin() with two arrays (axis=1)**

##### **1D Array**

In [95]:
arr1 = np.random.randint(1,10,5)
arr2 = np.random.randint(1,10,5)
print(arr1)
print(arr2)
print(np.argmin((arr1,arr2),axis=1))

[8 4 7 3 3]
[9 3 5 4 1]
[3 4]


##### **2D Array**

In [105]:
arr1 = np.random.randint(1,10,(2,3))
arr2 = np.random.randint(1,10,(2,3))
print(arr1)
print(arr2)
print(np.argmin((arr1,arr2),axis=1))

[[2 9 7]
 [8 3 1]]
[[9 6 2]
 [7 3 7]]
[[0 1 1]
 [1 1 0]]


##### **max() with two arrays (axis=0)**

##### **1D Array**

In [63]:
arr1 = np.random.randint(1,10,5)
arr2 = np.random.randint(1,10,5)
print(arr1)
print(arr2)
print(np.max((arr1,arr2),axis=0))

[8 9 1 2 1]
[4 3 5 5 2]
[8 9 5 5 2]


##### **2D Array**

In [106]:
arr1 = np.random.randint(1,10,(2,3))
arr2 = np.random.randint(1,10,(2,3))
print(arr1)
print(arr2)
print(np.max((arr1,arr2),axis=0))

[[5 1 5]
 [1 6 7]]
[[1 4 1]
 [2 7 5]]
[[5 4 5]
 [2 7 7]]


##### **max() with two arrays (axis=1)**

##### **1D Array**

In [77]:
arr1 = np.random.randint(1,10,5)
arr2 = np.random.randint(1,10,5)
print(arr1)
print(arr2)
print(np.max((arr1,arr2),axis=1))

[3 4 3 7 3]
[1 3 7 3 4]
[7 7]


##### **2D Array**

In [107]:
arr1 = np.random.randint(1,10,(2,3))
arr2 = np.random.randint(1,10,(2,3))
print(arr1)
print(arr2)
print(np.max((arr1,arr2),axis=1))

[[7 9 1]
 [6 9 2]]
[[4 1 9]
 [2 7 3]]
[[7 9 2]
 [4 7 9]]


##### **argmax() with two arrays (axis=0)**

##### **1D Array**

In [61]:
arr1 = np.random.randint(1,10,5)
arr2 = np.random.randint(1,10,5)
print(arr1)
print(arr2)
print(np.argmax((arr1,arr2),axis=0))

[6 9 9 3 1]
[7 5 8 4 6]
[1 0 0 1 1]


##### **2D Array**

In [108]:
arr1 = np.random.randint(1,10,(2,3))
arr2 = np.random.randint(1,10,(2,3))
print(arr1)
print(arr2)
print(np.min((arr1,arr2),axis=0))

[[5 2 5]
 [8 1 3]]
[[7 4 1]
 [3 8 2]]
[[5 2 1]
 [3 1 2]]


##### **argmax() with two arrays (axis=1)**

##### **1D Array**

In [78]:
arr1 = np.random.randint(1,10,5)
arr2 = np.random.randint(1,10,5)
print(arr1)
print(arr2)
print(np.argmax((arr1,arr2),axis=1))

[8 2 2 2 2]
[8 3 9 4 9]
[0 2]


##### **2D Array**

In [109]:
arr1 = np.random.randint(1,10,(2,3))
arr2 = np.random.randint(1,10,(2,3))
print(arr1)
print(arr2)
print(np.argmax((arr1,arr2),axis=1))

[[8 3 7]
 [4 9 3]]
[[7 9 3]
 [8 4 5]]
[[0 1 0]
 [1 0 1]]


##### **average() with two arrays (axis=0)**

##### **1D Array**

In [64]:
arr1 = np.random.randint(1,10,5)
arr2 = np.random.randint(1,10,5)
print(arr1)
print(arr2)
print(np.average((arr1,arr2),axis=0))

[5 1 5 1 3]
[2 8 7 6 4]
[3.5 4.5 6.  3.5 3.5]


##### **2D Array**

In [110]:
arr1 = np.random.randint(1,10,(2,3))
arr2 = np.random.randint(1,10,(2,3))
print(arr1)
print(arr2)
print(np.average((arr1,arr2),axis=0))

[[1 3 8]
 [3 9 8]]
[[3 8 4]
 [1 2 2]]
[[2.  5.5 6. ]
 [2.  5.5 5. ]]


##### **average() with two arrays (axis=1)**

##### **1D Array**

In [79]:
arr1 = np.random.randint(1,10,5)
arr2 = np.random.randint(1,10,5)
print(arr1)
print(arr2)
print(np.average((arr1,arr2),axis=1))

[1 9 6 3 1]
[2 9 5 6 7]
[4.  5.8]


##### **2D Array**

In [111]:
arr1 = np.random.randint(1,10,(2,3))
arr2 = np.random.randint(1,10,(2,3))
print(arr1)
print(arr2)
print(np.average((arr1,arr2),axis=1))

[[4 8 8]
 [7 3 3]]
[[1 2 8]
 [6 5 1]]
[[5.5 5.5 5.5]
 [3.5 3.5 4.5]]


##### **sort() with two arrays (axis=0)**

##### **1D Array**

In [68]:
arr1 = np.random.randint(1,10,5)
arr2 = np.random.randint(1,10,5)
print(arr1)
print(arr2)
print(np.sort((arr1,arr2),axis=0))

[7 3 3 1 9]
[3 2 8 6 1]
[[3 2 3 1 1]
 [7 3 8 6 9]]


##### **2D Array**

In [112]:
arr1 = np.random.randint(1,10,(2,3))
arr2 = np.random.randint(1,10,(2,3))
print(arr1)
print(arr2)
print(np.sort((arr1,arr2),axis=0))

[[4 2 1]
 [9 3 9]]
[[4 9 3]
 [2 6 7]]
[[[4 2 1]
  [2 3 7]]

 [[4 9 3]
  [9 6 9]]]


##### **sort() with two arrays (axis=1)**

##### **1D Array**

In [80]:
arr1 = np.random.randint(1,10,5)
arr2 = np.random.randint(1,10,5)
print(arr1)
print(arr2)
print(np.sort((arr1,arr2),axis=1))

[2 7 5 1 7]
[9 5 5 5 5]
[[1 2 5 7 7]
 [5 5 5 5 9]]


##### **2D Array**

In [113]:
arr1 = np.random.randint(1,10,(2,3))
arr2 = np.random.randint(1,10,(2,3))
print(arr1)
print(arr2)
print(np.sort((arr1,arr2),axis=1))

[[3 6 4]
 [8 7 6]]
[[8 4 9]
 [3 9 8]]
[[[3 6 4]
  [8 7 6]]

 [[3 4 8]
  [8 9 9]]]


##### **argsort() with two arrays (axis=0)**

##### **1D Array**

In [69]:
arr1 = np.random.randint(1,10,5)
arr2 = np.random.randint(1,10,5)
print(arr1)
print(arr2)
print(np.argsort((arr1,arr2),axis=0))

[2 8 1 3 5]
[2 4 7 9 3]
[[0 1 0 0 1]
 [1 0 1 1 0]]


##### **2D Array**

In [114]:
arr1 = np.random.randint(1,10,(2,3))
arr2 = np.random.randint(1,10,(2,3))
print(arr1)
print(arr2)
print(np.argsort((arr1,arr2),axis=0))

[[8 6 7]
 [8 5 7]]
[[5 9 3]
 [6 5 7]]
[[[1 0 1]
  [1 0 0]]

 [[0 1 0]
  [0 1 1]]]


##### **argsort() with two arrays (axis=1)**

##### **1D Array**

In [81]:
arr1 = np.random.randint(1,10,5)
arr2 = np.random.randint(1,10,5)
print(arr1)
print(arr2)
print(np.argsort((arr1,arr2),axis=1))

[2 9 3 5 3]
[6 9 6 2 2]
[[0 2 4 3 1]
 [3 4 2 0 1]]


##### **2D Array**

In [115]:
arr1 = np.random.randint(1,10,(2,3))
arr2 = np.random.randint(1,10,(2,3))
print(arr1)
print(arr2)
print(np.argsort((arr1,arr2),axis=1))

[[3 7 4]
 [9 6 6]]
[[7 3 2]
 [7 5 8]]
[[[0 1 0]
  [1 0 1]]

 [[0 0 0]
  [1 1 1]]]


##### **mean() with two arrays (axis=0)**

##### **1D Array**

In [70]:
arr1 = np.random.randint(1,10,5)
arr2 = np.random.randint(1,10,5)
print(arr1)
print(arr2)
print(np.mean((arr1,arr2),axis=0))

[5 7 9 7 2]
[8 8 2 3 5]
[6.5 7.5 5.5 5.  3.5]


##### **2D Array**

In [116]:
arr1 = np.random.randint(1,10,(2,3))
arr2 = np.random.randint(1,10,(2,3))
print(arr1)
print(arr2)
print(np.mean((arr1,arr2),axis=0))

[[9 7 5]
 [1 9 5]]
[[2 3 9]
 [1 9 1]]
[[5.5 5.  7. ]
 [1.  9.  3. ]]


##### **mean() with two arrays (axis=1)**

##### **1D Array**

In [82]:
arr1 = np.random.randint(1,10,5)
arr2 = np.random.randint(1,10,5)
print(arr1)
print(arr2)
print(np.mean((arr1,arr2),axis=1))

[4 5 4 4 5]
[8 9 4 9 1]
[4.4 6.2]


##### **2D Array**

In [117]:
arr1 = np.random.randint(1,10,(2,3))
arr2 = np.random.randint(1,10,(2,3))
print(arr1)
print(arr2)
print(np.mean((arr1,arr2),axis=1))

[[1 8 5]
 [5 4 4]]
[[4 6 7]
 [3 3 7]]
[[3.  6.  4.5]
 [3.5 4.5 7. ]]


##### **median() with two arrays (axis=0)**

##### **1D Array**

In [71]:
arr1 = np.random.randint(1,10,5)
arr2 = np.random.randint(1,10,5)
print(arr1)
print(arr2)
print(np.median((arr1,arr2),axis=0))

[8 5 6 7 3]
[4 7 2 2 7]
[6.  6.  4.  4.5 5. ]


##### **2D Array**

In [118]:
arr1 = np.random.randint(1,10,(2,3))
arr2 = np.random.randint(1,10,(2,3))
print(arr1)
print(arr2)
print(np.median((arr1,arr2),axis=0))

[[8 8 3]
 [9 1 8]]
[[9 5 5]
 [8 2 9]]
[[8.5 6.5 4. ]
 [8.5 1.5 8.5]]


##### **median() with two arrays (axis=1)**

##### **1D Array**

In [83]:
arr1 = np.random.randint(1,10,5)
arr2 = np.random.randint(1,10,5)
print(arr1)
print(arr2)
print(np.median((arr1,arr2),axis=1))

[6 4 9 4 6]
[6 2 5 3 3]
[6. 3.]


##### **2D Array**

In [119]:
arr1 = np.random.randint(1,10,(2,3))
arr2 = np.random.randint(1,10,(2,3))
print(arr1)
print(arr2)
print(np.median((arr1,arr2),axis=1))

[[9 7 2]
 [2 2 6]]
[[2 6 9]
 [5 3 9]]
[[5.5 4.5 4. ]
 [3.5 4.5 9. ]]


##### **sqrt() with two arrays (axis=0)**

##### **1D Array**

In [84]:
arr1 = np.random.randint(1,10,5)
arr2 = np.random.randint(1,10,5)
print(arr1)
print(arr2)
print(np.sqrt((arr1,arr2),axis=0))

[8 3 1 3 6]
[3 4 4 4 9]


TypeError: sqrt() got an unexpected keyword argument 'axis'

##### **2D Array**

In [120]:
arr1 = np.random.randint(1,10,(2,3))
arr2 = np.random.randint(1,10,(2,3))
print(arr1)
print(arr2)
print(np.sqrt((arr1,arr2),axis=0))

[[9 6 9]
 [2 5 2]]
[[6 3 7]
 [1 6 9]]


TypeError: sqrt() got an unexpected keyword argument 'axis'

##### **var() with two arrays (axis=0)**

##### **1D Array**

In [73]:
arr1 = np.random.randint(1,10,5)
arr2 = np.random.randint(1,10,5)
print(arr1)
print(arr2)
print(np.var((arr1,arr2),axis=0))

[9 9 7 4 2]
[7 5 9 8 8]
[1. 4. 1. 4. 9.]


##### **2D Array**

In [121]:
arr1 = np.random.randint(1,10,(2,3))
arr2 = np.random.randint(1,10,(2,3))
print(arr1)
print(arr2)
print(np.var((arr1,arr2),axis=0))

[[5 5 7]
 [2 6 7]]
[[1 6 8]
 [3 6 6]]
[[4.   0.25 0.25]
 [0.25 0.   0.25]]


##### **var() with two arrays (axis=1)**

##### **1D Array**

In [85]:
arr1 = np.random.randint(1,10,5)
arr2 = np.random.randint(1,10,5)
print(arr1)
print(arr2)
print(np.var((arr1,arr2),axis=1))

[9 3 8 8 3]
[2 2 7 9 6]
[6.96 7.76]


##### **2D Array**

In [122]:
arr1 = np.random.randint(1,10,(2,3))
arr2 = np.random.randint(1,10,(2,3))
print(arr1)
print(arr2)
print(np.var((arr1,arr2),axis=1))

[[5 2 4]
 [1 9 6]]
[[8 6 1]
 [9 8 3]]
[[ 4.   12.25  1.  ]
 [ 0.25  1.    1.  ]]


##### **std() with two arrays (axis=0)**

##### **1D Array**

In [74]:
arr1 = np.random.randint(1,10,5)
arr2 = np.random.randint(1,10,5)
print(arr1)
print(arr2)
print(np.std((arr1,arr2),axis=0))

[8 7 1 3 6]
[6 4 1 9 4]
[1.  1.5 0.  3.  1. ]


##### **2D Array**

In [123]:
arr1 = np.random.randint(1,10,(2,3))
arr2 = np.random.randint(1,10,(2,3))
print(arr1)
print(arr2)
print(np.std((arr1,arr2),axis=0))

[[1 4 2]
 [3 5 9]]
[[2 6 2]
 [3 2 3]]
[[0.5 1.  0. ]
 [0.  1.5 3. ]]


##### **std() with two arrays (axis=1)**

##### **1D Array**

In [86]:
arr1 = np.random.randint(1,10,5)
arr2 = np.random.randint(1,10,5)
print(arr1)
print(arr2)
print(np.std((arr1,arr2),axis=1))

[2 8 2 8 2]
[3 5 8 2 1]
[2.93938769 2.48193473]


##### **2D Array**

In [124]:
arr1 = np.random.randint(1,10,(2,3))
arr2 = np.random.randint(1,10,(2,3))
print(arr1)
print(arr2)
print(np.std((arr1,arr2),axis=1))

[[2 1 8]
 [2 9 4]]
[[3 4 6]
 [7 5 6]]
[[0.  4.  2. ]
 [2.  0.5 0. ]]
