# **Numpy(Numerical Python) Library :**

### **1.Properties Of Numpy Arrays :**
#### **1.1 dtype**
#### **1.2 ndim or Rank**
#### **1.3 shape**
#### **1.4 reshape**
#### **1.5 size**
#### **1.6 itemsize**
#### **1.7 flatten()**
#### **1.8 ravel()**

##### **============================================================** 
#### **1.1 dtype :** 
##### **============================================================** 
##### It returns the data type of array variable
##### **Syntax : array_variable.dtype**

##### First We need to create an array by using any one array creation method
##### Then check the array data type

##### We can create an array by manually or we can generate the array elements by using array creation methods
##### **1.Creating NumPy Arrays :**
##### 1.1 np.array()
##### 1.2 np.arange()
##### 1.3 np.ones()
##### 1.4 np.zeros()
##### 1.5 np.eye()
##### 1.6 np.linspace()
##### 1.7 np.fromIter()
##### 1.8 np.full()
##### 1.9 np.empty()
##### 1.10 np.identity()

In [39]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr, arr.dtype)
arr = np.array([1.4,2.8,9.3,4.0,5])
print(arr, arr.dtype)
arr = np.array([1+2j,2+9j,3,4,5])
print(arr, arr.dtype)
arr = np.array([1,2,3,4,5])
print(arr, arr.dtype)
arr = np.array((1,2,3,4,5))
print(arr, arr.dtype)
arr = np.array({1,2,3,4,5})
print(arr, arr.dtype)
arr = np.array(['Hello',1,2,3])
print(arr, arr.dtype)
arr = np.array({2:3,4:5})
print(arr, arr.dtype)

[1 2 3 4 5] int64
[1.4 2.8 9.3 4.  5. ] float64
[1.+2.j 2.+9.j 3.+0.j 4.+0.j 5.+0.j] complex128
[1 2 3 4 5] int64
[1 2 3 4 5] int64
{1, 2, 3, 4, 5} object
['Hello' '1' '2' '3'] <U21
{2: 3, 4: 5} object


##### **Note:** When we pass array elements explicitly, We can pass any type of collection(multivalue data type or single value data type with multiple elements) 
##### But for list, tuple and range data type it returns the data type based on the collection of elements(int,float,complex,bool,string) 
##### If array elements are in different  data types then based on the priority order it will conver the array and returns the dtype

##### **Note:** In this list we have passed string elements only , hence it doesn't care about order of priority

In [36]:
import numpy as np
arr = np.array(['Hello',"hi",'Bye'])
print(arr, arr.dtype)

['Hello' 'hi' 'Bye'] <U5


##### **Note:** In this list we have passed int aswell as float elements only , hence it take care about order of priority

In [38]:
import numpy as np
arr = np.array([1,3.4,3,4,5])
print(arr, arr.dtype)

[1.  3.4 3.  4.  5. ] float64


##### **Note:** In this list we have passed array elements explicitily.

In [33]:
a=list([1,2,3,4])
arr = np.array(a)
print(arr, arr.dtype)

[1 2 3 4] int64


In [23]:
a=tuple((1,2,3,4))
arr = np.array(a)
print(arr, arr.dtype)

[1 2 3 4] int64


In [30]:
a=tuple((1.0,9.7,4.5))
arr = np.array(a)
print(arr, arr.dtype)

[1.  9.7 4.5] float64


In [23]:
a=tuple((1,2,3,4))
arr = np.array(a)
print(arr, arr.dtype)

[1 2 3 4] int64


In [25]:
a=complex(1+2j,9+7j)
arr = np.array(a)
print(arr, arr.dtype)

(-6+11j) complex128


In [27]:
a=bool(True)
arr = np.array(a)
print(arr, arr.dtype)

True bool


In [22]:
a=set({1,2,3,4})
arr = np.array(a)
print(arr, arr.dtype)

{1, 2, 3, 4} object


In [19]:
a=frozenset({1,2,3,4})
arr = np.array(a)
print(arr, arr.dtype)

frozenset({1, 2, 3, 4}) object


In [20]:
a=range(10)
arr = np.array(a)
print(arr, arr.dtype)

[0 1 2 3 4 5 6 7 8 9] int64


In [21]:
a=dict({1:2,3:4})
arr = np.array(a)
print(arr, arr.dtype)

{1: 2, 3: 4} object


##### **============================================================** 
#### **1.2 ndim :** 
##### **============================================================** 
##### It returns the dimension of an array (1D/2D/3D)
##### **Syntax : array_variable.ndim**

##### First We need to create an array by using any one array creation method
##### Then check the dimensional of array

##### **1-Dimensional Array :**

In [41]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr)
print(arr.ndim)

[1 2 3 4 5 6 7]
1


##### **2-Dimensional Array :**

In [44]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6,]])
print(arr)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
2


##### **3-Dimensional Array :**

In [45]:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[1,1,1],[4,2,3]]])
print(arr)
print(arr.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 1 1]
  [4 2 3]]]
3


##### **Note :** While Creating an array, the number of array elements(rows,cols,elements) should be same

##### **============================================================** 
#### **1.3 shape :** 
##### **============================================================** 
##### It returns the shape of the given array variable. It returns number of elements for 1D array
##### **Syntax : array_variable.shape**
##### First We need to create an array by using any one array creation method
##### Then check the array shape

##### **1-Dimensional Array :** Shape Property returns the number of elements only in the tuple form only
##### Return Output : (number_of_elements,)

In [46]:
import numpy as np
arr = np.array([1,2,3,5,7,9])
print(arr)
print(arr.shape)

[1 2 3 5 7 9]
(6,)


##### **2-Dimensional Array :** Shape Property returns the number of rows and columns only in the tuple form only
##### Return Output : (number_of_rows,number_of_columns)

In [47]:
import numpy as np
arr = np.array([[1,2,3],[5,7,9]])
print(arr)
print(arr.shape)

[[1 2 3]
 [5 7 9]]
(2, 3)


##### **3-Dimensional Array :** Shape Property returns the number of rows and columns with number of elements in the tuple form only
##### Return Output : (number_of_rows,number_of_columns,number_of_elements)

In [51]:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[1,1,1],[4,2,3]]])
print(arr)
print(arr.shape)

[[[1 2 3]
  [4 5 6]]

 [[1 1 1]
  [4 2 3]]]
(2, 2, 3)


##### **============================================================** 
#### **1.4 reshape() :** 
##### **============================================================** 
##### It is used to convert 1D array 2D and 1D array to 3D
##### **Syntax : array_variable.reshape()**
##### First We need to create an array by using any one array creation method
##### Then do array reshape from existing array

##### **1-Dimensional to 2-Dimensional Array :** While Converting 1D array to 2D array,the number of array elements in 1D array is equal to the number of rows and columns in the reshape array
##### Menas if our 1D array size is 12 and we need to reshape it for 2D array, so we need to give row and column size in such way that it should be equal to the size of array(1D) when we multiply row and column in 2D array.

In [53]:
import numpy as np
arr = np.array([1,2,3,4,5,6,1,1,1,4,2,3]) # 12
print(arr)
print(arr.reshape(4,3)) # 4*3 = 12

[1 2 3 4 5 6 1 1 1 4 2 3]
[[1 2 3]
 [4 5 6]
 [1 1 1]
 [4 2 3]]


##### **1-Dimensional to 3-Dimensional Array :** While Converting 1D array to 3D array,the number of array elements in 1D array is equal to the number of rows and columns in the reshape array
##### Menas if our 1D array size is 12 and we need to reshape it for 3D array, so we need to give row and column size and total number of elements size in such way that it should be equal to the size of array(1D) when we multiply row ,column and element in 2D array.

In [55]:
import numpy as np
arr = np.array([1,2,3,4,5,6,1,1,1,4,2,3]) # 12
print(arr)
print(arr.reshape(2,3,2)) # 2*3*2 = 12

[1 2 3 4 5 6 1 1 1 4 2 3]
[[[1 2]
  [3 4]
  [5 6]]

 [[1 1]
  [1 4]
  [2 3]]]
(12,)


In [57]:
import numpy as np
arr = np.array([1,2,3,4,5,6,1,1,1,4,2,3]) # 12
print(arr)
rshape = arr.reshape(2,3,2) # 2*3*2 = 12
print(rshape)
print(rshape.shape)

[1 2 3 4 5 6 1 1 1 4 2 3]
[[[1 2]
  [3 4]
  [5 6]]

 [[1 1]
  [1 4]
  [2 3]]]
(2, 3, 2)


##### **============================================================** 
#### **1.5 size :** 
##### **============================================================** 
##### It is used to return total number of array elements in a array 
##### **Syntax : array_variable.size**
##### First We need to create an array by using any one array creation method
##### Then check the size of an array

##### **1-Dimensional Array :**

In [58]:
import numpy as np
arr = np.array([1,2,3,5,7,9])
print(arr)
print(arr.size)

[1 2 3 5 7 9]
6


##### **2-Dimensional Array :**

In [60]:
import numpy as np
arr = np.array([[1,2,3],[5,7,9]])
print(arr)
print(arr.size)

[[1 2 3]
 [5 7 9]]
6


##### **3-Dimensional Array :**

In [61]:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[1,1,1],[4,2,3]]])
print(arr)
print(arr.size)

[[[1 2 3]
  [4 5 6]]

 [[1 1 1]
  [4 2 3]]]
12


##### **============================================================** 
#### **1.6 itemsize :** 
##### **============================================================** 
##### Itemsize represents the size (in bytes) of each element in a NumPy array.
##### **Syntax : array_variable.size**
##### First We need to create an array by using any one array creation method
##### Then check the itemsize of an array
##### Each element takes 4 bytes

##### **1-Dimensional Array :**

In [62]:
import numpy as np
arr = np.array([1,2,3,5,7,9])
print(arr)
print(arr.itemsize)

[1 2 3 5 7 9]
8


##### **2-Dimensional Array :**

In [63]:
import numpy as np
arr = np.array([[1,2,3],[5,7,9]])
print(arr)
print(arr.itemsize)

[[1 2 3]
 [5 7 9]]
8


##### **3-Dimensional Array :**

In [64]:
import numpy as np
arr = np.array([[[1,2],[5,6]],[[3,5],[7,9]]])
print(arr)
print(arr.itemsize)

[[[1 2]
  [5 6]]

 [[3 5]
  [7 9]]]
8


##### **============================================================** 
#### **1.7 flatten() :** 
##### **============================================================** 
##### It returns a copy of the original array converted into 1D.
##### It Creates a new array (copy), where Original array is NOT affected and Uses extra memory
##### **Syntax : array_variable.flatten(order="C")**
##### First We need to create an array by using any one array creation method (create 2D Array,for 1D array it remains unchange)
##### Then check the flatten of an array
##### **Parameters**
##### Here order is optional
##### 'C' → Row-wise (default) : Reads elements row by row
##### 'F' → Column-wise (Fortran style) : Reads elements column by column
##### 'A' → Preserve order based on memory
##### 'K' → Preserve memory layout
##### 
##### What it actually does (Internally) : It Creates a new contiguous array in memory and Copies all elements into a 1D structure and that Breaks the link with original array
##### That means : New memory allocation happens which is Safe to modify.

##### **Note :** For **1-Dimensional Array** the flatten array is remain unchanged, because Flatten() is used to convert multi dimensional array to single dimentional array, where the array elemenets are stored in memory based on specific order

In [69]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
print(f"Original Array : {arr}")
print(f"Flatten Array : {arr.flatten()}")

Original Array : [1 2 3 4 5 6]
Flatten Array : [1 2 3 4 5 6]


##### **Note :** For **2-Dimensional Array** the flatten array is changed, because Flatten() is used to convert multi dimensional array to single dimentional array, where the array elemenets are stored in memory based on specific order
##### Until or unless we pass the order, it will gives flatten() array as it is , It will not change 
##### By default order is row by row, i,e. order='C'

In [71]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(f"Original Array :\n {arr}")
print(f"Flatten Array : {arr.flatten()}")

Original Array :
 [[1 2 3]
 [4 5 6]]
Flatten Array : [1 2 3 4 5 6]


##### **Note :** For **3-Dimensional Array** the flatten array is changed, because Flatten() is used to convert multi dimensional array to single dimentional array, where the array elemenets are stored in memory based on specific order
##### Until or unless we pass the order, it will gives flatten() array as it is , It will not change 
##### By default order is row by row, i,e. order='C'

In [72]:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(f"Original Array :\n {arr}")
print(f"Flatten Array : {arr.flatten()}")

Original Array :
 [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
Flatten Array : [1 2 3 4 5 6 1 2 3 4 5 6]


##### **Order='C'** → Row-wise (default) : Reads elements row by row

##### **For 1D Array with Order='C'** It perform row by row flatten operation. Where First row remain same as first row only because of 1D Array.

In [73]:
## 1D Array
import numpy as np
arr = np.array([1,2,3,4,5,6])
print(f"Original Array :\n {arr}")
print(f"Flatten Array : {arr.flatten(order='C')}")

Original Array :
 [1 2 3 4 5 6]
Flatten Array : [1 2 3 4 5 6]


##### **For 2D Array with Order='C'** It perform row by row flatten operation. Where First row added by 2nd row.

In [74]:
## 2D Array
import numpy as np
arr = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(f"Original Array :\n {arr}")
print(f"Flatten Array : {arr.flatten(order='C')}")

Original Array :
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
Flatten Array : [ 1  2  3  4  5  6  7  8  9 10 11 12]


##### **For 3D Array with Order='C'** It perform row by row flatten operation. Where First row added to next second row then 3rd row

In [76]:
## 3D Array
import numpy as np
arr = np.array([[[1,2,5,6],[7,9,10,12]],[[3,4,5,6],[8,9,11,12]]])
print(f"Original Array :\n {arr}")
print(f"Flatten Array : {arr.flatten(order='C')}")

Original Array :
 [[[ 1  2  5  6]
  [ 7  9 10 12]]

 [[ 3  4  5  6]
  [ 8  9 11 12]]]
Flatten Array : [ 1  2  5  6  7  9 10 12  3  4  5  6  8  9 11 12]


##### **Order=F'** → Column-wise (Fortran style) : Reads elements column by column

##### **For 1D Array with Order='F'** It perform row by row flatten operation. Where First row remain same as first row only because of 1D Array.

In [77]:
## 1D Array
import numpy as np
arr = np.array([1,2,3,4,5,6])
print(f"Original Array :\n {arr}")
print(f"Flatten Array : {arr.flatten(order='F')}")

Original Array :
 [1 2 3 4 5 6]
Flatten Array : [1 2 3 4 5 6]


##### **For 2D Array with Order='F'** It perform column by column flatten operation
##### Original Array :
##### [[1 2 3 4 5 6]
##### [7 8 9 3 4 2]]
##### Flatten Array : [1 7 2 8 3 9 4 3 5 4 6 2

In [78]:
## 2D Array
import numpy as np
arr = np.array([[1,2,3,4,5,6],[7,8,9,3,4,2]])
print(f"Original Array :\n {arr}")
print(f"Flatten Array : {arr.flatten(order='F')}")

Original Array :
 [[1 2 3 4 5 6]
 [7 8 9 3 4 2]]
Flatten Array : [1 7 2 8 3 9 4 3 5 4 6 2]


##### **For 3D Array with Order='F'** It perform column by column flatten operation, Where 1st row ,1st column added with 2nd row 1st column, then  1st row , 2nd column with 2nd row 2nd column added (column by column)
##### Original Array :
##### [[[ 1  2  5  6]
#####  [ 7  9 10 12]]
##### [[ 3  4  5  6]
#####  [ 8  9 11 12]]]
##### Flatten Array : [ 1  3  7  8  2  4  9  9  5  5 10 11  6  6 12 12]

In [79]:
## 3D Array
import numpy as np
arr = np.array([[[1,2,5,6],[7,9,10,12]],[[3,4,5,6],[8,9,11,12]]])
print(f"Original Array :\n {arr}")
print(f"Flatten Array : {arr.flatten(order='F')}")

Original Array :
 [[[ 1  2  5  6]
  [ 7  9 10 12]]

 [[ 3  4  5  6]
  [ 8  9 11 12]]]
Flatten Array : [ 1  3  7  8  2  4  9  9  5  5 10 11  6  6 12 12]


##### **Order='A'** → Preserve order based on memory

##### **For 1D Array with Order='A'** It perform Preserve Order Based memory where oder is already preserved we can't change by flatten operation. Where First row remain same as first row only because of 1D Array.

In [80]:
## 1D Array
import numpy as np
arr = np.array([1,2,3,4,5,6])
print(f"Original Array :\n {arr}")
print(f"Flatten Array : {arr.flatten(order='A')}")

Original Array :
 [1 2 3 4 5 6]
Flatten Array : [1 2 3 4 5 6]


##### **For 2D Array with Order='A'** It perform Preserve Order Based memory where oder is already preserved we can't change by flatten operation. Where First row remain same as first row only because of Array order is preserved.

In [81]:
## 2D Array
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(f"Original Array :\n {arr}")
print(f"Flatten Array : {arr.flatten(order='A')}")

Original Array :
 [[1 2 3]
 [4 5 6]]
Flatten Array : [1 2 3 4 5 6]


##### **For 3D Array with Order='A'** It perform Preserve Order Based memory where oder is already preserved we can't change by flatten operation. Where First row remain same as first row only because of Array order is preserved.

In [ ]:
## 3D Array
import numpy as np
arr = np.array([1,2,3,4,5,6])
print(f"Original Array :\n {arr}")
print(f"Flatten Array : {arr.flatten(order='A')}")

##### **Order='K'** → Preserve memory layout

##### **For 1D Array with Order='K'** It perform Preserve memory layout where oder is already preserved we can't change by flatten operation. Where First row remain same as first row only because of Array order is preserved in memory.

In [83]:
## 1D Array
import numpy as np
arr = np.array([1,2,3,4,5,6])
print(f"Original Array :\n {arr}")
print(f"Flatten Array : {arr.flatten(order='K')}")

Original Array :
 [1 2 3 4 5 6]
Flatten Array : [1 2 3 4 5 6]


##### **For 2D Array with Order='K'** It perform Preserve memory layout where oder is already preserved we can't change by flatten operation. Where First row remain same as first row only because of Array order is preserved in memory.

In [84]:
## 2D Array
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(f"Original Array :\n {arr}")
print(f"Flatten Array : {arr.flatten(order='K')}")

Original Array :
 [[1 2 3]
 [4 5 6]]
Flatten Array : [1 2 3 4 5 6]


##### **For 3D Array with Order='K'** It perform Preserve memory layout where oder is already preserved we can't change by flatten operation. Where First row remain same as first row only because of Array order is preserved in memory.

In [87]:
## 3D Array
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[2,4,5],[5,6,3]]])
print(f"Original Array :\n {arr}")
print(f"Flatten Array : {arr.flatten(order='C')}")

Original Array :
 [[[1 2 3]
  [4 5 6]]

 [[2 4 5]
  [5 6 3]]]
Flatten Array : [1 2 3 4 5 6 2 4 5 5 6 3]


##### **============================================================** 
#### **1.8 ravel() :** 
##### **============================================================** 
##### It returns a view of the original array (not a copy).If changes made then it also affects a original array
##### Returns a view (same memory) & Changes affect original array with Faster and memory-efficient
##### **Syntax : array_variable.ravel(order="C")**
##### First We need to create an array by using any one array creation method (create 2D Array,for 1D array it remains unchange)
##### Then check the ravel of an array
##### **Parameters**
##### Here order is optional
##### 'C' → Row-wise (default) : Reads elements row by row
##### 'F' → Column-wise (Fortran style) : Reads elements column by column
##### 'A' → Preserve order based on memory
##### 'K' → Preserve memory layout
##### What it actually does (Internally) : It Returns a view (whenever possible) & Does not copy data and Points to same memory block
##### If memory layout is complex → it may return a copy (rare case)

##### **1-Dimensional Array :** Here if we update one element, It also affects the original array ,It will not create a separate copy, It access same original one and modify it

In [90]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
rav = arr.ravel()
rav[0]=100
print(f"Original Array : {arr}")
print(f"Flatten Array : {rav}")

Original Array : [100   2   3   4   5   6]
Flatten Array : [100   2   3   4   5   6]


##### **2-Dimensional Array :** Here if we update one element, It also affects the original array ,It will not create a separate copy, It access same original one and modify it
##### Here if i am not mentioning the 2nd Index , By default it consider 0 Index Position from column

In [91]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
rav = arr.ravel()
rav[0]=100
print(f"Original Array : {arr}")
print(f"Flatten Array : {rav}")

Original Array : [[100   2   3]
 [  4   5   6]]
Flatten Array : [100   2   3   4   5   6]


##### Here if i am mentioning the 2nd Index then it raises error Because After applying ravel() It becomes single 1D array
##### We can apply row and column index before applying ravel

In [100]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
arr[0][1]=100
rav = arr.ravel()
print(f"Original Array : {arr}")
print(f"Flatten Array : {rav}")

Original Array : [[  1 100   3]
 [  4   5   6]]
Flatten Array : [  1 100   3   4   5   6]


##### Even though we can update the value even after applying ravel, But to change make use of array_variable only to update the element then go through ravel

In [101]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
rav = arr.ravel()
arr[0][1]=100
print(f"Original Array : {arr}")
print(f"Flatten Array : {rav}")

Original Array : [[  1 100   3]
 [  4   5   6]]
Flatten Array : [  1 100   3   4   5   6]


In [108]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
rav = arr.ravel()
rav[0]=100
print(f"Original Array : {arr}")
print(f"Flatten Array : {rav}")

Original Array : [[100   2   3]
 [  4   5   6]]
Flatten Array : [100   2   3   4   5   6]


##### After applying ravel We can't do 2D Indexing Because it becomes 1D array

In [102]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
rav = arr.ravel()
rav[0][1]=100
print(f"Original Array : {arr}")
print(f"Flatten Array : {rav}")

TypeError: 'numpy.int64' object does not support item assignment

##### **Order='C' :** Row by Row ( It reads element row by row) 
##### For 1D array it will not work because it converts the 2D array or 3D array to 1D array of ravel
##### If we done any changes with respect to ravel array then it also change in original array

In [123]:
# 1D Array
import numpy as np
arr = np.array([1,2,3,5,6])
rav = arr.ravel(order='C')
rav[0]=100
print(f"Original Array : {arr}")
print(f"Flatten Array : {rav}")

Original Array : [100   2   3   5   6]
Flatten Array : [100   2   3   5   6]


In [124]:
# 2D Array
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
rav = arr.ravel(order='C')
rav[0]=100
print(f"Original Array : {arr}")
print(f"Flatten Array : {rav}")

Original Array : [[100   2   3]
 [  4   5   6]]
Flatten Array : [100   2   3   4   5   6]


In [125]:
# 3D Array
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[6,2,6],[9,2,4]]])
rav = arr.ravel(order='C')
rav[0]=100
print(f"Original Array : {arr}")
print(f"Flatten Array : {rav}")

Original Array : [[[100   2   3]
  [  4   5   6]]

 [[  6   2   6]
  [  9   2   4]]]
Flatten Array : [100   2   3   4   5   6   6   2   6   9   2   4]


##### **Order='F' :** Column by column ( It reads element column by column) 
##### For 1D array it will not work because it converts the 2D array or 3D array to 1D array of ravel
##### If we done any changes with respect to ravel array then it also change in original array

In [120]:
# 1D Array
import numpy as np
arr = np.array([1,2,3,4,5,6])
rav = arr.ravel(order='F')
rav[0]=100
print(f"Original Array : {arr}")
print(f"Flatten Array : {rav}")

Original Array : [100   2   3   4   5   6]
Flatten Array : [100   2   3   4   5   6]


In [121]:
# 2D Array
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
rav = arr.ravel(order='F')
rav[0]=100
print(f"Original Array : {arr}")
print(f"Flatten Array : {rav}")

Original Array : [[1 2 3]
 [4 5 6]]
Flatten Array : [100   4   2   5   3   6]


In [122]:
# 3D Array
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[6,2,6],[9,2,4]]])
rav = arr.ravel(order='F')
rav[0]=100
print(f"Original Array : {arr}")
print(f"Flatten Array : {rav}")

Original Array : [[[1 2 3]
  [4 5 6]]

 [[6 2 6]
  [9 2 4]]]
Flatten Array : [100   6   4   9   2   2   5   2   3   6   6   4]


##### **Order='A' :** It reads by Preserve Order Based on Memory  
##### For 1D array it will not work because it converts the 2D array or 3D array to 1D array of ravel
##### If we done any changes with respect to ravel array then it also change in original array

In [116]:
# 1D Array
import numpy as np
arr = np.array([1,2,4,5,6])
rav = arr.ravel(order='A')
rav[0]=100
print(f"Original Array : {arr}")
print(f"Flatten Array : {rav}")

Original Array : [100   2   4   5   6]
Flatten Array : [100   2   4   5   6]


In [114]:
# 2D Array
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
rav = arr.ravel(order='A')
rav[0]=100
print(f"Original Array : {arr}")
print(f"Flatten Array : {rav}")

Original Array : [[100   2   3]
 [  4   5   6]]
Flatten Array : [100   2   3   4   5   6]


In [115]:
# 3D Array
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[6,2,6],[9,2,4]]])
rav = arr.ravel(order='A')
rav[0]=100
print(f"Original Array : {arr}")
print(f"Flatten Array : {rav}")

Original Array : [[[100   2   3]
  [  4   5   6]]

 [[  6   2   6]
  [  9   2   4]]]
Flatten Array : [100   2   3   4   5   6   6   2   6   9   2   4]


##### **Order='K' :** It reads by Preserve Memory Layout 
##### For 1D array it will not work because it converts the 2D array or 3D array to 1D array of ravel
##### If we done any changes with respect to ravel array then it also change in original array

In [117]:
# 1D Array
import numpy as np
arr = np.array([1,2,3,5,6])
rav = arr.ravel(order='K')
rav[0]=100
print(f"Original Array : {arr}")
print(f"Flatten Array : {rav}")

Original Array : [100   2   3   5   6]
Flatten Array : [100   2   3   5   6]


In [118]:
# 2D Array
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
rav = arr.ravel(order='K')
rav[0]=100
print(f"Original Array : {arr}")
print(f"Flatten Array : {rav}")

Original Array : [[100   2   3]
 [  4   5   6]]
Flatten Array : [100   2   3   4   5   6]


In [119]:
# 3D Array
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[6,2,6],[9,2,4]]])
rav = arr.ravel(order='K')
rav[0]=100
print(f"Original Array : {arr}")
print(f"Flatten Array : {rav}")

Original Array : [[[100   2   3]
  [  4   5   6]]

 [[  6   2   6]
  [  9   2   4]]]
Flatten Array : [100   2   3   4   5   6   6   2   6   9   2   4]
