# 1.Array with Constant

In [1]:
import numpy as np
arr = np.random.randint(1,10,5)
print(arr)

[1 1 8 9 1]


In [4]:
arr+1

array([ 2,  2,  9, 10,  2], dtype=int32)

In [5]:
arr-1

array([0, 0, 7, 8, 0], dtype=int32)

In [6]:
arr*2

array([ 2,  2, 16, 18,  2], dtype=int32)

In [7]:
arr/2

array([0.5, 0.5, 4. , 4.5, 0.5])

In [8]:
arr//2

array([0, 0, 4, 4, 0], dtype=int32)

In [9]:
arr%10

array([1, 1, 8, 9, 1], dtype=int32)

In [10]:
arr**2

array([ 1,  1, 64, 81,  1], dtype=int32)

In [11]:
arr^2 # adding by 2

array([ 3,  3, 10, 11,  3], dtype=int32)

# 2. Array with Array

In [13]:
import numpy as np
arr1 = np.random.randint(1,10,5)
arr2 = np.random.randint(1,10,5)
print(arr1)
print(arr2)

[4 5 7 5 4]
[8 6 3 7 4]


In [14]:
arr1+arr2

array([12, 11, 10, 12,  8], dtype=int32)

In [16]:
arr1-arr2

array([-4, -1,  4, -2,  0], dtype=int32)

In [17]:
arr1*arr2

array([32, 30, 21, 35, 16], dtype=int32)

In [18]:
arr1/arr2

array([0.5       , 0.83333333, 2.33333333, 0.71428571, 1.        ])

In [19]:
arr1//arr2

array([0, 0, 2, 0, 1], dtype=int32)

In [20]:
arr1**arr2

array([65536, 15625,   343, 78125,   256], dtype=int32)

In [21]:
arr1%arr2

array([4, 5, 1, 5, 0], dtype=int32)

In [22]:
arr1^arr2

array([12,  3,  4,  2,  0], dtype=int32)

# 3.Array with Built-in Methods

In [24]:
# Sort() : it sorts the array elements
import numpy as np
arr = np.random.randint(1,10,5)
print(arr)
print(np.sort(arr))

[5 8 1 6 3]
[1 3 5 6 8]


In [25]:
# argsort() : it will returns the sorted indexs of array elements
arr = np.random.randint(1,10,5)
print(arr)
print(np.argsort(arr))

[2 1 6 5 8]
[1 0 3 2 4]


In [39]:
arr = np.random.randint(1,10,5)
print(arr)
print(np.min(arr))

[9 8 4 4 9]
4


In [40]:
arr = np.random.randint(1,10,5)
print(arr)
print(np.argmin(arr))

[4 3 6 5 5]
1


In [41]:
arr = np.random.randint(1,10,5)
print(arr)
print(np.max(arr))

[9 2 8 8 6]
9


In [43]:
arr = np.random.randint(1,10,5)
print(arr)
print(np.argmax(arr))

[8 6 6 6 9]
4


In [44]:
arr = np.random.randint(1,10,5)
print(arr)
print(np.sum(arr))

[6 2 6 8 9]
31


In [52]:
arr = np.random.randint(1,10,5)
print(arr)
print(np.average(arr))

[9 4 5 9 1]
5.6


In [53]:
arr = np.random.randint(1,10,5)
print(arr)
print(np.mean(arr))

[2 4 8 7 2]
4.6


In [67]:
arr = np.random.randint(1,10,5)
print(arr)
print(np.median(arr)) #Sorted array ka middle value , If even → average of two middle values

[4 5 2 1 4]
4.0


In [62]:
arr = np.random.randint(1,10,5)
print(arr)
print(np.sqrt(arr)) 

[9 8 8 6 2]
[3.         2.82842712 2.82842712 2.44948974 1.41421356]


In [64]:
arr = np.random.randint(1,10,5) #Variance=n∑(x−mean)^2/total numbers
print(arr)
print(np.var(arr)) # mean=2.8 => (0.64+4.84+0.04+3.24+0.04)/5=1.76

[2 5 3 1 3]
1.7600000000000002


In [71]:
arr = np.random.randint(1,10,5)
print(arr)
print(np.mean(arr))
print(np.var(arr)) 
print(np.std(arr)) #sqrt(var)

[6 4 3 4 9]
5.2
4.5600000000000005
2.1354156504062622


In [63]:
arr = np.random.randint(1,10,5)
print(arr)
print(np.mode(arr)) 

[5 9 5 8 4]


AttributeError: module 'numpy' has no attribute 'mode'

In [59]:
arr = np.random.randint(1,10,5)
print(arr)
print(np.prod(arr)) 

[4 8 4 8 3]
3072


In [60]:
print(arr)
print(np.dot(arr)) 

[4 8 4 8 3]


TypeError: dot() missing 1 required positional argument: 'b'

In [47]:
arr = np.random.randint(1,10,5)
print(arr)
print(np.sum(arr,axis=0))

[6 4 4 7 5]
26


In [48]:
arr = np.random.randint(1,10,5)
print(arr)
print(np.sum(arr,axis=1))

[3 2 2 8 5]


AxisError: axis 1 is out of bounds for array of dimension 1

In [49]:
##### Note Axis=0 Row wise operation but column wise result
arr1 = np.random.randint(1,10,5)
arr2 = np.random.randint(1,10,5)
print(arr1)
print(arr2)
print(np.sum((arr1,arr2),axis=0))

[8 1 1 8 3]
[4 7 6 4 6]
[12  8  7 12  9]


In [50]:
##### Note Axis=1 Column wise operation but row wise result
print(arr1)
print(arr2)
print(np.sum((arr1,arr2),axis=1))

[8 1 1 8 3]
[4 7 6 4 6]
[21 27]


In [74]:
arr1 = np.random.randint(1,10,5)
arr2 = np.random.randint(1,10,5)
print(arr1)
print(arr2)
print(np.average((arr1,arr2),axis=0))

[6 6 3 4 4]
[7 1 6 8 3]
[6.5 3.5 4.5 6.  3.5]


In [75]:
print(arr1)
print(arr2)
print(np.average((arr1,arr2),axis=1))

[6 6 3 4 4]
[7 1 6 8 3]
[4.6 5. ]


In [76]:
arr1 = np.random.randint(1,10,5)
arr2 = np.random.randint(1,10,5)
print(arr1)
print(arr2)
print(np.prod((arr1,arr2),axis=0))

[5 2 8 1 5]
[8 3 8 2 5]
[40  6 64  2 25]


In [77]:
arr1 = np.random.randint(1,10,5)
arr2 = np.random.randint(1,10,5)
print(arr1)
print(arr2)
print(np.prod((arr1,arr2),axis=1))

[9 3 4 9 2]
[1 5 4 6 6]
[1944  720]


In [83]:
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3])
print(arr1)
print(arr2)
print(np.dot(arr1,arr2))
print(np.prod((arr1,arr2)))

[1 2 3]
[1 2 3]
14
36
